local my_language = {
	give_vehicle = "Přidal sis ~b~%s~w~ do inventáře.",
	store_vehicle_command = "Schovat vozidlo, které řídíš",
	no_entity_vehicle = "~r~Toto vozidlo neexistuje nebo je příliš daleko od tebe.",
	no_entity_vehicle_id = "~r~Toto vozidlo nemá žádné ID, nemůžeš ho schovat.",
	store_vehicle = "~b~Schoval sis vozidlo.",
	teleported_former_position = "~g~Byl jsi teleportován na tvou poslední uloženou pozici.",
	not_enough_of = "~r~Nemáš dostatek %s.",
	max_storage_chest = "~r~Máš plný sklad.",
	cant_carry_more_items = "~r~Do tvého inventáře se nic nevleze (je plný).",
	put_item = "Vložil jsi ~g~x%s~w~ %s~w~.",
	take_item = "Vzal jsi ~g~x%s~w~ %s~w~.",
	delete_item = "Odstranil jsi ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Bereš si ~g~%s~w~.",
	bind_weapon_command = "Zkratka na slot pro zbraně %s",
	kevlar_broke = "~r~AHH!~n~~w~Tvůj armor se rozbil.",
	inventory_command = "Otevřít inventář",
	press_enter_to_join = "Zmáčkni ~g~ENTER~w~ pro start hry.",
	new_character = "Nová postava",
	survivor = "Přeživší",
	right = "Vpravo",
	left = "Vlevo",
	male = "Muž",
	female = "Žena",
	ped = "Ped",
	name = "Jméno",
	sex = "Pohlaví",
	title = "Nadpis",
	select_this_character = "Vybrat tuto postavu",
	no_entity_zombie = "Zombík neexistuje nebo je příliš daleko od tebe.",
	you_found = "Našel jsi ~g~%sx %s~w~.",
	you_found_nothing = "Nenašel jsi ~g~nic~w~.",
	press_e_to_loot = "Zmáčkni ~b~[E]~w~ k lootování",
	full_for_item = "~r~Pro tuto věc nemáš dostatek místa.",
	put_item_container = "Vložil jsi ~g~x%s~w~ %s~w~ do skladu.",
	take_item_container = "Vzal jsi ~g~x%s~w~ %s~w~ ze skladu.",
	not_allowed_here = "~r~Zde to nemůžeš udělat.",
	cant_store_moving_veh = "~r~Nemůžeš uschovat vozidlo, pokud je v pohybu.",
	use_repair_tool = "použij repair tool",
	please_get_closer = "~b~Prosím běž blíž, v blízkosti nikdo/nic není.",
	you_cancel_action = "~r~Přerušil jsi akci.",
	selected_target_message = "Vybraný cíl:~n~%s~n~~r~Zmáčkni ~b~Y~r~ pro ukončení~n~~r~Zmáčkni ~g~X~r~ pro pokračování.",
	target_you = "~b~TY",
	target_screen = "~g~Zobrazeno",
	take_this_path = "jít touto cestou",

	-- hud
	default_hud = "Defaultní HUD",
	cinema_hud = "Cinema HUD",
	no_hud = "Žádný HUD",

	-- perms
	kick_member = "Vyhazovat členy",
	edit_member = "Upravovat členy",
	edit_rank = "Upravovat hodnosti",
	create_rank = "Vytvářet hodnosti",
	delete_rank = "Mazat hodnosti",
	edit_structure = "Upravit informace o crew",
	edit_permissions = "Upravit pravomoce",
	permission_level = "Pravomoce uděleny",
	red_delete = "Smazat",
	rank = "Hodnost",
	red_kick = "Vyhodit",
	crew_name = "Jméno crew",
	slogan = "Slogan",
	information = "informace",
	boss_rank = "Boss rank name",
	member_rank = "Newbie rank name",
	member = "Člen",

	permissions_manager = "správce pravomocí",
	members_manager = "správce členů",
	ranks_manager = "správce hodností",
	ranks_list = "seznam hodností",
	members_list = "seznam členů",
	create_a_rank = "vytvořit hodnost",
	invite_someone = "pozvat někoho",
	stats = "Statistiky",
	total_ranks = "Počet hodností",
	total_members = "Počet členů",
	level = "Level",
	actions = "akce",
	crew_manager = "správce crew",
	you_created_a_new_crew = "Vytvořil jsi novou crew: %s",
	you_deleted_your_crew = "Smazal jsi svou crew.",
	you_are_not_in_a_crew = "Nejsi v žádné crew",
	you_joined_the_crew = "Připojil ses do crew '%s'",
	kick_failed = "Neúspěšně jsi vyhodil hráče, důvod: %s",
	already_in_crew = "Už jsi v nějaké crew.",
	no_invitation = "Neobdržel jsi žádnou pozvánku.",
	left_crew = "Opustil jsi crew.",
	permission_updated = "Pravomoce <C>~g~%s</C>~w~ byly aktualizovány.",
	incorrect_name = "~r~Formát jména je nesprávný",
	incorrect_rank_perm = "~r~Chyba\n~w~Název hodnosti nebo úroveň hodnosti je neplatná.",
	warn_rank_limit = "~r~Překročil jsi limit hodností.",
	create_rank_success = "~g~Úspěšně\n~w~jsi vytvořil novou hodnost <C>~b~%s</C>~w~ s pravomocemi <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Nemůžeš spravovat hráče, který má vyšší pravomoce než ty.",
	you_sent_an_invitation = "Odeslal jsi pozvánku hráči <C>~g~%s</C>~w~ do tvojí crew.",
	you_received_an_invitation = "Obdržel jsi pozvánku do crew.\n~b~/%s pro přijmutí.",
	invitation_expired = "Pozvánka vypršela",
	crew_kick_success = "Vyhodil jsi <C>~b~%s</C>~w~ z tvojí crew.",
	first_rank_warning = "První hodnost je 'defaultní' hodnost.",

	you_updated_this = "Aktualizoval jsi %s na ~g~<C>%s</C>~w~.",
	changes_saved_on = "Změny provedeny na <C>~g~%s</C>~w~ byly uloženy.",
	yes = "ano",
	no = "ne",
	none = "Žádný",
	character_id = "Character ID",
	server_id = "Server ID",
	report = "Nahlásit",
	rename = "Přejmenovat",
	trade_with = "Obchodovat",
	
	please_wait_x_before = "~r~Prosím počkej %s sekund předtím, než to uděláš.",

	-- cloth
	take_outfit = "Koupit tento outfit",
	wardrobe_options = "možnosti šatníku",
	wardrobe = "šatník",
	manual_options = "manuální nastavení",
	manual_mode = "manuální výběr oblečení",
	save_outfit = "Uložit tento outfit",
	variation = "variace",
	outfits = "outfity",
	cloth_shop = "Obchod s oblečením",
	ped_cloth_shop = "Výběr peda",
	manual_props = "manuální doplňky",
	manuel = "Manuální",
	new_name = "Nové jméno",
	outfit_name = "Jméno outfitu",
	variations_saved = "~g~Úspěšně~n~~w~sis vybral nové oblečení.",
	equipped_new_outfit = "Oblékl sis nový outfit: ~b~%s",
	warning_limit_outfits = "Překročil jsi limit uložených outfitů. ~g~(%s)",
	saved_new_outfit = "Uložil sis nový outfit: ~b~%s~w~.",
	rename_outfit = "Tvůj outfit ~b~%s~w~ byl přejmenován na ~g~%s~w~.",
	delete_outfit = "Tvůj outfit: ~b~%s~w~ byl odstraněn.",

	torso = "Trup",
	props = "Doplňky",
	top = "Vršek",
	tops = "Vršek",
	badge = "Nášivky",
	pants = "Kalhoty",
	pant = "Kalhoty",
	shoes = "Boty",
	bags = "Batohy",
	undershirt = "Tričko",
	neck = "Řetězy",
	bracelets = "Náramky",
	montres = "Hodinky",
	earrings = "Náušnice",
	glasses = "Brýle",
	hats = "Čepice",
	graphiques = "Design",

	-- health
	inconscious = "V bezvědomí",
	doing_something = "Něco děláš",
	time_before_respawn = "Čas před respawnem",
	you_died = "~r~Zemřel jsi.",
	healing_wounds = "Uzdravování ran",
	already_doing_something = "~r~Již něco děláš.",
	you_have_been_healed = "~g~Byl jsi uzdraven.",
	you_respawned = "~g~Respawnul ses.",

	player_too_far_to_interact = "~r~Hráč se kterým chceš provádět interakci je příliš daleko.",
	send_trade_invitation_to = "Poslal jsi nabídku k obchodu hráči ~b~%s~w~.\n~b~Počkej až hráč, kterému jsi nabídku poslal, nabídku přijme.",
	receive_invitation_from = "Dostal jsi nabídku k obchodu od ~b~%s~w~.\n~b~Napiš ~w~/trade accept %s~b~ pro přijmutí nabídky.",

	invalid_command_args = "Neplatné argumenty příkazu: %s",
	start_trade_command_help = "Obchodovat s dalším hráčem",
	accept_trade_command_help = "Přijmout nabídku",
	deny_trade_command_help = "Odmítnout nabídku",
	invalid_invitation = "Tato nabídka je neplatná nebo již neexistuje",
	name_accepted_your_trade_invitation = "~b~%s~w~ přijal tvou nabídku",
	you_accepted_trade_invitation_of_name = "Přijal jsi nabídku od %s",
	name_denied_your_trade_invitation = "~b~%s~w~ odmítl tvou nabídku",
	you_denied_trade_invitation_of_name = "Odmítl jsi obchod od %s",
	you_already_trading = "Jsi zaneprázdněný",
	other_already_trading = "Hráč se kterým chceš obchodovat již s někým obchoduje",

	other_player_not_enough_money = "~r~Obchod nebyl úspěšný. Hráč se kterým obchoduješ nemá dostatek peněz.",
	you_player_not_enough_money = "~r~Obchod nebyl úspěšný. Nemáš dostatek peněz.",
	other_player_not_enough_item = "~r~Obchod nebyl úspěšný. Hráč se kterým jsi obchodoval neměl dostatek nějakého předmětu.",
	you_player_not_enough_item = "~r~Obchod nebyl úspěšný. Neměl jsi dostatek nějakého předmětu.",
	success_trade = "~g~Obchod byl úspěšný.",
	fail_trade_other_player = "~r~Obchod nebyl úspěšný, hráč se kterým obchoduješ odešel.",
	trade_other_full_item = "~r~Obchod nebyl úspěšný, hráč se kterým obchoduješ nemá dostatek místa.",
	trade_full_for_item = "~r~Obchod nebyl úspěšný, nemáš dostatek místa.",

	press_e_to_loot_inv = "Zmáčkni ~INPUT_CONTEXT~ pro otevření lootu.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Zmáčkni ~INPUT_CONTEXT~ pro interakci s ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "Zmáčkni ~INPUT_CONTEXT~ pro ~b~%s~w~.",
	press_e_to_open_catalog = "Zmáčkni ~b~E~w~ pro přečtení ~g~katalogu~w~.",
	this_person = "touto osobou",
	the_shop = "tohoto obchodu",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Tohle nemůžeš udělat.",

	no_weapon = "~r~Nemáš vytaženou žádnou zbraň.",
	no_need_ammo = "~r~Do této zbraně nepotřebuješ nabíjet žádné náboje.",
	not_right_ammo = "~r~Používáš špatné náboje, potřebuješ ~b~%s~w~.",
	you_used_ammo = "Nabil jsi ~b~%s~w~ s ~b~x%s~w~ typu ~b~%s~w~.",

	choose_a_destination = "výběr ~b~destinace",
	open_your_chest = "otevření tvého skladu",
	no_enough_money = "~r~Na to nemáš peníze.",
	you_paid = "Zaplatil jsi ~g~$%s~w~ za ~b~%s~w~.",
	you_paid_basket = "Zaplatil jsi ~g~$%s~w~ za tvůj košík.",
	you_sell_basket = "Obdržel jsi ~g~$%s~w~ za prodej ~b~x%s~w~ položek.",

	you_repaired_your_vehicle = "~g~Opravil jsi své vozidlo.",
	repairing_your_vehicle = "Opravuješ vozidlo",
	wheels_are_fine = "~r~Kola vozidla jsou v pohodě.",
	changing_wheel = "Výměna kol",
	you_repaired_the_wheels = "~g~Opravil jsi kola tvého vozidla.",

	front_post_ls = "Front Post Los Santos",
	front_post_ls_2 = "Front Post Los Santos 2",
	front_post_bc = "Front Post Blaine County",
	front_post_bc_2 = "Front Post Blaine County 2",
	main_post_ls = "Safe City Los Santos",
	main_post_bc = "Safe City Blaine County",
	random_zone = "Random zóna (seskok padákem)",

	this_item_is_equipped = "~r~Tuto věc máš vytaženou, dej ji pryč z dolní lišty.",
	only_in_safezone = "~r~Tohle nemůžeš udělat mimo safezónu.",
	-- Commerce
	feature_gold_only = "Tato funkce je pouze pro ~y~hráče s Gold rolí~w~.",
	feature_diamond_only = "Tato funkce je pouze pro ~b~hráče s Diamond rolí~w~.",
	you_turned_into = "Proměnil ses v ~g~%s~w~.",
	wait_between_transformation = "~r~Prosím počkej chvíli předtím, než se budeš chtít v něco proměnit znovu.",
	wait_between = "~r~Prosím počkej chvíli předtím, než to zkusíš znovu.",
	available_morphs = "Dostupné proměny",
	animal_models = "Modely zvířat",
	zombie_models = "Modely zombíků",
	success_update_name = "Změnil jsi svoje jméno na ~b~%s~w~.",
	success_reset_stats = "~g~Úspěšně sis vyresetoval svoje staty. (Tabulka se aktualizuje později)",

	-- animals
	boar = "Boar",
	cat = "Cat",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Cow",
	coyote = "Coyote",
	deer = "Deer",
	hen = "Hen",
	husky = "Husky",
	mtlion = "Lion",
	pig = "Pig",
	poodle = "Poodle",
	pug = "Pug",
	rabbit = "Rabbit",
	rat = "Rat",
	retriever = "Retriever",
	shepherd = "Shepherd",
	westy = "Westy",

	player_id = "ID hráče",
	bounty = "Odměna",
	reason = "Důvod",
	id_player_not_found = "~r~Žádný hráč nebyl nalezen s tímto ID.",

	ammo_dealer = "Obchodník s náboji",
	misc_dealer = "Obchodník s dalším vybavením",
	veh_dealer = "Obchodník s vozidly",
	custom_dealer = "LS Custom",
	gun_dealer = "Obchodník se zbraněmi",

	bounty_created = "Zaplatil jsi ~g~$%s~w~ za vypsání odměny na ~b~%s~w~.",
	contract_success = "Odměnu, kterou jsi vypsal na ~r~%s~w~ byla odeslána ~b~%s~w~.",
	a_contract_on_your_head = "~r~Byla na tebe vypsána odměna. Ten, kdo tě zabil dostal odměnu.",
	reward_for_contract = "Lovec odměn! Dostal jsi odměnu ~g~$%s~w~ za zabití ~b~%s~w~.",

	hey_can_help_you = "Čus, jak ti můžu pomoct?",
	i_want_to_buy_items = "Chci si něco koupit",
	i_want_to_sell_items = "Chci něco prodat",

	press_context_or_jump_to_get_up = "Zmáčkni ~INPUT_CONTEXT~ nebo ~INPUT_JUMP~ pro ~b~zvednutí se~w~.",
	server_restart_warning = "Server se bude za chvíli restartovat..",
	auto_restart_in = "Automatický restart proběhne za %s sekund.",

	not_allowed_create_character = "Nemůžeš si vytvořit novou postavu.",
	character_not_yours = "Tato postava není tvoje.",
	character_does_not_exist = "Tato postava již neexistuje.",
	loading_character = "Načítání tvojí postavy...",

	playtime_is = "~b~Odehraný čas na Extinction:\n~w~%s",
	dont_spam = "^1Nespamuj!",

	babygod_warning = "~b~Opustil jsi safezónu, chvíli budeš nesmrtelný.",

	-- LS Custom
	modifications_classiques = "Klasické modifikace",
	modifications_custom = "Speciální modifikace",
	modifications_benny = "Benny's modifikace",
	paint = "barva",
	custom_your_car = "Vytuň svoje auto",
	wheels_modifications = "Kola",
	performances = "Výkon",
	neons = "Neony",
	extra = "Extra",
	klaxon = "Horn",
	teinte_fenetre = "Windows tint",
	phares_xenons = "Xenon headlights",
	modele_plaque = "Plate model",
	livery = "Livery",
	headlight_color = "Headlights color",
	wheel_type = "Wheel type",
	primary_wheel_type = "Primary wheel type",
	back_wheel_type = "Back wheel type",
	wheel_color = "Wheel color",
	tire_smoke = "Tire smoke",
	custom_color = "Custom color",
	custom_wheel = "Custom wheel",
	custom_back_wheel = "Custom back wheel",
	suspension = "Suspension",
	transmission = "Transmission",
	moteur = "Engine",
	frein = "Brake",
	turbo = "Turbo",
	primary_color = "Primary color",
	secondary_color = "Secondary color",
	interior_color = "Interior color",
	dashboard_color = "Dashboard color",
	color_effect = "Color effect",
	left_neon = "Left neon",
	right_neon = "Right neon",
	front_neon = "Front neon",
	back_neon = "Back neon",

	aileron = "Spoiler",
	pc_front = "Front bumper",
	pc_back = "Rear bumper",
	carroserie = "Side skirt",
	exhaust = "Exhaust",
	cadre = "Frame",
	calandre = "Grille",
	capot = "Hood",
	gb_left = "Left fender",
	gb_right = "Right fender",
	roof = "Roof",
	plate_support = "Plate holders",
	front_plate = "Front plate",
	interior_style = "Interior style",
	figurine = "Figurine",
	motif_dashboard = "Dashboard style",
	cadran = "Dial design",
	haut_parleur_portes = "Speaker doors",
	motif_sieges = "Seat style",
	volant = "Steering wheel",
	levier = "Shifter leavers",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Speaker back doors",
	hydrolique = "Hydraulics",
	moteur = "Engine",
	filtres_air = "Air filter",
	entretoises = "Spacers",
	arc_couverture = "Arch",
	antenne = "Antenna",
	motif_exterieur = "Exterior style",
	reservoir = "Tank",
	window = "Window",
	style = "Style",
	default = "Default",
	type = "Type",
	normal = "Normal",
	black = "Black",
	black_smoke = "Black smoke",
	simple_smoke = "Simple smoke",
	stock = "Stock",
	limo = "Limousine",
	sa_black = "San Andreas black",
	sa_blue = "San Andreas blue",
	sa_white = "San Andreas white",
	simple_white = "Simple white",
	ny_white = "North Yankton white",
	race = "Race",
	sport = "Sport",
	stock = "Stock",
	street = "Street",
	discount = "Sleva",
	select_your_car = "Vyber svoje auto",
	select_car_custom = "Vyber vozidlo, které chceš vytunit. Číslo mezi šipkama je číslo vozidla, pokud jich máš v inventáři více.",
	loading_vehicle = "Spawnování vozidla",
	invalid_vehicle = "~r~Nesprávné vozidlo.",
	invalid_vehicle_please_spawn = "~r~Nesprávné vozidlo. Prosím spawni svoje auto alespoň jednou předtím, než ho budeš modifikovat.",
	free_take_and_validate = "Všechno je zdarma. Vyber si co chceš a potvrď svůj výběr!",
	car_custom_saved = "~g~Modifikace tvého vozidla byly uloženy.",

	-- Character creation
	character_creation = "Vytvoření postavy",
	confirm = "",
	start_playing = "Hrát",
	appearance = "vzhled",
	character_list = "seznam postav",
	face_features = "rysy obličeje",
	parents = "rodiče",
	parent = "rodič",
	mix = "mix",
	skin = "kůže",
	desc_mix = "Vyber jestli je tvůj obličej více podobný na otce/matku.",
	desc_skin = "Vyber jestli je barva kůže více ovlivněna otcem/matkou.",
	identity = "identita",
	player_name = "jméno hráče",
	new_character = "nová postava",
	warning_headblend = "~r~Nevybral sis rodiče tvé postavy.",
	warning_overlays = "~r~Nevybral sis vlasy, obočí nebo vousy.",
	warning_identity = "~r~Varování.~n~~w~Zapomněl jsi vyplnit tabulku o identitě.",

	-- kits
	kit_does_not_exist = "~r~Tento kit neexistuje.",
	kit_needs_rank = "Nemáš ~r~%s~w~ roli.",
	wait_before_using_kit = "Prosím počkej ~r~%s~w~ před obdržením tohoto kitu.",
	received_kit = "Obdržel jsi kit ~b~%s~w~.",
	no_kit = "Nemáš žádný kit.",

	unable_to_find_booster = "Nebylo možné najít žádný booster s tímto ID.",
	wait_already_player_boost = "Prosím počkej chvíli než použiješ tento booster. Tento booster je již aktivní.",
	wait_already_crew_boost = "Prosím počkej chvíli než použiješ tento booster. Crew booster je již aktivní.",
	wait_already_server_boost = "Prosím počkej chvíli než použiješ tento booster. Server booster je již aktivní.",
	booster_activated = "Booster aktivován na ~g~%s minut~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ aktivoval server booster na ~g~%s minut~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ aktivoval crew booster na ~g~%s minut~z~! ~b~XP +%s%%",
	no_booster = "Nemáš žádný booster.",

	rank_expired = "~r~Tvoje role vypršela.",
	supporter_role = "~g~Role:~w~ %s",
	no_rank_warning = "Nemáš žádnou roli.\n~r~Pokud sis něco zakoupil, musíš si linknout svůj FiveM účet.",
	no_fivem_id = "Nemáš linknutý FiveM účet.\n~r~Zkontroluj, že máš FiveM účet linknutý s hrou.",
	no_queue_warning = "Nemáš žádný balíček v řadě.\n~r~Zkus chvíli počkat nebo napsat /getRank pokud jsi nedostal svou roli.",
	package_sync_success = "~g~Tvůj nákup byl synchronizovaný, užívej!\n~w~Užitečné příkazy: /getRank, /booster",

	level_required = "Musíš být level %s.",
	rank_required = "Musíš mít alespoň hodnost %s.",
	level_required_2 = "~r~Musíš být level %s.",

	updated_deathmessage = "~g~Aktualizoval jsi svou zprávu po smrti.",
	updated_deatheffect = "~g~Aktualizoval jsi svůj efekt při zabití.",
	use = "Použít",
	test = "Test",

	-- zombie
	you_bitten = "~r~Byl jsi nakažen.",
	infection_rate = "Míra infekce: ~r~%s%%",

	-- ranks
	thug = "Thug",
	hustler = "Hustler",
	soldier = "Soldier",
	trigger = "Trigger",
	enforcer = "Enforcer",
	facilitator = "Facilitator",
	public_enemy = "Public Enemy",
	shot_caller = "Shot Caller",
	street_boss = "Street Boss",
	kingpin = "Kingpin",
	-- Tattoo
	tattoo = "tetování",
	tattoos = "tetování",
	torso = "trup",
	head = "hlava",
	left_arm = "levá ruka",
	right_arm = "pravá ruka",
	left_leg = "levá noha",
	right_leg = "pravá noha",
	unknown = "neznámé",
	other = "ostatní",
	remove_tattoo = "Odstranit všechna tetování",
	-- Hairdress
	haircuts = "Účesy",
	makeup = "Makeup",
	face = "Obličej",
	eyebrows = "Obočí",
	facial_hair = "Vousy",
	body_hair = "Chlupy na těle",
	barber_shop = "Holičství",
	face_makeup = "Makeup",
	lipstick = "Rtěnka",
	face_foundation = "Obličejový základ",
	skin_blemishes = "Kožní vady",
	skin_ageing = "Stáří",
	moles_freckles = "Pihy",
	sun_damage = "Poškození kůže",
	skin_complexion = "Pokožka",
	body_blemishes = "Tělesné vady",
	body_blemishes_2 = "Tělesné vady 2",
	opacity = "Alpha",
	variations = "Variace",
	filter = "Filtr",
	eyes_color = "Barva očí",
	-- Mask
	masks = "Masky",
	-- Items
	money = "Peníze",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	rocket = "Rocket",
	flare = "Flare",
	grenade = "Grenade Ammo",
	-- Food
	["fish_1"] = "Largemouth Bass",
	["fish_2"] = "Rainbow Trout",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Arctic Grayling",
	["fish_5"] = "Rock Bass",
	["fish_6"] = "Smallmouth Bass",
	["fish_7"] = "Paddlefish",
	["fish_8"] = "Bull Trout",
	["fish_9"] = "Lake Trout",
	["fish_10"] = "Chinook",
	["fish_11"] = "Pallid Sturgeon",
	["fish_12"] = "Salmon",

	misc_meat = "Raw meat",
	rabbit_meat = "Raw rabbit",
	lion_meat = "Raw lion",
	rare_plume = "Rare feather",
	dog_meat = "Raw dog",
	cat_meat = "Raw cat",
	rare_fish = "Rare fish",

	mask = "Mask",
	malette = "Suitcase",
	malette_metal = "Metal suitcase",
	ciseaux = "Scissors",
	clean_kit = "Clean kit",
	fishing_rod = "Fishing rod",
	meuble = "Furniture",
	tissu = "Cloth",
	accessory = "Accessory",
	radio = "Radio",
	recyclor = "Recycler",
	medkit = "Medkit",
	kevlar = "Kevlar",
	gps = "GPS",
	repair_tool = "Repair kit",
	jvn = "JVN",
	engine_veh = "Engine",
	bag = "Sac",
	wheel_veh = "Wheel",
	vetement = "Top",
	bloc_note = "Notepad",
	paint_spray = "Paint spray",
	spike = "Spike strip",
	paracetamol = "Paracetamol",
	bandage = "Bandage",
	gaz_mask = "Gaz mask",
	filter = "Filtr",
	tattoo_tool = "Tattoo tool",
	drug_med = "Drug",
	drug_antizin = "Antizin shot",
	drug_stamina = "Stamina shot",
	drug_berserker = "Health shot",

	pickup_spikestrip = "sebrání zastavovacího pásu",
	you_dropped_spikestrip = "Položil jsi ~g~zastavovací pás~w~.",
	you_pickup_spikestrip = "Sebral jsi ~g~zastavovací pás~w~.",

	you_have_been_killed_by = "Zabil tě ~r~%s",
	kill_notif = "~m~Zabit",
	you_killed = "Zabil jsi ~r~%s~w~",
	already_used_reset_only = "~r~Už sis resetoval svou postavu.\n~w~Pouze %s~w~ členové mohou resetovat svou postavu vícekrát než jednou.",
	already_used_reset_only2 = "~r~Tohle jsi už udělal.\n~w~Pouze %s~w~ členové to mohou použít vícekrát.",

	hud_options = "Nastavení HUD",
	advanced_hud = "Zobrazit pokročilý HUD",
	players = "Hráči",
	health = "Zdraví",
	player_menu = "Menu hráče",

	you_are_now_zombie = "~r~Nyní jsi zombík.",

	my_weapons = "moje zbraně",
	customize_weapons = "modifikace zbraně",
	weapon_skin = "Odstín",

	-- camo
	skin_classic = "Defaultní",
	skin_green = "Zelená",
	skin_yellow = "Žlutá",
	skin_pink = "Růžová",
	skin_gold = "Zlatá",
	skin_blue = "Modrá",
	skin_orange = "Oranžová",

	weapon_katana = "Katana",
	weapon_sledgehammer = "Sledge Hammer",

	-- new
	airdrop_coming = "~r~Blíží se airdrop, podívej se na mapu.",
	killed_by_cheater = "~r~Byl jsi zabit cheaterem.\n~w~Zabanovali jsme ho a tvoje smrt byla vyresetována.",

	corrupted_vehicle = "~r~Toto vozidlo je poškozené a v minulosti bylo duplikované, proto bylo odstraněno z inventáře. Omlouváme se, pokud tě někdo okradl.",

	-- Discord
	join_discord_for_kit = "Připoj se na náš Discord pro získání kitu!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~Musíš si linknout svůj Discord účet s FiveM.",
	discord_account_not_guild = "~r~Nejsi na našem Discord serveru.\n~w~Připoj se discord.gg/gtalife",

	already_done_recently = "~r~Zkus to znovu později, v poslední době jsi to již provedl.",
	update_country = "Změnit zemi",

	prestige_info = "~b~Dosáhl jsi maximálního levelu.\n~w~Napiš /prestige pro získání informací o systému prestiží.",
	prestige_not_max_level = "~r~Nedosáhl jsi nejvyššího možného levelu.",
	max_prestige_reached = "~r~Dosáhl jsi poslední prestiže.",
	prestige_info_cmd = [[^3Systém prestiží^7
Právě máš prestiž ^4%s^7 a level ^5%s^7.

Pokud dosáhneš maximálního levelu (%s) můžeš si zvolit prestiž a restartovat svůj level na level 0.
Získáním nové prestiže dostaneš speciální odznak a body, kterými si můžeš například zvětšit velikost inventáře.
^2Pokud si chceš dát prestiž a VRÁTIT se na level 0, napiš ^1/setprestige^2
]],
	new_prestige = "Odemkl jsi novou prestiž!\n~g~Nyní máš %s prestiží",
	cant_store_event_veh = "~r~Nemůžeš uschovat legendární vozidla.",

	you_are_no_longer_in_combat = "🛡️ ~b~Už nejsi v combatu.",
	you_are_in_combat_mode = "🛡️ ~b~Jsi v combatu.\nPokud se odpojíš, zemřeš.",
	you_disconnected_in_combat = "💀 Odpojil ses v combatu, zemřel jsi.",

	not_enough_prestige_points = "~r~Nemáš dostatek bodů na prestiž.",
	you_reached_max_prestige_stats_rank = "~r~Získal jsi nejvyšší možnou úroveň pro tuto prestiž.",
	new_prestige_stats_upgrade = "Vylepšil jsi svůj ~b~%s~w~\n~g~%s/%s",

	legendary_vehicle_pop = "~r~Legendární vozidlo se objevilo někde na mapě.",

	-- poll one
	poll1_q1 = "Jaký server bys rád viděl?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Private missions solo nebo s 1-4 kamarády (něco jako Payday/heisty/Hitman)",
	poll1_q1_a3 = "Race / Freeroam",
	poll1_q1_a4 = "Murder / Horror game",

	-- poll two
	poll2_q1 = "Mluvíš anglicky a měl bys zájem o RP server?",

	poll2_q1_a1 = "Ne",
	poll2_q1_a2 = "Ano",

	combat_mode_container_disabled = "~r~Jsi v combatu.\n~w~Nemůžeš uschovávat věci.",
	gcoins_wallet_updated = "~g~Tvoje peněženka s GCoiny se aktualizovala.\n~w~+%s GCoinů",
	not_enough_gcoins = "~r~Nemáš dostatek GCoinů.",
	gcoins_something_went_wrong = "~r~Něco se nepovedlo.",
	you_bought_with_gcoins = "Koupil sis ~g~%s~w~ za ~b~%s GCoinů~w~.",

	equiping_armor = "Nasazování armoru",

	toggle_mute_player = "Mutnout hráče",
	you_muted_this_player = "~b~Mutnul sis tohoto hráče.",
	you_unmuted_this_player = "~b~Odmutnul sis tohoto hráče.",

	already_purchased = "~r~Tento předmět už jsi koupil.",
	weapon_camo_preview = "Právě se díváš na náhled modelu, některé komponenty chybí.\n~INPUT_CELLPHONE_CANCEL~ pro opuštění náhledu.",

	already_using_a_seringue_booster = "~r~Tohle sis už píchnul.",
	seringue_effect_done = "~b~Efekt antizin shotu skončil.",
	you_injected_a_seringue_boost = "Píchnul sis ~b~antizin shot~w~ do krve.",

	put_item_permission = "Vložit věci",
	take_item_permission = "Vzít věci",
	put_money_permission = "Vložit peníze",
	take_money_permission = "Vzít peníze",

	preferred_badge_set = "Nastavil jsi svůj ~g~preferovaný odznak~w~.",
	preferred_badge_not_set = "~r~Nemůžeš si nastavit svůj preferovaný odznak.",

	marketplace_received_money_sales = "Získal jsi ~g~$%s~w~ z ~b~%s~w~ nabídek.",
	marketplace_no_sales = "~r~Nic jsi neprodal.",
	marketplace_you_paid_for = "Zaplatil jsi ~g~$%s~w~ za ~b~%s~w~.",

	deleted_sell_offer = "~b~Smazal jsi svou nabídku.",
	deleted_buy_offer = "~b~Smazal jsi svou nabídku.",
	deleted_sell_offers = "~b~Smazal jsi svoje nabídky.",
	deleted_buy_offers = "~b~Smazal jsi svoje nabídky.",

	marketplace_offer_does_not_exist = "~r~Tato nabídka neexistuje.",

	marketplace_create_sell_offer = "Vytvořil jsi nabíkdu ~b~%sx %s ~w~za ~g~$%s~w~ za jeden předmět.",
	marketplace_create_buy_offer = "Vytvořil jsi nabídku ~b~%sx %s ~w~za ~g~$%s~w~ za jeden předmět.",

	i_want_to_enter_in_my_property = "Chci do bunkru.",
	i_want_to_exit_private_world = "Chci do veřejného světa.",
	public_world = "Veřejný svět",
	private_world = "Soukromý svět",

	dailymission_playerkill = "Zabito hráčů",
	dailymission_zombiekill = "Zabito zombíků",
	dailymission_playerheadshotkill = "Zabito hráčů headshotem",
	dailymission_zombieheadshotkill = "Zabito zombíků headshotem",
	dailymission_zombiesurvivorkill = "Zabito survivor zombíků",
	dailymission_zombiearmoredkill = "Zabito armored zombíků",
	dailymission_zombiehazmatkill = "Zabito hazmat zombíků",
	dailymission_zoombieboomerkill = "Zabito boomer zombíků",
	dailymission_sellitems = "Prodaných věcí",
	dailymission_buyitems = "Koupených věcí",
	dailymission_lootitems = "Nalootěných věcí",
	dailymission_createselloffer = "Vytvořeno nabídek",
	dailymission_killtopkillcrew = "Zabito hráčů z crew",
	dailymission_killtopkillplayers = "Zabito hráčů",
	dailymission_getintolegendaryvehicle = "Vozidel",
	dailymission_killzombiewithweapon = "Zabito zombíků se zbraní",
	dailymission_killplayerwithweapon = "Zabito hráčů se zbraní",
	dailymission_darkzonesurvivingtime = "Přežito v darkzóně",
	dailymission_redzoneplayerkill = "Killů hráčů v redzóně",
	dailymission_redzonezombiekill = "Killů zombíků v redzóně",
	dailymission_darkzoneplayerkill = "Killů hráčů v darkzóně",
	dailymission_darkzonezombiekill = "Killů zombíků v darkzóně",
	dailymission_useitem = "Použito věcí",
	dailymission_playtime = "Odehraný čas",
	dailymission_xpharvest = "Získáno XP",
	dailymission_sellofferpurchased = "Nabídek prodáno",
	dailymission_sellofferpurchasedbyme = "Nabídek nakoupeno",
	dailymission_tradeitems = "Předmětů vytradováno",
	dailymission_createbuyoffer = "Nabídek vytvořeno",

	dailymission_completed = "~g~Splnil jsi denní úkol!\n~b~+%s XP\n~y~+1 Dungeon klíč",

	character_creation_mix_desc = "Vyber jestli je tvůj obličej více podobný na otce/matku.",
	character_creation_skin_desc = "Vyber jestli je barva kůže více ovlivněna otcem/matkou.",

	ff_1 = "Šířka nosu",
	ff_2 = "Výška nosu",
	ff_3 = "Délka nosu",
	ff_4 = "Pokles nosu",
	ff_5 = "Pokles špičky nosu",
	ff_6 = "Zakroucení nosu",
	ff_7 = "Výška obočí",
	ff_8 = "Hloubka obočí",
	ff_9 = "Výška lícních kostí",
	ff_10 = "Šířka lícní kosti",
	ff_11 = "Šířka líc",
	ff_12 = "Otevření očí",
	ff_13 = "Tloušťka rtů",
	ff_14 = "Šířka čelisti",
	ff_15 = "Délka zadní čelisti",
	ff_16 = "Snížení brady",
	ff_17 = "Délka brady",
	ff_18 = "Šířka brady",
	ff_19 = "Rozštěp brady",
	ff_20 = "Tloušťka krku",

	airdrop_taken_by = "^1%s vzal %s z airdropu.",

	available_death_effects = "Dostupné efekty při zabití",
	available_modes = "Dostupné módy",

	you_changed_your_ped_model = "~g~Úspěšně jsi změnil svůj ped.",
	i_want_to_change_my_ped = "Chci si změnit peda",

	poll4_q1 = "Co očekáváš od další sezóny?",
	poll4_q1_a4 = "Nové eventy jako airdropy, zabírání zón atd.",
	poll4_q1_a1 = "Více PvE možností jako například dungeony",
	poll4_q1_a2 = "Více her jako například kasíno/závody",
	poll4_q1_a3 = "Více PvP možností",

	poll4_q2 = "Chtěl bys mít více turnajů/ranked zápasů?",
	poll4_q2_a1 = "Ano",
	poll4_q2_a2 = "Ne",

	poll4_q3 = "Chtěl bys sniperky v obchodě?",
	poll4_q3_a1 = "Ano",
	poll4_q3_a2 = "Ne",

	poll4_q4 = "Co si nejvíc užíváš na Extinction?",
	poll4_q4_a1 = "PvP",
	poll4_q4_a2 = "PvE",
	poll4_q4_a3 = "Obchodování",

	dungeon_no_more_time = "~r~Byl jsi příliš pomalý. Dungeon se uzavřel.",
	dungeon_participant_left = "~r~%s opustil dungeon.",
	started_dungeon_party = "~b~Vytvořil jsi dungeon.",
	dungeon_party_no_longer_exists = "~r~Tato dungeon parta již neexistuje.",
	dungeon_invitation_expired = "~r~Tato pozvánka vypršela.",
	dungeon_join_party = "~g~Připojil ses do dungeon party.",
	dungeon_too_late_for_invitation = "~r~Přijal jsi pozvánku příliš pozdě. Nemůžeš se připojit do probíhajícího dungeonu.",
	dungeon_already_invited_this_player = "~r~Tohoto hráče už jsi pozval.",
	dungeon_invitation_received = "Získal jsi pozvánku od ~b~%s~w~ do jeho dungeon party.\nNapiš ~g~/dungeon join %s~w~ pro připojení se.",
	dungeon_invitation_sent = "Pozval jsi ~g~%s~w~ do tvojí dungeon party.",

	i_want_to_enter_a_dungeon = "Chci navštívit dungeon",
	dungeon_list = "Seznam dungeonů",
	dungeon = "Dungeon",
	dungeons = "Dungeony",
	you_need_x_keys = "Potřebuješ ~y~%s dungeon klíčů~w~ pro vstup do dungeonu.",
	time_remaining = "Zbývající čas",
	you_killed_the_dungeon_boss = "~r~Zabil jsi dungeon bosse.",
	dungeon_kill_final_boss = "Jsi v poslední místnosti. Zabij bosse, abys získal jeho poklad.",

	dungeon_died_remaining = "Umřel jsi, máš ~r~%s~w~ zbývajících životů.",
	dungeon_died = "~r~Už nemáš žádné zbývající životy. Zemřel jsi.",
	dungeon_already_in_party = "~r~Už jsi v dungeon party.\n~w~Napiš /dungeon quit pro opuštění.",
	dungeon_does_not_exist = "~r~Tento dungeon neexistuje.",
	dungeon_ready = "~g~%s~w~ je připraven.",
	dungeon_not_ready = "~r~%s~w~ není připraven.",

	not_released_yet = "Toto ještě není vydáno.",
	feature_only_supporters = "~b~Tato funkce je teprve v betě a pouze hráči s ranky Gold/Diamond ji mohou používat.",
	feature_not_enabled = "~b~Tato funkce není ještě zapnutá.\n~w~Prosím počkej, až se tato funkce spustí.",
	dungeon_charid_required = "~r~Prosím zadej character ID tvého kamaráda (nachází se na obrazovce vpravo nahoře).\nPříklad: /dungeon invite 1234",

	poll5_q1 = "Měl bys problém pokud by náš anticheat vyscreenoval obrazovku cheatera, pokud by byl podezřelý, že používá wallhack/aimbot? (je možné, že to ukáže část plochy, pokud máš hru v okně, ale tyto screeny nejsou uloženy a jsou přístupné pouze pro moderátory)",
	poll5_q1_a1 = "přeskočit - ignorovat",
	poll5_q1_a2 = "Ano, souhlasím s touto novou metodou",
	poll5_q1_a3 = "Ne, nesouhlasím",
	
	-- S4
	redzone_kill_leader_killed = "~r~Kill leader v redzóně~w~ byl zabit.",
	redzone_kill_leader_fled = "~r~Kill leader v redzóně~w~ utekl.",
	redzone_get_back_kill_leader_before_x = "Jsi ~r~mimo redzónu~w~ vrať se zpátky nebo ztratíš status kill leadera za ~r~%s sekund~w~.",
	redzone_kill_leader_new_xp_step = "~r~Násobitel XP v redzóně\n~b~+%s%~w~ bonus",
	remaining_lives = "Zbývající životy",

	name_tag = "Crew tag",
	redzone_changed = "~r~Redzóny se přemístily na nové lokace.",

	-- Squad
	squad_not_leader = "~r~Nejsi leader tvojí squady.",
	squad_kicked_by_x = "¨Byl jsi ~r~vyhozen~w~ z tvojí squady hráčem ~r~%s~w~.",
	squad_you_kicked_x = "Vyhodil jsi ~r~%s~w~ z tvojí squady.",
	squad_invited_x = "Pozval jsi ~r~%s~w~ do tvojí squady.",
	squad_invited_you_x = "~r~%s~w~ tě pozval do jeho squady.\nNapiš ~r~/squad join %s~w~ pro přijmutí pozvánky.",
	squad_you_set_new_leader = "Určil jsi ~r~%s~w~ jako nového ~r~leadera~w~ squady.",
	squad_you_are_new_leader = "~g~Nyní jsi nový leader squady.",
	squad_not_invited = "~r~Nebyl jsi pozván do žádné squady.",
	squad_joined_squad = "~g~Připojil ses do squadu.",
	squad_left = "~r~Opustil jsi squad.",
	squad_already_in = "~r~Už jsi v nějaké squadě.",
	squad_created_x = "Vytvořil jsi nový squad. ~b~(%s)",
	squad_x_joined = "~b~%s~w~ se připojil do squadu.",
	squad_leader_deleted = "~r~Leader smazal tento squad.",
	write_yes_to_confirm = "Napiš yes pro potvrzení",
	invite_a_player_write_char_id = "Pozvi hráče. Napiš jeho character ID",

	-- Help stuff
	press_enter_beginner_guide = "Zmáčkni ~INPUT_ENTER~ pro zapnutí návodu pro nováčky.",
	welcome_glife = "Vítej na ~g~GLife~w~!",
	you_are_playing_server_x_with_x = "Hraješ na serveru ~b~#%s~w~ s ~b~%s hráči~w~.",
	start_beginner_guide = "Začít návod pro nováčky",
	play_now = "~g~Hraj nyní!",
	interact_npc_fast_travel = "Promluv si s teleportérem",

	-- Tutorial
	tutorial_beginner_end_msg = "~r~Díky za tvůj čas!\n~w~Užívej Extinction, pokud máš nějaké otázky zeptej se v chatu nebo navštiv náš Discord.",
	tutorial_beginner_start_msg = "~r~Vítej na serveru GLife Extinction!\n~w~Tímto krátkým návodem zjistíš jak zde začít.",
	tutorial_beginner_camera_01 = "~r~~BLIP_557~ ~r~Hlavní safezóna\n~w~V této zóně můžeš nakupovat a uschovávat svoje věci, ale také si zde můžeš modifikovat svoji výbavu a obchodovat s ostatními hráči.",
	tutorial_beginner_camera_02 = "~BLIP_568~ ~r~Sklad\n~w~Tady můžeš navštívit svůj sklad a uschovat si zde tvoje cenné věci.",
	tutorial_beginner_camera_03 = "~BLIP_567~~BLIP_556~~BLIP_658~ ~r~NPC obchodníci\n~w~Můžeš nakupovat a prodávat svoje věci u obchodníku se zbraněmi, autami nebo u obchodníka s ostatní výbavou.",
	tutorial_beginner_camera_04 = "~BLIP_84~ ~r~Veřejné odměny\n~w~Pokud se ti podaří najít a zabít cílového hráče, dostaneš určitou odměnu.",
	tutorial_beginner_camera_05 = "~BLIP_176~ ~r~Nepřátelský svět\n~w~Potkáš zombíky a ostatní hráče. Všichni tě budou chtít zabít, ale na druhou stranu jsou nejlepším způsobem, jak získat XP a loot.",
	tutorial_beginner_camera_06 = "~BLIP_303~ ~r~Redzóny\n~w~Tady můžeš mít lepší loot a budeš získávat více zkušeností za killy.",
	tutorial_beginner_camera_07 = "~BLIP_648~ ~r~Darkzóna\n~w~Zde nemůžeš uschovávat věci nebo utéct tak jednoduše, ale je to nejlepší místo, kde najít nejlepší loot jako jsou MK2 zbraně nebo sniperky.",
	tutorial_beginner_camera_08 = "~BLIP_575~ ~r~Ostatní příležitosti\n~w~Můžeš bojovat o airdrop ale také můžeš prozkoumat dungeon a na konci zabít bosse.",
	tutorial_beginner_training_01 = "~g~Připojil ses do tréninkové místnosti.\n~w~Skoč pomocí ~INPUT_JUMP~ až budeš připraven.",
	tutorial_beginner_training_02 = "~g~Použij inventář.\n~w~Zmáčkni ~%s~ pro otevření inventáře.",
	tutorial_beginner_training_03 = "~g~Vem si zbraň.\n~w~Otevři inventář a přesuň zbraň do lišty dole.\nZmáčkni určitou klávesu ~b~1/2/3/4/5/6/7~w~.\n~r~Pokud nemáš žádnou zbraň, použij ~b~/kit newbie.",
	tutorial_beginner_training_04 = "~g~Nabij svoji zbraň.\n~w~Vem si zbraň a vlož náboje do lišty dole, pak zmáčkni určitou klávesu.",
	tutorial_beginner_training_05 = "~g~Konečně vozidla.\n~w~Teď můžeš spawnovat auta stejně jako používáš náboje nebo zbraně. Jakmile spawneš auto, můžeš ho schovat ~%s~ zatímco stojíš na místě. Zmáčkni klávesu pro potvrzení.",
	tutorial_beginner_training_success_01 = "~g~Dobrá práce, nyní můžeme začít!",
	tutorial_beginner_training_success_02 = "~g~Dobře, zvládl jsi to.\n~w~Proces je stejný pro všechny předměty.",
	tutorial_beginner_training_success_03 = "~g~Dobře, zvládl jsi to.\n~w~Proces je stejný pro všechny předměty.",
	tutorial_beginner_training_success_04 = "~g~Dobře, zvládl jsi to.\n~w~Nyní jsme hotoví.",

	-- Darkzone stuff
	contaminated = "kontaminováno",
	darkzone_boat_leaving_in = "Lodě zmizí za",
	darkzone_exit = "Místo pro opuštění",
	purificator = "Purifikátor",
	you_entered_the_darkzone = "~r~Vstoupil jsi do darkzóny.\n~w~Momentálně je uvnitř ~b~%s hráčů~w~.",
	you_left_the_darkzone = "~r~Opustil jsi darkzónu.",
	cannot_enter_darkzone_time = "~r~Darkzóna ještě není otevřená, čekej.",
	darkzone_is_full = "~r~Darkzóna je plná, prosím čekej.",
	darkzone_exit_allowed = "~r~Lodě jsou zde pro opuštění darkzóny, utíkej pokud chceš opustit darkzónu.",
	darkzone_close_time = "Zavírá se za",
	darkzone_surviving_since = "Přežíváš",
	darkzone_points = "Bodů",
	darkzone_points_x = "~r~Darkzone bodů: ~w~+%s",
	darkzone_landing_in_x = "Darkzóna se otevře za ~b~%s minut~w~.\nPokud bude dostatek hráčů.",
	darkzone_open_press_context = "Zmáčkni ~INPUT_CONTEXT~ pro vstoupení ~m~do darkzóny~w~.",
	darkzone_outside_warning = "~r~Jsi mimo darkzónu, vrať se nebo umřeš.",
	darkzone_close_warning = "~r~Darkzóna se brzy uzavře~w~.\nNeměl bys zde zůstávat příliš dlouho.",
	darkzone_close_damage = "Darkzóna se uzavřela, celá oblast je nyní kontaminovaná.",
	darkzone_not_enough_points_to_exit = "Potřebuješ ~r~%sx bodů~w~ pro opuštění darkzóny.",
	press_e_to_exit_the_darkzone = "Zmáčkni ~INPUT_CONTEXT~ pro opuštění darkzóny.\n~r~Potřebuješ x%s darkzone bodů.",
	use_purificator = "použití purifikátoru",
	darkzone_not_enough_points_to_start_purificator = "Potřebuješ ~r~%sx bodů~w~ pro zapnutí purifikátoru.",
	darkzone_not_enough_points_to_refill_purificator = "Potřebuješ ~r~%sx bodů~w~ pro doplnění purifikátoru.",
	darkzone_too_far_from_purificator = "~r~Jsi přilíš daleko od purifikátoru.",
	darkzone_cant_remove_while_running_purificator = "~r~Nemůžeš vybírat věci pokud je purifikátor zapnutý.",
	darkzone_purificator_running = "~r~Nemůžeš vkládat věci dovnitř pokud je purifikátor zapnutý.",
	darkzone_purificator_running_refill = "~r~Nemůžeš doplnit purifikátor pokud je právě zapnutý.",
	darkzone_put_x_in_purificator = "Vložil jsi ~r~%s~w~ do purifikátoru.",
	darkzone_you_took_x_from_purificator = "Vzal jsi ~r~%s~w~ z purifikátoru.",
	darkzone_purificator_does_not_need_refill = "Nepotřebuješ ~r~doplňovat tento purifikátor~w~.",
	darkzone_refilled_purificator_x = "Použil jsi ~r~x%s bodů~w~ pro doplnění purifikátoru.",
	darkzone_open = "Darkzóna se otevřela.\n~r~Najdi transportér v jakékoliv safezóně.",
	darkzone_item_clean = "Tato položka už je předělaná.\n~r~Můžeš vkládat pouze kontaminované věci.",
	
	dungeon_cooldown_between = "Prosím počkej ~r~%s minut~w~ před startem dalšího dungeonu.",
	set_as_default = "Nastavit jako defaultní modifikaci pro tento model vozidla",
	car_custom_presets_saved = "Preset modifikací pro ~g~%s~w~ byl uložen.",
	marketplace_you_received_x_x = "Obdržel jsi ~b~%sx ~g~%s~w~.",

	above_level_x_no_longer_possible_loot_safe = "Hráči nad level %s nemůžou lootovat zombíky v safezónách.",
	preferred_component_desc = "Tento set bude defaultní set pro všechny %s zbraně, které budeš držet.",
	set_as_preferred_component_class = "Nastavit jako preferovaný set komponentů",
	weapon_presets_updated = "Nastavil sis defaultní preset komponentů pro ~g~%s~w~.",

	-- New survey
	poll6_q1 = "Chtěl bys snížit limit členů v crew na 25? (více konkurence, menší skupinky)",
	poll6_q2 = "Máš v pohodě ping na tvém main serveru? (je tvůj průměrný ping v pohodě?)",
	poll6_q3 = "Hraješ v private worldu?",
	poll6_q4 = "Měl by být zaplý headshot damage pro sezónu 4?",
	
	casino_dungeon_desc = "⚠️ ~r~Budeš potřebovat baterku na zbraň, abys tam dobře viděl.",
	dungeon_destroy_wall_obj = "Znič zeď, která ti blokuje cestu.",
	dungeon_use_key_obj = "Použij klíč k otevření dveří.",
	dungeon_kill_zombies_obj = "Zabij všechny zombíky.",
	dungeon_kill_zombies_obj_x = "~b~Zabij všechny zombíky.~w~\n%s/%s hráčů zabilo všechny zombíky.",
	dungeon_use_key_to_open_door = "Použij klíč pro otevření dveří.",
	dungeon_find_key_obj = "Najdi klíč, kterým otevřeš dveře.",
	take_key = "získání klíče",
	open_the_door = "otevření dveří",
	dungeon_quit_notif = "Napiš ~g~/dungeon quit~w~ pro opuštění dungeonu.",
	dungeon_generator_obj = "Najdi generátor a obnov elektřinu.",
	dungeon_press_generator = "Zmáčkni ~INPUT_CONTEXT~ pro zapnutí generátoru.",
	power_generator = "Generátor elektrické energie",
	dungeon_find_c4_obj = "Někde tu je schovaná C4, najdi ji.",
	dungeon_use_c4_obj = "Použij C4 k odpálení trezoru.",
	dungeon_party_help = "Napiš ~b~\"/dungeon\"~w~ pro správu tohoto dungeonu.",
	press_x_to = "Zmáčkni %s pro %s",

	quest_clean_zone = "Zabij zombíky v zóně: %s",
	quest_clean_zone_desc = "Přijeď do zóny %s a zabíjej zde zombíky.",

	loot_crate_light = "Light Loot Crate",
	loot_crate_medium = "Medium Loot Crate",
	loot_crate_high = "High Loot Crate",
	
	dailymission_killzombieinzoneid = "Zombíků zabito v zóně",
	dailymission_dungeonbosskilled = "Dungeon boss zabit",

	quest_too_far_npc = "~r~Jsi příliš daleko od NPC s úkoly.",
	quest_already_started_quest = "~r~Tento úkol už plníš.",
	quest_redo_in_x = "~r~Tento úkol už jsi splnil.\n~w~Budeš se moct pokusit ho splnit znovu po uplynutí ~b~%s",
	quest_max_quests_reached = "~r~Můžeš přijmout pouze %s úkoly.",
	quest_new_accepted = "~g~Přijmul jsi nový úkol.",
	quest_gave_up = "~r~Vzdal ses tohoto úkolu.",
	quest_not_completed = "~r~Musíš splnit všechny části tohoto úkolu.",
	quest_already_completed = "~r~Tento úkol už jsi splnil.",
	quest_all_completed = "~g~Úspěšně jsi splnil všechny části.",
	dungeon_key = "Dungeon klíč",
	darkzone_cannot_enter_min_levels = "Musíš být level ~b~%s~w~ abys mohl vstoupit do darkzóny.",
	darkzone_you_survived_x = "Přežil jsi ~r~%s minut~w~ v darkzóně.",
	questmenu_command = "Otevřít menu s úkoly",
	squadmenu_command = "Otevřít squad menu",
	airdrop_coming_darkzone = "~r~V darkzóně budou airdropy, podívej se na mapu.",
	darkzone_full_crew = "V darkzóně je ~r~%s members~w~ z tvojí crew, počkej až někdo opustí darkzónu.",

	crew_join_cooldown_x = "Musíš počkat ~r~%s~w~ než se budeš moct připojit do této crew.",
	darkzone_not_enough_players_darkzone = "Darkzóna se neotevře.\n~r~Není dostatek hráčů.",

	dungeon_loot_boss_box = "~g~Bedna se objevila uprostřed místnosti.",
	drug_antizin_bar = "Efekt Antizin shotu",
	drug_stamina_bar = "Efekt Stamina shotu",
	drug_berserker_bar = "Efekt Health shotu",

	squad_members_limit = "~r~Tvoje squad překročila limit členů.",
	darkzone_only = "~r~Musíš být v darkzóně.",
	darkzone_no_cars = "~r~V darkzóně můžeš používat pouze motorky, lodě a ostatní vozidla, které mohou létat.",

	poll7_q1 = "Měl bys zájem o evropský server pouze pro hraní solo?",
	poll7_q2 = "Chtěl bys opět dropovat AWP MK2/Marksman Rifle MK2 i z dropů?",

	you_have_been_muted = "~r~Byl jsi umlčen.~w~\nVypršení: ~b~%s~w~\nDůvod: ~b~%s",
	you_have_been_unmuted = "~g~Byl jsi odmlčen.",
	muted_x = "Umlčel jsi ~g~%s~w~.~w~\nVypršení: ~b~%s~w~\nDůvod: ~b~%s",
	unmuted_x = "Odmlčel jsi ~g~%s~w~.",
	invalid_duration = "~r~Nesprávná délka, prosím zadej správný čas.",
	player_already_muted = "~r~Tento hráč už je umlčený.",
	player_not_muted = "~r~Tento hráč není umlčený.",
	you_are_muted = "~r~Jsi umlčený.",

	open_mailbox = "otevření schránky",
	you_entered_crew_pro = "~g~Vstoupil jsi do crew bunkru.",

	you_player_not_enough_gcoin = "~r~Nemáš dostatek GCoinů.",
	other_player_not_enough_gcoin = "~r~Hráč se kterým obchoduješ nemá dostatek GCoinů.",
	a_player_no_fivem_account_linked = "~r~Hráč se kterým obchoduješ nemá linknutý svůj FiveM účet.",
	you_no_fivem_account_linked = "~r~Abys mohl tradovat GCoiny, musíš linknout svůj FiveM účet.",
	trade_gcoin_for_gcoin_not_allowed = "~r~Nemůžeš tradovat GCoiny za GCoiny.",
	cannot_delete_this_item = "~r~Nemůžeš vymazat tuto položku.",
	impossible_on_solo_server = "~r~Tohle nemůžeš dělat na solo serveru.",

	warning_message = "Hraješ na SOLO serveru Extinction. Není zde povoleno teamovat s ostatními hráči, vytvářet squady/spojenectví. Pokud budeš přichycen při teamování, budeš zabanován z tohoto serveru a dočasně i z celého GLifu. Prosím respektuj pravidla a hraj solo.",
	bank_no_money = "~r~Nemáš žádné peníze.",
	bank_deposit_x = "Vložil jsi ~g~$%s~w~ do banky.",
	cannot_deposit_money_go_bank = "~r~Promiň, zde nemůžeš vložit peníze do banky.\n~w~Běž za opicí u banky.",
	bank_balance_x = "Zůstatek v bance: ~g~$%s",
	store_money_bank = "~g~vložení peněz do banky",
	wait_before_next_action = "Počkej ~r~%sms~w~ než budeš manipulovat s touto položkou.",
	bank = "Banka",

	poll8_q1 = "Chtěl bys nahradit server 2 (solo server) serverem pouze pro dua?",
	poll8_q2 = "Máš rád banán?",

	reset_radar_tips = "Pokud chceš resetovat i radar, je pro to jiné nastavení.",
	redzone_shop = "Redzone obchod",
	no_enough_redzone_points = "~r~Nemáš dostatek redzone bodů.",
	you_paid_basket_rp = "Zaplatil jsi ~r~%s RP~w~ za tvůj košík.",

	redzone_points_balance_x = "Redzone body: ~r~%s",
	top_kills = "Nejvíce killů",
	top_zombies = "Nejvíce zombíků",

	not_allowed_in_this_zone = "~r~Tohle nemůžeš dělat v této zóně.",
	darkzone_disabled_for_update = "~r~Darkzóny jsou momentálně vypnuté, budou zpátky s dalšími updaty.",
	loot_crate_halloween = "Halloween Loot Crate",

	new_weapon = "Nová zbraň",
	winner_title = "Vítěž",
	left_gungame_party = "~r~Opustil jsi lobby Gun Game.",
	outfit_gta = "GTA Outfity",

	poll10_q1 = "Kde si myslíš, že by měl být zaplý siphon mód?",
	poll_10_q1 = "Pouze v redzóně",
	poll_10_q2 = "Všude",

	open_lobby_menu = "otevřít lobby menu",
	choose_game_lobby = "Vyber lobby",

	joined_lobby_x = "~g~Připojil ses do lobby %s.~w~\nHerní režim: ~b~%s",
	gun_game = "Gun Game",
	spawn = "Spawn",
	return_lobby_help = "Pokud se chceš vrátit do hlavní lobby, napiš ~b~/lobby.",
	afk_press_key = "AFK?~r~~n~Zmáčkni klávesu.",
	sorry_it_is_ok = "~r~Promiň!\n~w~Teď je to v pohodě.",
	swimming_respawn_help = "~r~Vypadá to, že jsi ve vodě.\n~w~Zmáčkni ~INPUT_CONTEXT~ pro respawn.",

	only_darkzone_item = "~r~Tento předmět můžeš použít pouze v darkzóně.",
	cant_get_darkzone_loadout = "~r~Nemůžeš dostat tvoji výbavu do darkzóny.\n~w~%s",
	press_e_to_exit_the_darkzone2 = "Zmáčkni ~INPUT_CONTEXT~ pro opuštění darkzóny.",
	not_driving_vehicle = "~r~Neřídíš vozidlo.",
	not_enough_airdrop_points = "~r~Tvoje crew/squad nemá dostatek bodů na to, aby mohla otevřít airdrop.",
	airdrop_points = "Airdrop body",

	warning_message_duo = "Hraješ na DUO serveru Extinction. Není zde povoleno teamovat s více jak jedním hráčem. Pokud budeš přichycen při teamování, budeš zabanován z tohoto serveru a dočasně i z celého GLifu. Prosím respektuj pravidla a hraj solo. Pokud budeš přichycen při teamování s více jak jedním hráčem, budeš zabanován z tohoto serveru a dočasně i z celého GLifu. Prosím respektuj pravidla a hraj solo.",
	combat_mode_cannot_do_that = "~r~Jsi v combatu.\n~w~Tohle nemůžeš dělat.",
	open_darkzone_shop = "otevření darkzone obchodu",
	dzone_flare_airdrop = "Světlice airdropu",
	paid_x_points_for_x = "Zaplatil jsi ~r~%s~w~ bodů za ~r~%s~w~.",
	starter_pack_upgrade_1 = "Upgrade starter packu",
	extraction_package = "Výsadkový balíček",
	always_spawn_antizin = "Spawn s antizinem",
	cannot_enter_darkzone_inventory = "~r~Nemůžeš vstoupit do darkzóny pokud máš něco v inventáři.",
	you_are_not_in_a_squad = "~r~Nejsi v žádné squadě.",
	already_in_a_crew = "Už jsi v nějaké crew.",
	
	poll11_q1 = "Měli bychom opravit rychlé přebíjení homingu/rpg (glitch)?",
	poll11_q2 = "Měli bychom banovat/opravit deluxo trick (stání na deluxu a střílení z něj)?",
	loot_crate_christmas = "Christmas Loot Crate",

	christmas_quest_x_completed = "~r~Vánoční úkol za den #%s splněn.",
	open_the_gift_menu = "otevření menu s dárky",
	too_high_level_gift = "~r~Pouze nováčci mohou brát dárky, tvůj level je příliš vysoký.",
	already_withdraw_gift_recently = "~r~Za posledních 15 minut už sis dárek vzal.",
	thank_you_for_gifting_x = "Díky za darování ~g~%sx %s~w~.",
	cannot_donate_junk = "~r~Nemůžeš darovat levné/junk věci.",
}

AddLanguage("cs", my_language)