local my_language = {
	give_vehicle = "Pridal sis ~b~%s~w~ do inventare.",
	store_vehicle_command = "Ulozis vozidlo, které ridis",
	no_entity_vehicle = "~r~Toto vozidlo neexistuje nebo je prilis daleko od tebe.",
	no_entity_vehicle_id = "~r~Toto vozidlo nemá žádné ID, nemuzes ho schovat.",
	store_vehicle = "~b~Schoval sis vozidlo.",
	teleported_former_position = "~g~Byl jsi teleportován na tvou poslední uloženou pozici.",
	not_enough_of = "~r~Nemáš dostatek %s.",
	max_storage_chest = "~r~Máš plný sklad.",
	cant_carry_more_items = "~r~Do tvého inventare se nic nevleze (je plný).",
	put_item = "Vložil jsi ~g~x%s~w~ %s~w~.",
	take_item = "Vzal jsi ~g~x%s~w~ %s~w~.",
	delete_item = "Odstranil jsi ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Vytahuješ ~g~%s~w~.",
	bind_weapon_command = "Zkratka na slot pro zbrane %s",
	kevlar_broke = "~r~POZOR!~n~~w~Tvuj armor se rozbil.",
	inventory_command = "Otevrit inventar",
	press_enter_to_join = "Zmackni ~g~ENTER~w~ pro start hry.",
	new_character = "Nová postava",
	survivor = "Prezivsi",
	right = "Vpravo",
	left = "Vlevo",
	male = "Muž",
	female = "Žena",
	ped = "Ped",
	name = "Jméno",
	sex = "Pohlaví",
	title = "Nadpis",
	select_this_character = "Vybrat tuto postavu",
	no_entity_zombie = "Zombík neexistuje nebo je prilis daleko od tebe.",
	you_found = "Našel jsi ~g~%sx %s~w~.",
	you_found_nothing = "Nenašel jsi ~g~nic~w~.",
	press_e_to_loot = "Zmackni ~b~[E]~w~ k lootování",
	full_for_item = "~r~Pro tuto vec nemáš dostatek místa.",
	put_item_container = "Vložil jsi ~g~x%s~w~ %s~w~ do skladu.",
	take_item_container = "Vzal jsi ~g~x%s~w~ %s~w~ ze skladu.",
	not_allowed_here = "~r~Zde to nemuzes udelat.",
	cant_store_moving_veh = "~r~Nemuzes ukládat vozidlo, pokud je v pohybu.",
	use_repair_tool = "Opravarska sada",
	please_get_closer = "~b~Prosím bez blíž, v blízkosti nikdo/nic není.",
	you_cancel_action = "~r~Prerusil jsi akci.",
	selected_target_message = "Vybraný cíl:~n~%s~n~~r~Zmackni ~b~Y~r~ pro ukonceni~n~~r~Zmackni ~g~X~r~ pro pokracovani.",
	target_you = "~b~TY",
	target_screen = "~g~Zobrazeno",
	take_this_path = "jít touto cestou",

	-- hud
	default_hud = "Defaultní HUD",
	cinema_hud = "Cinema HUD",
	no_hud = "Žádný HUD",

	-- perms
	kick_member = "Vyhazovat cleny",
	edit_member = "Upravovat cleny",
	edit_rank = "Upravovat hodnosti",
	create_rank = "Vytvaret hodnosti",
	delete_rank = "Mazat hodnosti",
	edit_structure = "Upravit informace o crew",
	edit_permissions = "Upravit pravomoce",
	permission_level = "Pravomoce udeleny",
	red_delete = "Smazat",
	rank = "Hodnost",
	red_kick = "Vyhodit",
	crew_name = "Jméno crew",
	slogan = "Slogan",
	information = "informace",
	boss_rank = "Název hodnosti šéfa",
	member_rank = "Název hodnosti novacka",
	member = "Clen",

	permissions_manager = "správce pravomocí",
	members_manager = "správce clenu",
	ranks_manager = "správce hodností",
	ranks_list = "seznam hodností",
	members_list = "seznam clenu",
	create_a_rank = "vytvorit hodnost",
	invite_someone = "pozvat nekoho",
	stats = "Statistiky",
	total_ranks = "Pocet hodností",
	total_members = "Pocet clenu",
	level = "Level",
	actions = "akce",
	crew_manager = "správce crew",
	you_created_a_new_crew = "Vytvoril jsi novou crew: %s",
	you_deleted_your_crew = "Smazal jsi svou crew.",
	you_are_not_in_a_crew = "Nejsi v žádné crew",
	you_joined_the_crew = "Pripojil ses do crew '%s'",
	kick_failed = "Neuspesne jsi vyhodil hrace, duvod: %s",
	already_in_crew = "Už jsi v nejake crew.",
	no_invitation = "Neobdržel jsi žádnou pozvánku.",
	left_crew = "Opustil jsi crew.",
	permission_updated = "Pravomoce <C>~g~%s</C>~w~ byly aktualizovány.",
	incorrect_name = "~r~Formát jména je nesprávný",
	incorrect_rank_perm = "~r~Chyba\n~w~Název hodnosti nebo uroven hodnosti je neplatná.",
	warn_rank_limit = "~r~Prekrocil jsi limit hodností.",
	create_rank_success = "~g~Uspesne\n~w~jsi vytvoril novou hodnost <C>~b~%s</C>~w~ s pravomocemi <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Nemuzes spravovat hrace, který má vyšší pravomoce než ty.",
	you_sent_an_invitation = "Odeslal jsi pozvánku hraci <C>~g~%s</C>~w~ do tvojí crew.",
	you_received_an_invitation = "Obdržel jsi pozvánku do crew.\n~b~/%s pro prijmuti.",
	invitation_expired = "Pozvánka vypršela",
	crew_kick_success = "Vyhodil jsi <C>~b~%s</C>~w~ z tvojí crew.",
	first_rank_warning = "První hodnost je 'defaultní' hodnost.",

	you_updated_this = "Aktualizoval jsi %s na ~g~<C>%s</C>~w~.",
	changes_saved_on = "Zmeny provedeny na <C>~g~%s</C>~w~ byly uloženy.",
	yes = "ano",
	no = "ne",
	none = "Žádný",
	character_id = "Character ID",
	server_id = "Server ID",
	report = "Nahlásit",
	rename = "Prejmenovat",
	trade_with = "Obchodovat",
	
	please_wait_x_before = "~r~Prosím pockej %s sekund predtim, než to udelas.",

	-- cloth
	take_outfit = "Koupit tento outfit",
	wardrobe_options = "možnosti šatníku",
	wardrobe = "šatník",
	manual_options = "manuální nastavení",
	manual_mode = "manuální vyber oblecení",
	save_outfit = "Uložit tento outfit",
	variation = "variace",
	outfits = "outfity",
	cloth_shop = "Obchod s oblecenim",
	ped_cloth_shop = "Obleceni na peda",
	manual_props = "manuální doplnky",
	manuel = "manuální",
	new_name = "Nové jméno",
	outfit_name = "Jméno outfitu",
	variations_saved = "~g~Uspesne~n~~w~sis vybral nové obleceni.",
	equipped_new_outfit = "Vybral sis nový outfit: ~b~%s",
	warning_limit_outfits = "Prekrocil jsi limit uložených outfitu. ~g~(%s)",
	saved_new_outfit = "Uložil sis nový outfit: ~b~%s~w~.",
	rename_outfit = "Tvuj outfit ~b~%s~w~ byl prejmenovan na ~g~%s~w~.",
	delete_outfit = "Tvuj outfit: ~b~%s~w~ byl odstranen.",

	torso = "Trup",
	props = "Doplnky",
	top = "Vršek",
	tops = "Vršek",
	badge = "Nášivky",
	pants = "Kalhoty",
	pant = "Kalhoty",
	shoes = "Boty",
	bags = "Batohy",
	undershirt = "tricko",
	neck = "Retezy",
	bracelets = "náramky",
	montres = "hodinky",
	earrings = "nausnice",
	glasses = "brýle",
	hats = "cepice",
	graphiques = "design",

	-- health
	inconscious = "V bezvedomi",
	doing_something = "Neco delas",
	time_before_respawn = "Cas pred respawnem",
	you_died = "~r~Umrel jsi.",
	healing_wounds = "Obvazuješ se",
	already_doing_something = "~r~Již neco delas.",
	you_have_been_healed = "~g~Obvázal sis ránu.",
	you_respawned = "~g~Respawnul ses.",

	player_too_far_to_interact = "~r~Hrac se kterým chceš provadet interakci je prilis daleko.",
	send_trade_invitation_to = "Poslal jsi nabídku k obchodu hraci ~b~%s~w~.\n~b~Pockej až hrac, kterému jsi nabídku poslal, nabídku prijme.",
	receive_invitation_from = "Dostal jsi nabídku k obchodu od ~b~%s~w~.\n~b~Napiš ~w~/trade accept %s~b~ pro prijmuti nabídky.",

	invalid_command_args = "Neplatné argumenty prikazu: %s",
	start_trade_command_help = "Obchodovat s dalším hracem",
	accept_trade_command_help = "Prijmout nabídku",
	deny_trade_command_help = "Odmítnout nabídku",
	invalid_invitation = "Tato nabídka je neplatná nebo již neexistuje",
	name_accepted_your_trade_invitation = "~b~%s~w~ prijal tvou nabídku",
	you_accepted_trade_invitation_of_name = "Prijal jsi nabídku od %s",
	name_denied_your_trade_invitation = "~b~%s~w~ odmítl tvou nabídku",
	you_denied_trade_invitation_of_name = "Odmítl jsi obchod od %s",
	you_already_trading = "Již obchoduješ",
	other_already_trading = "Hrac se kterým chceš obchodovat již s nekym obchoduje",

	other_player_not_enough_money = "~r~Obchod nebyl uspesny. Hrac se kterým obchoduješ nemá dostatek penez.",
	you_player_not_enough_money = "~r~Obchod nebyl uspesny. Nemáš dostatek penez.",
	other_player_not_enough_item = "~r~Obchod nebyl uspesny. Hrac se kterým jsi obchodoval nemel dostatek nejakeho predmetu.",
	you_player_not_enough_item = "~r~Obchod nebyl uspesny. Nemel jsi dostatek nejakeho predmetu.",
	success_trade = "~g~Obchod byl uspesny.",
	fail_trade_other_player = "~r~Obchod nebyl uspesny, hrac se kterým obchoduješ odešel.",
	trade_other_full_item = "~r~Obchod nebyl uspesny, hrac se kterým obchoduješ nemá dostatek místa.",
	trade_full_for_item = "~r~Obchod nebyl uspesny, nemáš dostatek místa.",

	press_e_to_loot_inv = "Zmackni ~INPUT_CONTEXT~ pro otevreni lootu.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Zmackni ~INPUT_CONTEXT~ pro interakci s ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "Zmackni ~INPUT_CONTEXT~ pro ~b~%s~w~.",
	press_e_to_open_catalog = "Zmackni ~b~E~w~ pro precteni ~g~katalogu~w~.",
	this_person = "touto osobou",
	the_shop = "tohoto obchodu",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Tohle nemuzes udelat.",

	no_weapon = "~r~Nemáš vytaženou žádnou zbran.",
	no_need_ammo = "~r~Do této zbrane nepotrebujes nabíjet žádné náboje.",
	not_right_ammo = "~r~Používáš špatné náboje, potrebujes ~b~%s~w~.",
	you_used_ammo = "Nabil jsi ~b~%s~w~ s ~b~x%s~w~ typu ~b~%s~w~.",

	choose_a_destination = "vyber ~b~destinace",
	open_your_chest = "otevreni tvého skladu",
	no_enough_money = "~r~Na to nemáš peníze.",
	you_paid = "Zaplatil jsi ~g~$%s~w~ za ~b~%s~w~.",
	you_paid_basket = "Zaplatil jsi ~g~$%s~w~ za tvuj košík.",
	you_sell_basket = "Obdržel jsi ~g~$%s~w~ za prodej ~b~x%s~w~ položek.",

	you_repaired_your_vehicle = "~g~Opravil jsi své vozidlo.",
	repairing_your_vehicle = "Opravuješ vozidlo",
	wheels_are_fine = "~r~Kola vozidla jsou v pohode.",
	changing_wheel = "Vymena kol",
	you_repaired_the_wheels = "~g~Opravil jsi kola tvého vozidla.",

	front_post_ls = "Front Post Los Santos",
	front_post_ls_2 = "Front Post Los Santos 2",
	front_post_bc = "Front Post Blaine County",
	front_post_bc_2 = "Front Post Blaine County 2",
	main_post_ls = "Safe City Los Santos",
	main_post_bc = "Safe City Blaine County",
	random_zone = "Random zona (seskok padákem)",

	this_item_is_equipped = "~r~Tuto vec máš vytaženou, dej ji pryc z dolní lišty.",
	only_in_safezone = "~r~Tohle nemuzes udelat mimo safezonu.",
	-- Commerce
	feature_gold_only = "Tato funkce je pouze pro ~y~hrace s Gold rolí~w~.",
	feature_diamond_only = "Tato funkce je pouze pro ~b~hrace s Diamond rolí~w~.",
	you_turned_into = "Promenil ses v ~g~%s~w~.",
	wait_between_transformation = "~r~Prosím pockej chvíli predtim, než se budeš chtít v neco promenit znovu.",
	wait_between = "~r~Prosím pockej chvíli predtim, než to zkusíš znovu.",
	available_morphs = "Dostupné promeny",
	animal_models = "Modely zvirat",
	zombie_models = "Modely zombiku",
	success_update_name = "Zmenil jsi svoje jméno na ~b~%s~w~.",
	success_reset_stats = "~g~Uspesne sis vyresetoval svoje staty. (Tabulka se aktualizuje pozdeji)",

	-- animals
	boar = "Boar",
	cat = "Cat",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Cow",
	coyote = "Coyote",
	deer = "Deer",
	hen = "Hen",
	husky = "Husky",
	mtlion = "Lion",
	pig = "Pig",
	poodle = "Poodle",
	pug = "Pug",
	rabbit = "Rabbit",
	rat = "Rat",
	retriever = "Retriever",
	shepherd = "Shepherd",
	westy = "Westy",

	player_id = "ID hrace",
	bounty = "Odmena",
	reason = "Duvod",
	id_player_not_found = "~r~Žádný hrac nebyl nalezen s tímto ID.",

	ammo_dealer = "Prodejce naboju",
	misc_dealer = "Prodejce všeho mozneho",
	veh_dealer = "Prodejce aut",
	custom_dealer = "LS Custom",
	gun_dealer = "Obchodník se zbranemi",

	bounty_created = "Zaplatil jsi ~g~$%s~w~ za vypsání odmeny na ~b~%s~w~.",
	contract_success = "Odmenu, kterou jsi vypsal na ~r~%s~w~ byla odeslána ~b~%s~w~.",
	a_contract_on_your_head = "~r~Byla na tebe vypsána odmena. Ten, kdo te zabil dostal odmenu.",
	reward_for_contract = "Lovec odmen! Dostal jsi odmenu ~g~$%s~w~ za zabití ~b~%s~w~.",

	hey_can_help_you = "Zdarec, jak ti muzu pomoct?",
	i_want_to_buy_items = "Chci si neco koupit",
	i_want_to_sell_items = "Chci neco prodat",

	press_context_or_jump_to_get_up = "Zmackni ~INPUT_CONTEXT~ nebo ~INPUT_JUMP~ pro ~b~zvednutí se~w~.",
	server_restart_warning = "Server se bude za chvíli restartovat..",
	auto_restart_in = "Automatický restart probehne za %s sekund.",

	not_allowed_create_character = "Nemuzes si vytvorit novou postavu.",
	character_not_yours = "Tato postava není tvoje.",
	character_does_not_exist = "Tato postava již neexistuje.",
	loading_character = "Nacitani tvojí postavy",

	playtime_is = "~b~Odehraný cas na Extinction:\n~w~%s",
	dont_spam = "^1Nespamuj!",

	babygod_warning = "~b~Opustil jsi safezonu, chvíli budeš nesmrtelný.",

	-- LS Custom
	modifications_classiques = "Klasické modifikace",
	modifications_custom = "Speciální modifikace",
	modifications_benny = "Benny's modifikace",
	paint = "barva",
	custom_your_car = "Vytun svoje auto",
	wheels_modifications = "Kola",
	performances = "Výkon",
	neons = "Neony",
	extra = "Extra",
	klaxon = "Horn",
	teinte_fenetre = "Windows tint",
	phares_xenons = "Xenon headlights",
	modele_plaque = "Plate model",
	livery = "Livery",
	headlight_color = "Headlights color",
	wheel_type = "Wheel type",
	primary_wheel_type = "Primary wheel type",
	back_wheel_type = "Back wheel type",
	wheel_color = "Wheel color",
	tire_smoke = "Tire smoke",
	custom_color = "Custom color",
	custom_wheel = "Custom wheel",
	custom_back_wheel = "Custom back wheel",
	suspension = "Suspension",
	transmission = "Transmission",
	moteur = "Engine",
	frein = "Brake",
	turbo = "Turbo",
	primary_color = "Primary color",
	secondary_color = "Secondary color",
	interior_color = "Interior color",
	dashboard_color = "Dashboard color",
	color_effect = "Color effect",
	left_neon = "Left neon",
	right_neon = "Right neon",
	front_neon = "Front neon",
	back_neon = "Back neon",

	aileron = "Spoiler",
	pc_front = "Front bumper",
	pc_back = "Rear bumper",
	carroserie = "Side skirt",
	exhaust = "Exhaust",
	cadre = "Frame",
	calandre = "Grille",
	capot = "Hood",
	gb_left = "Left fender",
	gb_right = "Right fender",
	roof = "Roof",
	plate_support = "Plate holders",
	front_plate = "Front plate",
	interior_style = "Interior style",
	figurine = "Figurine",
	motif_dashboard = "Dashboard style",
	cadran = "Dial design",
	haut_parleur_portes = "Speaker doors",
	motif_sieges = "Seat style",
	volant = "Steering wheel",
	levier = "Shifter leavers",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Speaker back doors",
	hydrolique = "Hydraulics",
	moteur = "Engine",
	filtres_air = "Air filter",
	entretoises = "Spacers",
	arc_couverture = "Arch",
	antenne = "Antenna",
	motif_exterieur = "Exterior style",
	reservoir = "Tank",
	window = "Window",
	style = "Style",
	default = "Default",
	type = "Type",
	normal = "Normal",
	black = "Black",
	black_smoke = "Black smoke",
	simple_smoke = "Simple smoke",
	stock = "Stock",
	limo = "Limousine",
	sa_black = "San Andreas black",
	sa_blue = "San Andreas blue",
	sa_white = "San Andreas white",
	simple_white = "Simple white",
	ny_white = "North Yankton white",
	race = "Race",
	sport = "Sport",
	stock = "Stock",
	street = "Street",
	discount = "Sleva",
	select_your_car = "Vyber svoje auto",
	select_car_custom = "Vyber vozidlo, které chceš vytunit. Cislo mezi šipkama je cislo vozidla, pokud jich máš v inventari více.",
	loading_vehicle = "Spawnování vozidla",
	invalid_vehicle = "~r~Nesprávné vozidlo.",
	invalid_vehicle_please_spawn = "~r~Nesprávné vozidlo. Prosím spawni svoje auto alespon jednou predtim, než ho budeš modifikovat.",
	free_take_and_validate = "Všechno je zdarma. Vyber si co chceš a potvrd svuj vyber!",
	car_custom_saved = "~g~Modifikace tvého vozidla byly uloženy.",

	-- Character creation
	character_creation = "Vytvoreni postavy",
	confirm = "potvrdit",
	start_playing = "Hrát",
	appearance = "vzhled",
	character_list = "seznam postav",
	face_features = "rysy obliceje",
	parents = "rodice",
	parent = "rodic",
	mix = "mix",
	skin = "kuze",
	desc_mix = "Vyber jestli je tvuj oblicej více podobný na otce/matku.",
	desc_skin = "Vyber jestli je barva kuze více ovlivnena otcem/matkou.",
	identity = "identita",
	player_name = "jméno hrace",
	new_character = "nová postava",
	warning_headblend = "~r~Nevybral sis rodice tvé postavy.",
	warning_overlays = "~r~Nevybral sis vlasy, oboci nebo vousy.",
	warning_identity = "~r~Varování.~n~~w~Zapomnel jsi vyplnit tabulku o identite.",

	-- kits
	kit_does_not_exist = "~r~Tento kit neexistuje.",
	kit_needs_rank = "Nemáš ~r~%s~w~ roli.",
	wait_before_using_kit = "Prosím pockej ~r~%s~w~ pred obdržením tohoto kitu.",
	received_kit = "Obdržel jsi kit ~b~%s~w~.",
	no_kit = "Nemáš žádný kit.",

	unable_to_find_booster = "Nebylo možné najít žádný booster s tímto ID.",
	wait_already_player_boost = "Prosím pockej chvíli než použiješ tento booster. Tento booster je již aktivní.",
	wait_already_crew_boost = "Prosím pockej chvíli než použiješ tento booster. Crew booster je již aktivní.",
	wait_already_server_boost = "Prosím pockej chvíli než použiješ tento booster. Server booster je již aktivní.",
	booster_activated = "Booster aktivován na ~g~%s minut~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ aktivoval server booster na ~g~%s minut~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ aktivoval crew booster na ~g~%s minut~z~! ~b~XP +%s%%",
	no_booster = "Nemáš žádný booster.",

	rank_expired = "~r~Tvoje role vypršela.",
	supporter_role = "~g~Role:~w~ %s",
	no_rank_warning = "Nemáš žádnou roli.\n~r~Pokud sis neco zakoupil, musíš si linknout svuj FiveM ucet.",
	no_fivem_id = "Nemáš linknutý FiveM ucet.\n~r~Zkontroluj, že máš FiveM ucet linknutý s hrou.",
	no_queue_warning = "Nemáš žádný balicek v rade.\n~r~Zkus chvíli pockat nebo napsat /getRank pokud jsi nedostal svou roli.",
	package_sync_success = "~g~Tvuj nákup byl synchronizovaný, užívej!\n~w~Uzitecne prikazy: /getRank, /booster",

	level_required = "Musíš být level %s.",
	rank_required = "Musíš mít alespon hodnost %s.",
	level_required_2 = "~r~Musíš být level %s.",

	updated_deathmessage = "~g~Aktualizoval jsi svou zprávu po smrti.",
	updated_deatheffect = "~g~Aktualizoval jsi svuj efekt pri zabití.",
	use = "Použít",
	test = "Test",

	-- zombie
	you_bitten = "~r~Byl jsi nakažen.",
	infection_rate = "Míra infekce: ~r~%s%%",

	-- ranks
	thug = "Thug",
	hustler = "Hustler",
	soldier = "Soldier",
	trigger = "Trigger",
	enforcer = "Enforcer",
	facilitator = "Facilitator",
	public_enemy = "Public Enemy",
	shot_caller = "Shot Caller",
	street_boss = "Street Boss",
	kingpin = "Kingpin",
	-- Tattoo
	tattoo = "tetování",
	tattoos = "tetování",
	torso = "trup",
	head = "hlava",
	left_arm = "levá ruka",
	right_arm = "pravá ruka",
	left_leg = "levá noha",
	right_leg = "pravá noha",
	unknown = "neznámé",
	other = "ostatní",
	remove_tattoo = "Odstranit všechna tetování",
	-- Hairdress
	haircuts = "Ucesy",
	makeup = "Makeup",
	face = "Oblicej",
	eyebrows = "Oboci",
	facial_hair = "Vousy",
	body_hair = "Chlupy na tele",
	barber_shop = "Holicstvi",
	face_makeup = "Makeup",
	lipstick = "Rtenka",
	face_foundation = "Oblicejovy základ",
	skin_blemishes = "Kožní vady",
	skin_ageing = "Stari",
	moles_freckles = "Pihy",
	sun_damage = "Poškození kuze",
	skin_complexion = "Pokožka",
	body_blemishes = "Telesne vady",
	body_blemishes_2 = "Telesne vady 2",
	opacity = "Alpha",
	variations = "Variace",
	filter = "Filtr",
	eyes_color = "Barva oci",
	-- Mask
	masks = "Masky",
	-- Items
	money = "Peníze",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	rocket = "Rocket",
	flare = "Flare",
	grenade = "Grenade Ammo",
	-- Food
	["fish_1"] = "Largemouth Bass",
	["fish_2"] = "Rainbow Trout",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Arctic Grayling",
	["fish_5"] = "Rock Bass",
	["fish_6"] = "Smallmouth Bass",
	["fish_7"] = "Paddlefish",
	["fish_8"] = "Bull Trout",
	["fish_9"] = "Lake Trout",
	["fish_10"] = "Chinook",
	["fish_11"] = "Pallid Sturgeon",
	["fish_12"] = "Salmon",

	misc_meat = "Raw meat",
	rabbit_meat = "Raw rabbit",
	lion_meat = "Raw lion",
	rare_plume = "Rare feather",
	dog_meat = "Raw dog",
	cat_meat = "Raw cat",
	rare_fish = "Rare fish",

	mask = "Mask",
	malette = "Suitcase",
	malette_metal = "Metal suitcase",
	ciseaux = "Scissors",
	clean_kit = "Clean kit",
	fishing_rod = "Fishing rod",
	meuble = "Furniture",
	tissu = "Cloth",
	accessory = "Accessory",
	radio = "Radio",
	recyclor = "Recycler",
	medkit = "Medkit",
	kevlar = "Kevlar",
	gps = "GPS",
	repair_tool = "Repair kit",
	jvn = "JVN",
	engine_veh = "Engine",
	bag = "Sac",
	wheel_veh = "Wheel",
	vetement = "Top",
	bloc_note = "Notepad",
	paint_spray = "Paint spray",
	spike = "Spike strip",
	paracetamol = "Paracetamol",
	bandage = "Bandage",
	gaz_mask = "Gaz mask",
	filter = "Filtr",
	tattoo_tool = "Tattoo tool",
	drug_med = "Drug",
	drug_antizin = "Antizin shot",
	drug_stamina = "Stamina shot",
	drug_berserker = "Health shot",

	pickup_spikestrip = "sebrání zastavovacího pásu",
	you_dropped_spikestrip = "Položil jsi ~g~zastavovací pás~w~.",
	you_pickup_spikestrip = "Sebral jsi ~g~zastavovací pás~w~.",

	you_have_been_killed_by = "Zabil te ~r~%s",
	kill_notif = "~m~Zabit",
	you_killed = "Zabil jsi ~r~%s~w~",
	already_used_reset_only = "~r~Už sis resetoval svou postavu.\n~w~Pouze %s~w~ clenove mohou resetovat svou postavu vícekrát než jednou.",
	already_used_reset_only2 = "~r~Tohle jsi už udelal.\n~w~Pouze %s~w~ clenove to mohou použít vícekrát.",

	hud_options = "Nastavení HUD",
	advanced_hud = "Zobrazit pokrocily HUD",
	players = "Hraci",
	health = "Zdraví",
	player_menu = "Menu hrace",

	you_are_now_zombie = "~r~Nyní jsi zombík.",

	my_weapons = "moje zbrane",
	customize_weapons = "modifikace zbrane",
	weapon_skin = "Odstín",

	-- camo
	skin_classic = "Defaultní",
	skin_green = "Zelená",
	skin_yellow = "Žlutá",
	skin_pink = "Ruzova",
	skin_gold = "Zlatá",
	skin_blue = "Modrá",
	skin_orange = "Oranžová",

	weapon_katana = "Katana",
	weapon_sledgehammer = "Sledge Hammer",

	-- new
	airdrop_coming = "~r~Blíží se airdrop, podívej se na mapu.",
	killed_by_cheater = "~r~Byl jsi zabit cheaterem.\n~w~Zabanovali jsme ho a tvoje smrt byla vyresetována.",

	corrupted_vehicle = "~r~Toto vozidlo je poškozené a v minulosti bylo duplikované, proto bylo odstraneno z inventare. Omlouváme se, pokud te nekdo okradl.",

	-- Discord
	join_discord_for_kit = "Pripoj se na náš Discord pro získání kitu!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~Musíš si linknout svuj Discord ucet s FiveM.",
	discord_account_not_guild = "~r~Nejsi na našem Discord serveru.\n~w~Pripoj se discord.gg/gtalife",

	already_done_recently = "~r~Zkus to znovu pozdeji, v poslední dobe jsi to již provedl.",
	update_country = "Zmenit zemi",

	prestige_info = "~b~Dosáhl jsi maximálního levelu.\n~w~Napiš /prestige pro získání informací o systému prestiží.",
	prestige_not_max_level = "~r~Nedosáhl jsi nejvyššího možného levelu.",
	max_prestige_reached = "~r~Dosáhl jsi poslední prestiže.",
	prestige_info_cmd = [[^3Systém prestiží^7
Prave máš prestiž ^4%s^7 a level ^5%s^7.

Pokud dosáhneš maximálního levelu (%s) muzes si zvolit prestiž a restartovat svuj level na level 0.
Získáním nové prestiže dostaneš speciální odznak a body, kterými si muzes napriklad zvetsit velikost inventare.
^2Pokud si chceš dát prestiž a VRÁTIT se na level 0, napiš ^1/setprestige^2
]],
	new_prestige = "Odemkl jsi novou prestiž!\n~g~Nyní máš %s prestiží",
	cant_store_event_veh = "~r~Nemuzes uschovat legendární vozidla.",

	you_are_no_longer_in_combat = "🛡️ ~b~Už nejsi v combatu.",
	you_are_in_combat_mode = "🛡️ ~b~Jsi v combatu.\nPokud se odpojíš, zemres.",
	you_disconnected_in_combat = "💀 Odpojil ses v combatu, zemrel jsi.",

	not_enough_prestige_points = "~r~Nemáš dostatek bodu na prestiž.",
	you_reached_max_prestige_stats_rank = "~r~Získal jsi nejvyšší možnou uroven pro tuto prestiž.",
	new_prestige_stats_upgrade = "Vylepšil jsi svuj ~b~%s~w~\n~g~%s/%s",

	legendary_vehicle_pop = "~r~Legendární vozidlo se objevilo nekde na mape.",

	-- poll one
	poll1_q1 = "Jaký server bys rád videl?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Private missions solo nebo s 1-4 kamarády (neco jako Payday/heisty/Hitman)",
	poll1_q1_a3 = "Race / Freeroam",
	poll1_q1_a4 = "Murder / Horror game",

	-- poll two
	poll2_q1 = "Mluvíš anglicky a mel bys zájem o RP server?",

	poll2_q1_a1 = "Ne",
	poll2_q1_a2 = "Ano",

	combat_mode_container_disabled = "~r~Jsi v combatu.\n~w~Nemuzes uschovávat veci.",
	gcoins_wallet_updated = "~g~Tvoje penezenka s GCoiny se aktualizovala.\n~w~+%s GCoinu",
	not_enough_gcoins = "~r~Nemáš dostatek GCoinu.",
	gcoins_something_went_wrong = "~r~Neco se nepovedlo.",
	you_bought_with_gcoins = "Koupil sis ~g~%s~w~ za ~b~%s GCoinu~w~.",

	equiping_armor = "Nasazování armoru",

	toggle_mute_player = "Mutnout hrace",
	you_muted_this_player = "~b~Mutnul sis tohoto hrace.",
	you_unmuted_this_player = "~b~Odmutnul sis tohoto hrace.",

	already_purchased = "~r~Tento predmet už jsi koupil.",
	weapon_camo_preview = "Prave se díváš na náhled modelu, nektere komponenty chybí.\n~INPUT_CELLPHONE_CANCEL~ pro opusteni náhledu.",

	already_using_a_seringue_booster = "~r~Tohle sis už píchnul.",
	seringue_effect_done = "~b~Efekt Antizin shotu skoncil.",
	you_injected_a_seringue_boost = "Píchnul sis ~b~Antizin shot~w~ do krve.",

	put_item_permission = "Vložit veci",
	take_item_permission = "Vzít veci",
	put_money_permission = "Vložit peníze",
	take_money_permission = "Vzít peníze",

	preferred_badge_set = "Nastavil jsi svuj ~g~preferovaný odznak~w~.",
	preferred_badge_not_set = "~r~Nemuzes si nastavit svuj preferovaný odznak.",

	i_want_to_enter_in_my_property = "Chci do bunkru.",
	i_want_to_exit_private_world = "Chci do verejneho sveta.",
	public_world = "Public svet",
	private_world = "Private svet",

	dailymission_playerkill = "Zabito hracu",
	dailymission_zombiekill = "Zabito zombiku",
	dailymission_playerheadshotkill = "Zabito hracu headshotem",
	dailymission_zombieheadshotkill = "Zabito zombiku headshotem",
	dailymission_zombiesurvivorkill = "Zabito survivor zombiku",
	dailymission_zombiearmoredkill = "Zabito armored zombiku",
	dailymission_zombiehazmatkill = "Zabito hazmat zombiku",
	dailymission_zoombieboomerkill = "Zabito boomer zombiku",
	dailymission_sellitems = "Prodaných veci",
	dailymission_buyitems = "Koupených veci",
	dailymission_lootitems = "Nalootenych veci",
	dailymission_createselloffer = "Vytvoreno nabídek",
	dailymission_killtopkillcrew = "Zabito hracu z crew",
	dailymission_killtopkillplayers = "Zabito hracu",
	dailymission_getintolegendaryvehicle = "Vozidel",
	dailymission_killzombiewithweapon = "Zabito zombiku se zbraní",
	dailymission_killplayerwithweapon = "Zabito hracu se zbraní",
	dailymission_darkzonesurvivingtime = "Prezito v darkzone",
	dailymission_redzoneplayerkill = "Killu hracu v redzone",
	dailymission_redzonezombiekill = "Killu zombiku v redzone",
	dailymission_darkzoneplayerkill = "Killu hracu v darkzone",
	dailymission_darkzonezombiekill = "Killu zombiku v darkzone",
	dailymission_useitem = "Použito veci",
	dailymission_playtime = "Odehraný cas",
	dailymission_xpharvest = "Získáno XP",
	dailymission_sellofferpurchased = "Nabídek prodáno",
	dailymission_sellofferpurchasedbyme = "Nabídek nakoupeno",
	dailymission_tradeitems = "Predmetu vytradováno",
	dailymission_createbuyoffer = "Nabídek vytvoreno",

	dailymission_completed = "~g~Splnil jsi denní ukol!\n~b~+%s XP\n~y~+1 Dungeon klic",

	character_creation_mix_desc = "Vyber jestli je tvuj oblicej více podobný na otce/matku.",
	character_creation_skin_desc = "Vyber jestli je barva kuze více ovlivnena otcem/matkou.",

	ff_1 = "Sirka nosu",
	ff_2 = "Výška nosu",
	ff_3 = "Délka nosu",
	ff_4 = "Pokles nosu",
	ff_5 = "Pokles spicky nosu",
	ff_6 = "Zakroucení nosu",
	ff_7 = "Výška oboci",
	ff_8 = "Hloubka oboci",
	ff_9 = "Výška lícních kostí",
	ff_10 = "Sirka lícní kosti",
	ff_11 = "Sirka líc",
	ff_12 = "Otevreni oci",
	ff_13 = "Tloustka rtu",
	ff_14 = "Sirka celisti",
	ff_15 = "Délka zadní celisti",
	ff_16 = "Snížení brady",
	ff_17 = "Délka brady",
	ff_18 = "Sirka brady",
	ff_19 = "Rozstep brady",
	ff_20 = "Tloustka krku",

	airdrop_taken_by = "^1%s vzal %s z airdropu.",

	available_death_effects = "Dostupné efekty pri zabití",
	available_modes = "Dostupné mody",

	you_changed_your_ped_model = "~g~Uspesne jsi zmenil svuj ped.",
	i_want_to_change_my_ped = "Chci si zmenit peda",

	poll4_q1 = "Co ocekavas od další sezony?",
	poll4_q1_a4 = "Nové eventy jako airdropy, zabírání zon atd.",
	poll4_q1_a1 = "Více PvE možností jako napriklad dungeony",
	poll4_q1_a2 = "Více her jako napriklad kasíno/závody",
	poll4_q1_a3 = "Více PvP možností",

	poll4_q2 = "Chtel bys mít více turnaju/ranked zapasu?",
	poll4_q2_a1 = "Ano",
	poll4_q2_a2 = "Ne",

	poll4_q3 = "Chtel bys sniperky v obchode?",
	poll4_q3_a1 = "Ano",
	poll4_q3_a2 = "Ne",

	poll4_q4 = "Co si nejvíc užíváš na Extinction?",
	poll4_q4_a1 = "PvP",
	poll4_q4_a2 = "PvE",
	poll4_q4_a3 = "Obchodování",

	dungeon_no_more_time = "~r~Byl jsi prilis pomalý. Dungeon se uzavrel.",
	dungeon_participant_left = "~r~%s opustil dungeon.",
	started_dungeon_party = "~b~Vytvoril jsi dungeon.",
	dungeon_party_no_longer_exists = "~r~Tato dungeon parta již neexistuje.",
	dungeon_invitation_expired = "~r~Tato pozvánka vypršela.",
	dungeon_join_party = "~g~Pripojil ses do dungeon party.",
	dungeon_too_late_for_invitation = "~r~Prijal jsi pozvánku prilis pozde. Nemuzes se pripojit do probíhajícího dungeonu.",
	dungeon_already_invited_this_player = "~r~Tohoto hrace už jsi pozval.",
	dungeon_invitation_received = "Získal jsi pozvánku od ~b~%s~w~ do jeho dungeon party.\nNapiš ~g~/dungeon join %s~w~ pro pripojeni se.",
	dungeon_invitation_sent = "Pozval jsi ~g~%s~w~ do tvojí dungeon party.",

	i_want_to_enter_a_dungeon = "Chci navštívit dungeon",
	dungeon_list = "Seznam dungeonu",
	dungeon = "Dungeon",
	dungeons = "Dungeony",
	you_need_x_keys = "Potrebujes ~y~%s dungeon klicu~w~ pro vstup do dungeonu.",
	time_remaining = "Zbývající cas",
	you_killed_the_dungeon_boss = "~r~Zabil jsi dungeon bosse.",
	dungeon_kill_final_boss = "Jsi v poslední místnosti. Zabij bosse, abys získal jeho poklad.",

	dungeon_died_remaining = "Umrel jsi, máš ~r~%s~w~ zbývajících životu.",
	dungeon_died = "~r~Už nemáš žádné zbývající životy. Zemrel jsi.",
	dungeon_already_in_party = "~r~Už jsi v dungeon party.\n~w~Napiš /dungeon quit pro opusteni.",
	dungeon_does_not_exist = "~r~Tento dungeon neexistuje.",
	dungeon_ready = "~g~%s~w~ je pripraven.",
	dungeon_not_ready = "~r~%s~w~ není pripraven.",

	not_released_yet = "Toto jeste není vydáno.",
	feature_only_supporters = "~b~Tato funkce je teprve v bete a pouze hraci s ranky Gold/Diamond ji mohou používat.",
	feature_not_enabled = "~b~Tato funkce není jeste zapnutá.\n~w~Prosím pockej, až se tato funkce spustí.",
	dungeon_charid_required = "~r~Prosím zadej character ID tvého kamaráda (nachází se na obrazovce vpravo nahore).\nPriklad: /dungeon invite 1234",

	poll5_q1 = "Mel bys problém pokud by náš anticheat vyscreenoval obrazovku cheatera, pokud by byl podezrely, že používá wallhack/aimbot? (je možné, že to ukáže cast plochy, pokud máš hru v okne, ale tyto screeny nejsou uloženy a jsou pristupne pouze pro moderátory)",
	poll5_q1_a1 = "preskocit - ignorovat",
	poll5_q1_a2 = "Ano, souhlasím s touto novou metodou",
	poll5_q1_a3 = "Ne, nesouhlasím",
	
	-- S4
	redzone_kill_leader_killed = "~r~Kill leader v redzone~w~ byl zabit.",
	redzone_kill_leader_fled = "~r~Kill leader v redzone~w~ utekl.",
	redzone_get_back_kill_leader_before_x = "Jsi ~r~mimo redzonu~w~ vrat se zpátky nebo ztratíš status kill leadera za ~r~%s sekund~w~.",
	redzone_kill_leader_new_xp_step = "~r~Násobitel XP v redzone\n~b~+%s%~w~ bonus",
	remaining_lives = "Zbývající životy",

	name_tag = "Crew tag",
	redzone_changed = "~r~Redzony se premistily na nové lokace.",

	-- Squad
	squad_not_leader = "~r~Nejsi leader tvojí squady.",
	squad_kicked_by_x = "¨Byl jsi ~r~vyhozen~w~ z tvojí squady hracem ~r~%s~w~.",
	squad_you_kicked_x = "Vyhodil jsi ~r~%s~w~ z tvojí squady.",
	squad_invited_x = "Pozval jsi ~r~%s~w~ do tvojí squady.",
	squad_invited_you_x = "~r~%s~w~ te pozval do jeho squady.\nNapiš ~r~/squad join %s~w~ pro prijmuti pozvánky.",
	squad_you_set_new_leader = "Urcil jsi ~r~%s~w~ jako nového ~r~leadera~w~ squady.",
	squad_you_are_new_leader = "~g~Nyní jsi nový leader squady.",
	squad_not_invited = "~r~Nebyl jsi pozván do žádné squady.",
	squad_joined_squad = "~g~Pripojil ses do squadu.",
	squad_left = "~r~Opustil jsi squad.",
	squad_already_in = "~r~Už jsi v nejake squade.",
	squad_created_x = "Vytvoril jsi nový squad. ~b~(%s)",
	squad_x_joined = "~b~%s~w~ se pripojil do squadu.",
	squad_leader_deleted = "~r~Leader smazal tento squad.",
	write_yes_to_confirm = "Napiš yes pro potvrzení",
	invite_a_player_write_char_id = "Pozvi hrace. Napiš jeho character ID",

	-- Help stuff
	press_enter_beginner_guide = "Zmackni ~INPUT_ENTER~ pro zapnutí návodu pro novacky.",
	welcome_glife = "Vítej na ~g~GLife~w~!",
	you_are_playing_server_x_with_x = "Hraješ na serveru ~b~#%s~w~ s ~b~%s hraci~w~.",
	start_beginner_guide = "Zacit návod pro novacky",
	play_now = "~g~Hraj nyní!",
	interact_npc_fast_travel = "Promluv si s teleportérem",

	-- Tutorial
	tutorial_beginner_end_msg = "~r~Díky za tvuj cas!\n~w~Užívej Extinction, pokud máš nejake otázky zeptej se v chatu nebo navštiv náš Discord.",
	tutorial_beginner_start_msg = "~r~Vítej na serveru GLife Extinction!\n~w~Tímto krátkým návodem zjistíš jak zde zacit.",
	tutorial_beginner_camera_01 = "~r~~BLIP_557~ ~r~Hlavní safezona\n~w~V této zone muzes nakupovat a uschovávat svoje veci, ale také si zde muzes modifikovat svoji výbavu a obchodovat s ostatními hraci.",
	tutorial_beginner_camera_02 = "~BLIP_568~ ~r~Sklad\n~w~Tady muzes navštívit svuj sklad a uschovat si zde tvoje cenné veci.",
	tutorial_beginner_camera_03 = "~BLIP_567~~BLIP_556~~BLIP_658~ ~r~NPC obchodníci\n~w~Muzes nakupovat a prodávat svoje veci u obchodníka se zbranemi, autami nebo u prodejce všeho možného.",
	tutorial_beginner_camera_04 = "~BLIP_84~ ~r~Verejne odmeny\n~w~Pokud se ti podari najít a zabít cílového hrace, dostaneš urcitou odmenu.",
	tutorial_beginner_camera_05 = "~BLIP_176~ ~r~Nepratelsky svet\n~w~Potkáš zombíky a ostatní hrace. Všichni te budou chtít zabít, ale na druhou stranu jsou nejlepším zpusobem, jak získat XP a loot.",
	tutorial_beginner_camera_06 = "~BLIP_303~ ~r~Redzony\n~w~Tady muzes mít lepší loot a budeš získávat více zkušeností za killy.",
	tutorial_beginner_camera_07 = "~BLIP_648~ ~r~Darkzona\n~w~Zde nemuzes uschovávat veci nebo utéct tak jednoduše, ale je to nejlepší místo, kde najít nejlepší loot jako jsou MK2 zbrane nebo sniperky.",
	tutorial_beginner_camera_08 = "~BLIP_575~ ~r~Ostatní prilezitosti\n~w~Muzes bojovat o airdrop ale také muzes prozkoumat dungeon a na konci zabít bosse.",
	tutorial_beginner_training_01 = "~g~Pripojil ses do tréninkové místnosti.\n~w~Skoc pomocí ~INPUT_JUMP~ až budeš pripraven.",
	tutorial_beginner_training_02 = "~g~Použij inventar.\n~w~Zmackni ~%s~ pro otevreni inventare.",
	tutorial_beginner_training_03 = "~g~Vem si zbran.\n~w~Otevri inventar a presun zbran do lišty dole.\nZmackni urcitou klávesu ~b~1/2/3/4/5/6/7~w~.\n~r~Pokud nemáš žádnou zbran, použij ~b~/kit newbie.",
	tutorial_beginner_training_04 = "~g~Nabij svoji zbran.\n~w~Vem si zbran a vlož náboje do lišty dole, pak zmackni urcitou klávesu.",
	tutorial_beginner_training_05 = "~g~Konecne vozidla.\n~w~Ted muzes spawnovat auta stejne jako používáš náboje nebo zbrane. Jakmile spawneš auto, muzes ho schovat ~%s~ zatímco stojíš na miste. Zmackni klávesu pro potvrzení.",
	tutorial_beginner_training_success_01 = "~g~Dobrá práce, nyní muzeme zacit!",
	tutorial_beginner_training_success_02 = "~g~Dobre, zvládl jsi to.\n~w~Proces je stejný pro všechny predmety.",
	tutorial_beginner_training_success_03 = "~g~Dobre, zvládl jsi to.\n~w~Proces je stejný pro všechny predmety.",
	tutorial_beginner_training_success_04 = "~g~Dobre, zvládl jsi to.\n~w~Nyní jsme hotoví.",

	-- Darkzone stuff
	contaminated = "kontaminováno",
	darkzone_boat_leaving_in = "Lode zmizí za",
	darkzone_exit = "Místo pro opusteni",
	purificator = "Purifikátor",
	you_entered_the_darkzone = "~r~Vstoupil jsi do darkzony.\n~w~Momentalne je uvnitr ~b~%s hracu~w~.",
	you_left_the_darkzone = "~r~Opustil jsi darkzonu.",
	cannot_enter_darkzone_time = "~r~Darkzona jeste není otevrena, cekej.",
	darkzone_is_full = "~r~Darkzona je plná, prosím cekej.",
	darkzone_exit_allowed = "~r~Lode jsou zde pro opusteni darkzony, utíkej pokud chceš opustit darkzonu.",
	darkzone_close_time = "Zavírá se za",
	darkzone_surviving_since = "Prezivas",
	darkzone_points = "Bodu",
	darkzone_points_x = "~r~Darkzone bodu: ~w~+%s",
	darkzone_landing_in_x = "Darkzona se otevre za ~b~%s minut~w~.\nPokud bude dostatek hracu.",
	darkzone_open_press_context = "Zmackni ~INPUT_CONTEXT~ pro vstoupení ~m~do darkzony~w~.",
	darkzone_outside_warning = "~r~Jsi mimo darkzonu, vrat se nebo umres.",
	darkzone_close_warning = "~r~Darkzona se brzy uzavre~w~.\nNemel bys zde zustavat prilis dlouho.",
	darkzone_close_damage = "Darkzona se uzavrela, celá oblast je nyní kontaminovaná.",
	darkzone_not_enough_points_to_exit = "Potrebujes ~r~%sx bodu~w~ pro opusteni darkzony.",
	press_e_to_exit_the_darkzone = "Zmackni ~INPUT_CONTEXT~ pro opusteni darkzony.\n~r~Potrebujes x%s darkzone bodu.",
	use_purificator = "použití purifikátoru",
	darkzone_not_enough_points_to_start_purificator = "Potrebujes ~r~%sx bodu~w~ pro zapnutí purifikátoru.",
	darkzone_not_enough_points_to_refill_purificator = "Potrebujes ~r~%sx bodu~w~ pro doplneni purifikátoru.",
	darkzone_too_far_from_purificator = "~r~Jsi prilis daleko od purifikátoru.",
	darkzone_cant_remove_while_running_purificator = "~r~Nemuzes vybírat veci pokud je purifikátor zapnutý.",
	darkzone_purificator_running = "~r~Nemuzes vkládat veci dovnitr pokud je purifikátor zapnutý.",
	darkzone_purificator_running_refill = "~r~Nemuzes doplnit purifikátor pokud je prave zapnutý.",
	darkzone_put_x_in_purificator = "Vložil jsi ~r~%s~w~ do purifikátoru.",
	darkzone_you_took_x_from_purificator = "Vzal jsi ~r~%s~w~ z purifikátoru.",
	darkzone_purificator_does_not_need_refill = "Nepotrebujes ~r~doplnovat tento purifikátor~w~.",
	darkzone_refilled_purificator_x = "Použil jsi ~r~x%s bodu~w~ pro doplneni purifikátoru.",
	darkzone_open = "Darkzona se otevrela.\n~r~Najdi transportér v jakékoliv safezone.",
	darkzone_item_clean = "Tato položka už je predelana.\n~r~Muzes vkládat pouze kontaminované veci.",
	
	dungeon_cooldown_between = "Prosím pockej ~r~%s minut~w~ pred startem dalšího dungeonu.",
	set_as_default = "Nastavit jako defaultní modifikaci pro tento model vozidla",
	car_custom_presets_saved = "Preset modifikací pro ~g~%s~w~ byl uložen.",

	above_level_x_no_longer_possible_loot_safe = "Hraci nad level %s nemuzou lootovat zombíky v safezonách.",
	preferred_component_desc = "Tento set bude defaultní set pro všechny %s zbrane, které budeš držet.",
	set_as_preferred_component_class = "Nastavit jako preferovaný set komponentu",
	weapon_presets_updated = "Nastavil sis defaultní preset komponentu pro ~g~%s~w~.",

	-- New survey
	poll6_q1 = "Chtel bys snížit limit clenu v crew na 25? (více konkurence, menší skupinky)",
	poll6_q2 = "Máš v pohode ping na tvém main serveru? (je tvuj prumerny ping v pohode?)",
	poll6_q3 = "Hraješ v private worldu?",
	poll6_q4 = "Mel by být zaplý headshot damage pro sezonu 4?",
	
	casino_dungeon_desc = "⚠️ ~r~Budeš potrebovat baterku na zbran, abys tam dobre videl.",
	dungeon_destroy_wall_obj = "Znic zed, která ti blokuje cestu.",
	dungeon_use_key_obj = "Použij klic k otevreni dveri.",
	dungeon_kill_zombies_obj = "Zabij všechny zombíky.",
	dungeon_kill_zombies_obj_x = "~b~Zabij všechny zombíky.~w~\n%s/%s hracu zabilo všechny zombíky.",
	dungeon_use_key_to_open_door = "Použij klic pro otevreni dveri.",
	dungeon_find_key_obj = "Najdi klic, kterým otevres dvere.",
	take_key = "získání klice",
	open_the_door = "otevreni dveri",
	dungeon_quit_notif = "Napiš ~g~/dungeon quit~w~ pro opusteni dungeonu.",
	dungeon_generator_obj = "Najdi generátor a obnov elektrinu.",
	dungeon_press_generator = "Zmackni ~INPUT_CONTEXT~ pro zapnutí generátoru.",
	power_generator = "Generátor elektrické energie",
	dungeon_find_c4_obj = "Nekde tu je schovaná C4, najdi ji.",
	dungeon_use_c4_obj = "Použij C4 k odpálení trezoru.",
	dungeon_party_help = "Napiš ~b~\"/dungeon\"~w~ pro správu tohoto dungeonu.",
	press_x_to = "Zmackni %s pro %s",

	quest_clean_zone = "Zabij zombíky v zone: %s",
	quest_clean_zone_desc = "Prijed do zony %s a zabíjej zde zombíky.",

	loot_crate_light = "Light Loot Crate",
	loot_crate_medium = "Medium Loot Crate",
	loot_crate_high = "High Loot Crate",
	
	dailymission_killzombieinzoneid = "zombiku zabito v zone",
	dailymission_dungeonbosskilled = "Dungeon boss zabit",

	quest_too_far_npc = "~r~Jsi prilis daleko od NPC s ukoly.",
	quest_already_started_quest = "~r~Tento ukol už plníš.",
	quest_redo_in_x = "~r~Tento ukol už jsi splnil.\n~w~Budeš se moct pokusit ho splnit znovu po uplynutí ~b~%s",
	quest_max_quests_reached = "~r~Muzes prijmout pouze %s ukoly.",
	quest_new_accepted = "~g~Prijmul jsi nový ukol.",
	quest_gave_up = "~r~Vzdal ses tohoto ukolu.",
	quest_not_completed = "~r~Musíš splnit všechny casti tohoto ukolu.",
	quest_already_completed = "~r~Tento ukol už jsi splnil.",
	quest_all_completed = "~g~Uspesne jsi splnil všechny casti.",
	dungeon_key = "Dungeon klic",
	darkzone_cannot_enter_min_levels = "Musíš být level ~b~%s~w~ abys mohl vstoupit do darkzony.",
	darkzone_you_survived_x = "Prezil jsi ~r~%s minut~w~ v darkzone.",
	questmenu_command = "Otevrit menu s ukoly",
	squadmenu_command = "Otevrit squad menu",
	airdrop_coming_darkzone = "~r~V darkzone budou airdropy, podívej se na mapu.",
	darkzone_full_crew = "V darkzone je ~r~%s clenu~w~ z tvojí crew, pockej až nekdo opustí darkzonu.",

	crew_join_cooldown_x = "Musíš pockat ~r~%s~w~ než se budeš moct pripojit do této crew.",
	darkzone_not_enough_players_darkzone = "Darkzona se neotevre.\n~r~Není dostatek hracu.",

	dungeon_loot_boss_box = "~g~Bedna se objevila uprostred místnosti.",
	drug_antizin_bar = "Efekt Antizin shotu",
	drug_stamina_bar = "Efekt Stamina shotu",
	drug_berserker_bar = "Efekt Health shotu",

	squad_members_limit = "~r~Tvoje squad prekrocila limit clenu.",
	darkzone_only = "~r~Musíš být v darkzone.",
	darkzone_no_cars = "~r~V darkzone muzes používat pouze motorky, lode a ostatní vozidla, které mohou létat.",

	poll7_q1 = "Mel bys zájem o evropský server pouze pro hraní solo?",
	poll7_q2 = "Chtel bys opet dropovat AWP MK2/Marksman Rifle MK2 i z dropu?",

	you_have_been_muted = "~r~Byl jsi umlcen.~w~\nVypršení: ~b~%s~w~\nDuvod: ~b~%s",
	you_have_been_unmuted = "~g~Byl jsi odmlcen.",
	muted_x = "Umlcel jsi ~g~%s~w~.~w~\nVypršení: ~b~%s~w~\nDuvod: ~b~%s",
	unmuted_x = "Odmlcel jsi ~g~%s~w~.",
	invalid_duration = "~r~Nesprávná délka, prosím zadej správný cas.",
	player_already_muted = "~r~Tento hrac už je umlceny.",
	player_not_muted = "~r~Tento hrac není umlceny.",
	you_are_muted = "~r~Jsi umlceny.",

	open_mailbox = "otevreni schránky",
	you_entered_crew_pro = "~g~Vstoupil jsi do crew bunkru.",

	you_player_not_enough_gcoin = "~r~Nemáš dostatek GCoinu.",
	other_player_not_enough_gcoin = "~r~Hrac se kterým obchoduješ nemá dostatek GCoinu.",
	a_player_no_fivem_account_linked = "~r~Hrac se kterým obchoduješ nemá linknutý svuj FiveM ucet.",
	you_no_fivem_account_linked = "~r~Abys mohl tradovat GCoiny, musíš linknout svuj FiveM ucet.",
	trade_gcoin_for_gcoin_not_allowed = "~r~Nemuzes tradovat GCoiny za GCoiny.",
	cannot_delete_this_item = "~r~Nemuzes vymazat tuto položku.",
	impossible_on_solo_server = "~r~Tohle nemuzes delat na solo serveru.",

	warning_message = "Hraješ na SOLO serveru Extinction. Není zde povoleno teamovat s ostatními hraci, vytvaret squady/spojenectví. Pokud budeš prichycen pri teamování, budeš zabanován z tohoto serveru a docasne i z celého GLifu. Prosím respektuj pravidla a hraj solo.",
	bank_no_money = "~r~Nemáš žádné peníze.",
	bank_deposit_x = "Vložil jsi ~g~$%s~w~ do banky.",
	cannot_deposit_money_go_bank = "~r~Promin, zde nemuzes vložit peníze do banky.\n~w~Bez za opicí u banky.",
	bank_balance_x = "Zustatek v bance: ~g~$%s",
	store_money_bank = "~g~vložení penez do banky",
	wait_before_next_action = "Pockej ~r~%sms~w~ než budeš manipulovat s touto položkou.",
	bank = "Banka",

	poll8_q1 = "Chtel bys nahradit server 2 (solo server) serverem pouze pro dua?",
	poll8_q2 = "Máš rád banán?",

	reset_radar_tips = "Pokud chceš resetovat i radar, je pro to jiné nastavení.",
	redzone_shop = "Odmeny za redzone body",
	no_enough_redzone_points = "~r~Nemáš dostatek redzone bodu.",
	you_paid_basket_rp = "Zaplatil jsi ~r~%s RP~w~ za tvuj košík.",

	redzone_points_balance_x = "Redzone body: ~r~%s",
	top_kills = "Nejvice killu",
	top_zombies = "Nejvice zombiku",

	not_allowed_in_this_zone = "~r~Tohle nemuzes delat v této zone.",
	darkzone_disabled_for_update = "~r~Darkzony jsou momentalne vypnuté, budou zpátky s dalšími updaty.",
	loot_crate_halloween = "Halloween Loot Crate",

	new_weapon = "Nová zbran",
	winner_title = "Vitez",
	left_gungame_party = "~r~Opustil jsi lobby Gun Game.",
	outfit_gta = "GTA Outfity",

	poll10_q1 = "Kde si myslíš, že by mel být zaplý siphon mod?",
	poll_10_q1 = "Pouze v redzone",
	poll_10_q2 = "Všude",

	open_lobby_menu = "otevrit lobby menu",
	choose_game_lobby = "Vyber lobby",

	joined_lobby_x = "~g~Pripojil ses do lobby %s.~w~\nHerní režim: ~b~%s",
	gun_game = "Gun Game",
	spawn = "Spawn",
	return_lobby_help = "Pokud se chceš vrátit do hlavní lobby, napiš ~b~/lobby.",
	afk_press_key = "AFK?~r~~n~Zmackni klávesu.",
	sorry_it_is_ok = "~r~Promin!\n~w~Ted je to v pohode.",
	swimming_respawn_help = "~r~Vypadá to, že jsi ve vode.\n~w~Zmackni ~INPUT_CONTEXT~ pro respawn.",

	only_darkzone_item = "~r~Tento predmet muzes použít pouze v darkzone.",
	cant_get_darkzone_loadout = "~r~Nemuzes dostat tvoji výbavu do darkzony.\n~w~%s",
	press_e_to_exit_the_darkzone2 = "Zmackni ~INPUT_CONTEXT~ pro opusteni darkzony.",
	not_driving_vehicle = "~r~Neridis vozidlo.",
	not_enough_airdrop_points = "~r~Tvoje crew/squad nemá dostatek bodu na to, aby mohla otevrit airdrop.",
	airdrop_points = "Airdrop body",

	warning_message_duo = "Hraješ na DUO serveru Extinction. Není zde povoleno teamovat s více jak jedním hracem. Pokud budeš prichycen pri teamování, budeš zabanován z tohoto serveru a docasne i z celého GLifu. Prosím respektuj pravidla a hraj solo. Pokud budeš prichycen pri teamování s více jak jedním hracem, budeš zabanován z tohoto serveru a docasne i z celého GLifu. Prosím respektuj pravidla a hraj solo.",
	combat_mode_cannot_do_that = "~r~Jsi v combatu.\n~w~Tohle nemuzes delat.",
	open_darkzone_shop = "otevreni darkzone obchodu",
	dzone_flare_airdrop = "Svetlice airdropu",
	paid_x_points_for_x = "Zaplatil jsi ~r~%s~w~ bodu za ~r~%s~w~.",
	starter_pack_upgrade_1 = "Upgrade starter packu",
	extraction_package = "Výsadkový balicek",
	always_spawn_antizin = "Spawn s antizinem",
	cannot_enter_darkzone_inventory = "~r~Nemuzes vstoupit do darkzony pokud máš neco v inventari.",
	you_are_not_in_a_squad = "~r~Nejsi v žádné squade.",
	already_in_a_crew = "Už jsi v nejake crew.",

	poll11_q1 = "Meli bychom opravit rychlé prebijeni homingu/rpg (glitch)?",
	poll11_q2 = "Meli bychom banovat/opravit deluxo trick (stání na deluxu a strileni z nej)?",
	loot_crate_christmas = "Christmas Loot Crate",

	christmas_quest_x_completed = "~r~Vanocni ukol za den #%s splnen.",
	open_the_gift_menu = "otevreni menu s dárky",
	too_high_level_gift = "~r~Pouze novacci mohou brát dárky, tvuj level je prilis vysoký.",
	already_withdraw_gift_recently = "~r~Za posledních 15 minut už sis dárek vzal.",
	thank_you_for_gifting_x = "Díky za darování ~g~%sx %s~w~.",
	cannot_donate_junk = "~r~Nemuzes darovat levné/junk veci.",
	item_not_unique = "~r~Tuto položku nemuzes prodat, není unikátní.",
	marketplace_minimum_price_x_is_x = "Minimální prodejní cena za ^01x %s^7 je ^0$%s^7.",

	drop_from_the_plane = "vyskoceni z letadla",
	component_suppressor = "Tlumic",
	component_clip_01 = "Lehký zásobník",
	component_clip_02 = "Stredni zásobník",
	component_clip_03 = "Tezky zásobník",
	component_flashlight = "Baterka",
	component_barrel = "Hlaven",
	component_grip = "Rukojet",
	component_rail = "Lišta",
	component_compensator = "Kompenzátor",
	component_scope_small = "Malý zamerovac",
	component_scope_medium = "Stredni zamerovac",
	component_scope_large_fixed_zoom = "Velký zamerovac",
	component_scope_thermal = "Zamerovac s termovizí",
	component_scope_nv = "Zamerovac s nocni vizí",

	light_kevlar = "Lehký kevlar",
	medium_kevlar = "Policejní kevlar",
	heavy_kevlar = "Armádní kevlar",
	light_helmet = "Lehká helma",
	medium_helmet = "Policejní helma",
	heavy_helmet = "Armádní helma",
	light_bag = "Malý batoh",
	medium_bag = "Stredni batoh",
	heavy_bag = "Velký batoh",

	armor_plate = "Plát armoru",
	fixing_armor = "Nasazování plátu",
	bandage_g2 = "Bandáž",
	medkit_g2  ="Medkit",

	game_start = "Hra zacina za",
	waiting_x_players_to_start = "Cekame alespon na %s hracu pro zacatek hry.",
	game_starting_in_x = "Hra zacina za ~r~%s sekund~w~.",
	game_in_progress = "Hra již probíhá. %s hracu bojuje.",
	zone_closing_in = "Zona se uzavírá za",
	zone_closed_in = "Zona uzavrena za",
	x_joined_the_lobby = "~b~%s~w~ se pripojil do lobby.",
	choose_a_gamemode = "Vyber herniho rezimu",

	loading_account = "Nacitani uctu",
	loading_user = "Nacitani uzivatele",
	loading_game_data = "Nacitani herních dat",
	loading_clothes = "Nacitani obleceni",
	loading_crew = "Nacitani crew",

	["aircraft-carrier"] = "Aircraft carrier",
	["car-dealer"] = "Car dealer",
	["cayo"] = "Cayo Perico",
	["construction-site"] = "Construction site",
	["docks"] = "South docks",
	["docks2"] = "Private docks",
	["el-burro"] = "El burro height",
	["fairground"] = "Fairground",
	["families"] = "Families",
	["golf-field"] = "Golf field",
	["grape-seed"] = "Grape seed",
	["groove-street"] = "Grove Street",
	["hippie-camp"] = "Hippie Camp",
	["hollywood"] = "Hollywood",
	["killhouse"] = "Killhouse",
	["kortz"] = "Kortz",
	["labs"] = "Humane Labs",
	["lost-territory"] = "Lost territory",
	["madrazo"] = "Fuenta Blanca",
	["military-base"] = "Military Base",
	["mining-site"] = "Mining site",
	["mirror-park"] = "Mirror Park",
	["oil-field"] = "Oil field",
	["oil-station"] = "Oil station",
	["oneil-land"] = "Oneil land",
	["paleto-big"] = "Paleto city",
	["paleto-city"] = "Paleto city",
	["planeyard"] = "Plane yard",
	["playboy"] = "Playboy Mansion",
	["police-department"] = "Police department",
	["quarry"] = "Quarry",
	["race-site"] = "Racing site",
	["rockford-mansions"] = "Rockford mansions",
	["sandy-motel"] = "Sandy motel",
	["sandy-shore"] = "Sandy Shore",
	["sawmill"] = "Sawmill",
	["transport-station"] = "Transport station",
	["trash"] = "Junkyard",
	["unicorn"] = "Unicorn",
	["university"] = "University",
	["vagos-playa"] = "Vespucci beach",
	["vagos"] = "Vagos",
	["vespucci-canals"] = "Vespucci canals",

	vote_removed_x = "Hlas odstranen pro ~r~%s~w~.",
	vote_added_x = "Hlas pridan pro ~g~%s~w~.",

	armor_full = "~b~Plný armor.",
	spawning_vehicle = "Spawnování auta",
	opening_chest = "Otevírání skladu",
	cannot_loot_greenzone_public_world = "~r~Nemuzes lootit zombíky v greenzone.\n~w~Bez za teleportérem a jdi do private sveta.",
	leaving_private_world = "Opousteni private sveta",

	front_post_ls_3 = "Front post Los Santos 3",
	front_post_bc_3 = "Front post Blaine County 3",
	find_destination_press_x_to_select = "Vyber destinaci a klikni %s pro vybrání.",
	dungeon_check_secret_files = "Najdi tajné složky, kde jsou informace o puvodu viru.",
	secret_files = "Tajné složky",
	reading_files = "Procitani slozek",
	dungeon_press_read_files = "Zmackni ~INPUT_CONTEXT~ pro precteni tajných složek.",
	dungeon_reach_fib = "Navštiv FIB budovu a zjisti odkud pochází daný virus.",
	destination = "Destinace",
	dungeon_find_keycard_obj = "Najdi pristupovou kartu pro otevreni dveri v místnosti.",
	stop_action = "pro zastavení aktuální animace",
	crewperk_screen_bunker = "Obrazovka v bunkru",
	crewperk_crew_chest = "Spolecny crew sklad v bunkru",
	crewperk_lscustom_bunker = "LS Custom a prodejce vozidel v bunkru",
	crewperk_clothshop_bunker = "Obchod s oblecenim v bunkru",
	crewperk_weapon_bunker = "Obchodník se zbranemi v bunkru",
	crewperk_double_storage = "Zdvojnasobnene místo ve spolecnem crew skladu",
	crewperk_slots_increase_a = "Navyseni slotu crew o +2",
	crewperk_default_cloth = "Možnost nastavit výchozí outfit všem clenum",
	crewperk_map_blips = "Možnost videt ostatní cleny na mape",
	crewperk_speed_boost_bunker = "Speed boost pro všechny cleny v bunkru",
	crewperk_slots_increase_b = "Navyseni slotu crew o +3",
	crew_did_not_unlock_perk = "~r~Tvoje crew neodemkla toto vylepseni.",

	press_x_to_x = "Zmackni %s pro %s~w~.",
	seat_already_occupied = "~r~Toto místo je obsazeno.",
	leave_the_table = "opusteni stolu",
	dealer_hand = "Dealer",
	split_hand = "Split hand",
	hand = "Hand",
	stand = "Stand",
	hit = "Hit",
	double_down = "Double down",
	split = "Rozdelit",
	move_time = "Posunout cas",
	your_bet = "Tvoje sazka",
	bet = "prihoz",
	set_your_bet = "prihozeni svojí sázky",
	start_in = "Zacatek za",
	you_won_x_x = "Vyhrál jsi ~g~x%s %s~w~.",
	you_lost_your_bet = "~r~Prohrál jsi tvoji sázku.",
	invalid_bet = "~r~Nemuzes vsadit mene než $%s.",
	bet_limit = "~r~Nemuzes vsadit víc než $%s.",
	you_left_the_table = "~r~Odešel jsi od stolu",
	cannot_bet_casino_closed = "~r~Nemuzes vsadit, kasíno je zavreno",
	to_seat = "~b~místo",
	leave_game = "Odejít",
	change_view = "Zmenit pohled",
	validate_bet = "Poslat nabídku",
	move_chips = "Presunout žetony",
	manage_amount = "Upravit množství",
	chips = "Zetony",
	solo_game_disabled = "~r~Solo hry jsou vypnuté.",
	rider = "Rider",
	computer = "Computer",
	change_screen = "Change screen",
	you_need_to_be_in_casino = "~r~Musis být uvnitr kasína.",
	switch_to_table_view = "zmenit na pohled na stul",
	open_panel = "zpristupneni panelu",
	amount_to_trade = "Množství k obchodování",
	party_already_started = "~r~Hra již zacala.",
	game_no_participant = "~r~Nikdo jiný se neucastni, nemuzes zacit.",
	game_already_started = "~r~Hra již zacala.",
	party_not_started = "~r~Nestartnul jsi hru.",
	not_enough_participants = "~r~Není zde dostatek ucastniku.",
	you_lost = "~r~Prohrál jsi svou sázku!",
	max_participants_game_4casino = "~r~V této hre už je prilis moc ucastniku.",
	roulette_num_chips = "Cislo: ~b~%s\n~g~+$%s",
	roulette_num_lost = "Cislo: ~b~%s\n~r~Prohrál jsi.",
	casino_x_joined_game = "~g~%s~w~ se pripojil.",
	cannot_bet_now = "~r~Nemuzes ted vsazet, pockej.",
	spectators_cannot_bet = "~r~Divaci nemohou vsazet.",
	bet_validated_x = "Tvoje sázka ~g~$%s~w~ byla poslána. (%s)",

	join_br = "Pripojit na Battle Royale",
	new_game_starting_x_press_x_join_soon = "Nová hra brzy zacne, abys byl automaticky presunut do lobby pred zacatkem ~y~zmackni X~w~.",
	registered_teleported_before_start = "~b~Budeš presunut do lobby pred zacatkem hry.",
	lobby = "~y~Lobby",

	only_in_safezone_ui = "Tohle nemuzes udelat mimo ^0safezonu^7.",
	reached_max_sell_offer = "Nemuzes pridat víc než ^0%s aktivních nabídek^7.",
	not_enough_of_ui = "Nemáš dostatek ^0%s^7.",
	marketplace_create_sell_offer = "Vytvoril jsi nabídku ^0%sx %s ^7za ^0$%s^7 kus.",
	marketplace_offer_does_not_exist = "Tato ^0nabídka^7 neexistuje.",
	marketplace_create_buy_offer = "Vytvoril jsi žádost ke koupi ^0%sx %s ^7fza ^0$%s^7 kus.",
	full_for_item_ui = "Nemáš ^0dostatek místa^7 v inventari.",
	marketplace_received_money_sales = "Obdržel jsi ^0$%s^7 z ^0%s^7 nabídek.",
	marketplace_no_sales = "Zatím jsi ^0nic neprodal^7 na marketu.",
	marketplace_you_paid_for = "Zaplatil jsi ^0$%s^7 za ^0%s^7.",
	marketplace_you_received_x_x = "Obdržel jsi ^0%sx %s^7.",
	deleted_sell_offer = "^0Smazal jsi^7 svou nabídku.",
	deleted_buy_offer = "^0Smazal jsi^7 svou žádost ke koupi.",
	deleted_sell_offers = "^0Smazal jsi^7 svoje nabídky.",
	deleted_buy_offers = "^0Smazal jsi^7 svoje žádosti ke koupi.",
	no_enough_money_ui = "To si ^0nemuzes dovolit^7.",

	gpoints_shop = "Odmeny za GLife body",
	no_enough_glife_points = "~r~Nemáš dostatek GLife bodu.",
	you_paid_basket_gpoints = "Zaplatil jsi ~r~%s GLife bodu~w~ za svuj košík.",
	glife_points_balance_x = "GLife body: ~r~%s",

	bet_player_x_won_x = "~g~%s ~w~vyhrál ~g~$%s~w~.",
	bet_player_x_lost_x = "~r~%s ~w~prohrál ~r~$%s~w~.",

	cloth_warning_game_build = "~r~Hraješ na serveru, který ma starý build hry. Je možné, že nejake obleceni bude neviditelné.",
	back_accessory = "Extra položka prislusenstvi",
	armor_item = "Položka armoru",
	citizen_modified = "Hraješ s modifikovanými herními soubory. Zkontroluj si svoje soubory FiveM/GTA 5, že neobsahují takové soubory (modifikovaný citizen/jiné soubory)",
	grayzone_warning = "💀 ~r~Bud opatrný, všichni hraci jsou nepratele mimo safezony.",

	redzone_votemap = "Napiš ~r~/redzone_vote~w~ pro hlasování o další ~r~redzonu~w~.",
	darkzone_votemap = "~b~Darkzona~w~ se za chvíli otevírá, napiš ~b~/darkzone_vote~w~ pro hlasování o další ~b~mapu v darkzone~w~.",
	darkzone_open_press_context2 = "Zmackni ~INPUT_CONTEXT~ pro vstoupení ~m~do darkzony~w~.\nMod: ~r~%s",
	legacy_darkzone = "Hardcore Darkzone",
	classic_darkzone = "Casual Darkzone",
	darkzone_exit_allowed2 = "~r~Byly vám pristaveny auta pro utek, pokud chceš opustit darkzonu, utíkej.",
	max_slots = "Max sloty",
	crew_set_favorite_cloth = "Nastavit oblíbený outfit",
	crew_reset_favorite_cloth = "Resetovat oblíbený outfit",
	crew_favorite_cloth_desc = "Nastaví tvuj outfit jako výchozí outfit pro všechny cleny crew i se stejným modelem peda.",
	crew_favorite_cloth_deleted = "~r~Odstranil jsi výchozí outfit pro ostatní cleny",
	crew_favorite_cloth_added = "~r~Pridal jsi svuj outfit jako výchozí pro ostatní cleny",

	top_gungame = "Top Gungame",
	top_ffa = "Top FFA",

	poll12_q1 = "Chtel bys pridat M60 zpátky do hry?",
	poll12_q2 = "Chtel bys odstranit metu s 200hp + bandáže a vrátit kevlary?",
	poll12_q3 = "Chtel bys odstranit cooldown když spawnuješ auto?",

	-- League
	player_x_league_left = "~b~%s~w~ se odpojil.",
	player_x_league_join = "~b~%s~w~ se pripojil.",
	ctf_summary = "Hraci jsou rozdeleni do ruznych tymu, všechny týmy mají vlajku na jejich spawnu. Cílem je prinest zpet co nejvyšší množství nepratelskych vlajek na svoji základnu. Tým s nejvetsim poctem vlajek na konci hry vyhrává.",
	ctf_title = "Capture The Flag",
	green_team = "Zelený tým",
	blue_team = "Modrý tým",
	red_team = "Cerveny tým",
	yellow_team = "Žlutý tým",
	team_menu = "Týmy",
	view_team = "Zobrazit tým",
	ready = "Pripraven",
	ready_desc = "Budeš pripraven a hra zacne možná rychleji.",
	join_team = "Pripojit tým",
	join_team_desc = "Opustíš svuj momentální tým a pripojis se do jiného.",
	leave_team = "Opustit tým",
	leave_team_desc = "Opustíš svuj momentální tým.",
	already_ready_desc = "~g~Seš už pripraven hrát.",
	take_flag = "Vzal jsi vlajku",
	deliver_flag = "Donesl jsi vlajku",
	kill_carrier_flag = "Zabil jsi týpka s vlajkou",
	kill_player = "Zabil jsi hrace",
	capture_other_team_flag = "Zajisti vlajku nepratelskeho týmu a prines ji zpátky.",
	kill_carrier_flag_stolen = "Naše vlajka byla ukradena, zabij ~r~%s~w~ a prines ji zpátky!",
	escrot_carrier_flag_to_base = "Vzali jsme nepratelskou vlajku, ochranuj ~g~%s~w~ na ceste zpátky.",
	you_bring_back_flag_to_base = "Máš nepratelskou vlajku, odnes ji k nám!",
	you_bring_back_our_flag_to_base = "Máš naši vlajku, prines ji zpátky k nám!",
	escrot_carrier_our_flag_to_base = "Máme zpátky naši vlajku, ochranuj ~g~%s~w~ na ceste zpátky.",
	time_elapsed = "Uplynulý cas",

	squad_invite = "Byl jsi pozván do squady.",
	squad = "Squad",

	crew_invite = "Byl jsi pozván do crew.",
	crew = "Crew",

	trade_invite = "Byl jsi pozván k obchodování.",
	trade = "Obchodování",

	league_lobby_invite = "Byl jsi pozván do lobby ligy.",
	league_party = "Lobby ligy",
	league_random_mode_summary = "Náhodný mod bude vybrán až se odstartuje hra.",
	league_random_mode_title = "Náhodný mod",
	league_ban_mode_summary = "Všechny týmy budou moci banovat herní mod, jakmile bude hra startovat. Jakmile všechny týmy zabanují urcity pocet modu, bude vybrán náhodný režim.",
	league_ban_mode_title = "Náhodný mod / Banování o mod",
	league_random_map = "Náhodná mapa",
	league_ban_map = "Banování o mape / Náhodná mapa",
	spectator = "Divák",
	hardpoint_summary = "Hraci jsou rozdeleni do ruznych tymu, na mape se zobrazí zona. Cílem je ovládat co nejdéle danou zonu. Vyhrává tým s nejvyšším poctem bodu.",
	hardpoint_title = "Hardpoint",
	domination_summary = "Hraci jsou rozdeleni do ruznych tymu, na mape je nekolik vlajek. Cílem je ovládat co nejvyšší možný pocet vlajek a získat co nejvíc bodu. Tým, který bude mít dostatek bodu, vitezi.",
	domination_title = "Domination",
	open_party_settings = "otevreni nastavení party",
	league_players_not_ready = "Všichni hraci musí být pripraveni ke hre, aby hra mohla odstartovat.",
	league_kicked_from_party = "Byl jsi vyhozen z party.",
	league_no_longer_owner = "Už nejsi vlastníkem této party.",
	league_party_full = "Soukromá party ligy je plná.",
	league_now_owner = "Momentalne ses stal vlastníkem této party.",
	league_party_deleted = "Soukromá party byla smazána.",
	redzone_dm_kill_enemy = "Zabij co nejvíc hracu v zone.",
	redzone_dm_get_in_zone = "Jed do zony a zabij co nejvíc hracu.",

	redzone_deathmatch_title = "Redzone Deathmatch",
	redzone_deathmatch_summary = "Hraci jsou rozdeleni do ruznych tymu, na mape se zobrazí redzona. Cílem je zabít co nejvíc hracu v zone. Tým s nejvyšším poctem killu vitezi.",

	manage_kits = "Spravovat svoje kity",
	too_far_spawn_area = "~r~Jsi daleko od spawnu, abys otevrel tohle menu.",
	league_mode_changed = "~b~Herní mod této lobby byl zmenen.",
	edit_spawning_kit = "pro upravení svého kitu po spawnutí",
	duration_2m = "2 minuty",
	duration_3m = "3 minuty",
	duration_4m = "4 minuty",
	duration_5m = "5 minut",
	duration_6m = "6 minut",
	duration_10m = "10 minut",
	duration_15m = "15 minut",
	duration_30m = "30 minut",

	poll14_q1 = "Meli bychom nechat nový hitreg systém? Momentalne takhle funguje damage a registrace hitu."
}

AddLanguage("cs", my_language)
