local my_language = {
	give_vehicle = "Pridal sis ~b~%s~w~ do inventare.",
	store_vehicle_command = "Schovat vozidlo, ktere ridis",
	no_entity_vehicle = "~r~Toto vozidlo neexistuje nebo je prilis daleko od tebe.",
	no_entity_vehicle_id = "~r~Toto vozidlo nema zadne ID, nemuzes ho schovat.",
	store_vehicle = "~b~Schoval sis vozidlo.",
	teleported_former_position = "~g~Byl jsi teleportovan na tvou posledni ulozenou pozici.",
	not_enough_of = "~r~Nemas dostatek %s.",
	max_storage_chest = "~r~Mas plny sklad.",
	cant_carry_more_items = "~r~Do tveho inventare se nic nevleze (je plny).",
	put_item = "Vlozil jsi ~g~x%s~w~ %s~w~.",
	take_item = "Vzal jsi ~g~x%s~w~ %s~w~.",
	delete_item = "Odstranil jsi ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Beres si ~g~%s~w~.",
	bind_weapon_command = "Zkratka na slot pro zbrane %s",
	kevlar_broke = "~r~AHH!~n~~w~Tvuj armor se rozbil.",
	inventory_command = "Otevrit inventar",
	press_enter_to_join = "Zmackni ~g~ENTER~w~ pro start hry.",
	new_character = "Nova postava",
	survivor = "Prezivsi",
	right = "Vpravo",
	left = "Vlevo",
	male = "Muz",
	female = "Zena",
	ped = "Ped",
	name = "Jmeno",
	sex = "Pohlavi",
	title = "Nadpis",
	select_this_character = "Vybrat tuto postavu",
	no_entity_zombie = "Zombik neexistuje nebo je prilis daleko od tebe.",
	you_found = "Nasel jsi ~g~%sx %s~w~.",
	you_found_nothing = "Nenasel jsi ~g~nic~w~.",
	press_e_to_loot = "Zmackni ~b~[E]~w~ k lootovani",
	full_for_item = "~r~Pro tuto vec nemas dostatek mista.",
	put_item_container = "Vlozil jsi ~g~x%s~w~ %s~w~ do skladu.",
	take_item_container = "Vzal jsi ~g~x%s~w~ %s~w~ ze skladu.",
	not_allowed_here = "~r~Zde to nemuzes udelat.",
	cant_store_moving_veh = "~r~Nemuzes uschovat vozidlo, pokud je v pohybu.",
	use_repair_tool = "pouzij repair tool",
	please_get_closer = "~b~Prosim bez bliz, v blizkosti nikdo/nic neni.",
	you_cancel_action = "~r~Prerusil jsi akci.",
	selected_target_message = "Vybrany cil:~n~%s~n~~r~Zmackni ~b~Y~r~ pro ukonceni~n~~r~Zmackni ~g~X~r~ pro pokracovani.",
	target_you = "~b~TY",
	target_screen = "~g~Zobrazeno",
	take_this_path = "jit touto cestou",

	-- hud
	default_hud = "Defaultni HUD",
	cinema_hud = "Cinema HUD",
	no_hud = "Zadny HUD",

	-- perms
	kick_member = "Vyhazovat cleny",
	edit_member = "Upravovat cleny",
	edit_rank = "Upravovat hodnosti",
	create_rank = "Vytvaret hodnosti",
	delete_rank = "Mazat hodnosti",
	edit_structure = "Upravit informace o crew",
	edit_permissions = "Upravit pravomoce",
	permission_level = "Pravomoce udeleny",
	red_delete = "Smazat",
	rank = "Hodnost",
	red_kick = "Vyhodit",
	crew_name = "Jmeno crew",
	slogan = "Slogan",
	information = "informace",
	boss_rank = "Boss rank name",
	member_rank = "Newbie rank name",
	member = "Clen",

	permissions_manager = "spravce pravomoci",
	members_manager = "spravce clenu",
	ranks_manager = "spravce hodnosti",
	ranks_list = "seznam hodnosti",
	members_list = "seznam clenu",
	create_a_rank = "vytvorit hodnost",
	invite_someone = "pozvat nekoho",
	stats = "Statistiky",
	total_ranks = "Pocet hodnosti",
	total_members = "Pocet clenu",
	level = "Level",
	actions = "akce",
	crew_manager = "spravce crew",
	you_created_a_new_crew = "Vytvoril jsi novou crew: %s",
	you_deleted_your_crew = "Smazal jsi svou crew.",
	you_are_not_in_a_crew = "Nejsi v zadne crew",
	you_joined_the_crew = "Pripojil ses do crew '%s'",
	kick_failed = "Neuspesne jsi vyhodil hrace, duvod: %s",
	already_in_crew = "Uz jsi v nejake crew.",
	no_invitation = "Neobdrzel jsi zadnou pozvanku.",
	left_crew = "Opustil jsi crew.",
	permission_updated = "Pravomoce <C>~g~%s</C>~w~ byly aktualizovany.",
	incorrect_name = "~r~Format jmena je nespravny",
	incorrect_rank_perm = "~r~Chyba\n~w~Nazev hodnosti nebo uroven hodnosti je neplatna.",
	warn_rank_limit = "~r~Prekrocil jsi limit hodnosti.",
	create_rank_success = "~g~Uspesne\n~w~jsi vytvoril novou hodnost <C>~b~%s</C>~w~ s pravomocemi <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Nemuzes spravovat hrace, ktery ma vyssi pravomoce nez ty.",
	you_sent_an_invitation = "Odeslal jsi pozvanku hraci <C>~g~%s</C>~w~ do tvoji crew.",
	you_received_an_invitation = "Obdrzel jsi pozvanku do crew.\n~b~/%s pro prijmuti.",
	invitation_expired = "Pozvanka vyprsela",
	crew_kick_success = "Vyhodil jsi <C>~b~%s</C>~w~ z tvoji crew.",
	first_rank_warning = "Prvni hodnost je 'defaultni' hodnost.",

	you_updated_this = "Aktualizoval jsi %s na ~g~<C>%s</C>~w~.",
	changes_saved_on = "Zmeny provedeny na <C>~g~%s</C>~w~ byly ulozeny.",
	yes = "ano",
	no = "ne",
	none = "Zadny",
	character_id = "Character ID",
	server_id = "Server ID",
	report = "Nahlasit",
	rename = "Prejmenovat",
	trade_with = "Obchodovat",
	
	please_wait_x_before = "~r~Prosim pockej %s sekund predtim, nez to udelas.",

	-- cloth
	take_outfit = "Koupit tento outfit",
	wardrobe_options = "moznosti satniku",
	wardrobe = "satnik",
	manual_options = "manualni nastaveni",
	manual_mode = "manualni vyber obleceni",
	save_outfit = "Ulozit tento outfit",
	variation = "variace",
	outfits = "outfity",
	cloth_shop = "Obchod s oblecenim",
	ped_cloth_shop = "Vyber peda",
	manual_props = "manualni doplnky",
	manuel = "Manualni",
	new_name = "Nove jmeno",
	outfit_name = "Jmeno outfitu",
	variations_saved = "~g~Uspesne~n~~w~sis vybral nove obleceni.",
	equipped_new_outfit = "Oblekl sis novy outfit: ~b~%s",
	warning_limit_outfits = "Prekrocil jsi limit ulozenych outfitu. ~g~(%s)",
	saved_new_outfit = "Ulozil sis novy outfit: ~b~%s~w~.",
	rename_outfit = "Tvuj outfit ~b~%s~w~ byl prejmenovan na ~g~%s~w~.",
	delete_outfit = "Tvuj outfit: ~b~%s~w~ byl odstranen.",

	torso = "Trup",
	props = "Doplnky",
	top = "Vrsek",
	tops = "Vrsek",
	badge = "Nasivky",
	pants = "Kalhoty",
	pant = "Kalhoty",
	shoes = "Boty",
	bags = "Batohy",
	undershirt = "Tricko",
	neck = "Retezy",
	bracelets = "Naramky",
	montres = "Hodinky",
	earrings = "Nausnice",
	glasses = "Bryle",
	hats = "Cepice",
	graphiques = "Design",

	-- health
	inconscious = "V bezvedomi",
	doing_something = "Neco delas",
	time_before_respawn = "Cas pred respawnem",
	you_died = "~r~Zemrel jsi.",
	healing_wounds = "Uzdravovani ran",
	already_doing_something = "~r~Jiz neco delas.",
	you_have_been_healed = "~g~Byl jsi uzdraven.",
	you_respawned = "~g~Respawnul ses.",

	player_too_far_to_interact = "~r~Hrac se kterym chces provadet interakci je prilis daleko.",
	send_trade_invitation_to = "Poslal jsi nabidku k obchodu hraci ~b~%s~w~.\n~b~Pockej az hrac, kteremu jsi nabidku poslal, nabidku prijme.",
	receive_invitation_from = "Dostal jsi nabidku k obchodu od ~b~%s~w~.\n~b~Napis ~w~/trade accept %s~b~ pro prijmuti nabidky.",

	invalid_command_args = "Neplatne argumenty prikazu: %s",
	start_trade_command_help = "Obchodovat s dalsim hracem",
	accept_trade_command_help = "Prijmout nabidku",
	deny_trade_command_help = "Odmitnout nabidku",
	invalid_invitation = "Tato nabidka je neplatna nebo jiz neexistuje",
	name_accepted_your_trade_invitation = "~b~%s~w~ prijal tvou nabidku",
	you_accepted_trade_invitation_of_name = "Prijal jsi nabidku od %s",
	name_denied_your_trade_invitation = "~b~%s~w~ odmitl tvou nabidku",
	you_denied_trade_invitation_of_name = "Odmitl jsi obchod od %s",
	you_already_trading = "Jsi zaneprazdneny",
	other_already_trading = "Hrac se kterym chces obchodovat jiz s nekym obchoduje",

	other_player_not_enough_money = "~r~Obchod nebyl uspesny. Hrac se kterym obchodujes nema dostatek penez.",
	you_player_not_enough_money = "~r~Obchod nebyl uspesny. Nemas dostatek penez.",
	other_player_not_enough_item = "~r~Obchod nebyl uspesny. Hrac se kterym jsi obchodoval nemel dostatek nejakeho predmetu.",
	you_player_not_enough_item = "~r~Obchod nebyl uspesny. Nemel jsi dostatek nejakeho predmetu.",
	success_trade = "~g~Obchod byl uspesny.",
	fail_trade_other_player = "~r~Obchod nebyl uspesny, hrac se kterym obchodujes odesel.",
	trade_other_full_item = "~r~Obchod nebyl uspesny, hrac se kterym obchodujes nema dostatek mista.",
	trade_full_for_item = "~r~Obchod nebyl uspesny, nemas dostatek mista.",

	press_e_to_loot_inv = "Zmackni ~INPUT_CONTEXT~ pro otevreni lootu.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Zmackni ~INPUT_CONTEXT~ pro interakci s ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "Zmackni ~INPUT_CONTEXT~ pro ~b~%s~w~.",
	press_e_to_open_catalog = "Zmackni ~b~E~w~ pro precteni ~g~katalogu~w~.",
	this_person = "touto osobou",
	the_shop = "tohoto obchodu",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Tohle nemuzes udelat.",

	no_weapon = "~r~Nemas vytazenou zadnou zbran.",
	no_need_ammo = "~r~Do teto zbrane nepotrebujes nabijet zadne naboje.",
	not_right_ammo = "~r~Pouzivas spatne naboje, potrebujes ~b~%s~w~.",
	you_used_ammo = "Nabil jsi ~b~%s~w~ s ~b~x%s~w~ typu ~b~%s~w~.",

	choose_a_destination = "vyber ~b~destinace",
	open_your_chest = "otevreni tveho skladu",
	no_enough_money = "~r~Na to nemas penize.",
	you_paid = "Zaplatil jsi ~g~$%s~w~ za ~b~%s~w~.",
	you_paid_basket = "Zaplatil jsi ~g~$%s~w~ za tvuj kosik.",
	you_sell_basket = "Obdrzel jsi ~g~$%s~w~ za prodej ~b~x%s~w~ polozek.",

	you_repaired_your_vehicle = "~g~Opravil jsi sve vozidlo.",
	repairing_your_vehicle = "Opravujes vozidlo",
	wheels_are_fine = "~r~Kola vozidla jsou v pohode.",
	changing_wheel = "Vymena kol",
	you_repaired_the_wheels = "~g~Opravil jsi kola tveho vozidla.",

	front_post_ls = "Front Post Los Santos",
	front_post_ls_2 = "Front Post Los Santos 2",
	front_post_bc = "Front Post Blaine County",
	front_post_bc_2 = "Front Post Blaine County 2",
	main_post_ls = "Safe City Los Santos",
	main_post_bc = "Safe City Blaine County",
	random_zone = "Random zona (seskok padakem)",

	this_item_is_equipped = "~r~Tuto vec mas vytazenou, dej ji pryc z dolni listy.",
	only_in_safezone = "~r~Tohle nemuzes udelat mimo safezonu.",
	-- Commerce
	feature_gold_only = "Tato funkce je pouze pro ~y~hrace s Gold roli~w~.",
	feature_diamond_only = "Tato funkce je pouze pro ~b~hrace s Diamond roli~w~.",
	you_turned_into = "Promenil ses v ~g~%s~w~.",
	wait_between_transformation = "~r~Prosim pockej chvili predtim, nez se budes chtit v neco promenit znovu.",
	wait_between = "~r~Prosim pockej chvili predtim, nez to zkusis znovu.",
	available_morphs = "Dostupne promeny",
	animal_models = "Modely zvirat",
	zombie_models = "Modely zombiku",
	success_update_name = "Zmenil jsi svoje jmeno na ~b~%s~w~.",
	success_reset_stats = "~g~Uspesne sis vyresetoval svoje staty. (Tabulka se aktualizuje pozdeji)",

	-- animals
	boar = "Boar",
	cat = "Cat",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Cow",
	coyote = "Coyote",
	deer = "Deer",
	hen = "Hen",
	husky = "Husky",
	mtlion = "Lion",
	pig = "Pig",
	poodle = "Poodle",
	pug = "Pug",
	rabbit = "Rabbit",
	rat = "Rat",
	retriever = "Retriever",
	shepherd = "Shepherd",
	westy = "Westy",

	player_id = "ID hrace",
	bounty = "Odmena",
	reason = "Duvod",
	id_player_not_found = "~r~Zadny hrac nebyl nalezen s timto ID.",

	ammo_dealer = "Obchodnik s naboji",
	misc_dealer = "Obchodnik s dalsim vybavenim",
	veh_dealer = "Obchodnik s vozidly",
	custom_dealer = "LS Custom",
	gun_dealer = "Obchodnik se zbranemi",

	bounty_created = "Zaplatil jsi ~g~$%s~w~ za vypsani odmeny na ~b~%s~w~.",
	contract_success = "Odmenu, kterou jsi vypsal na ~r~%s~w~ byla odeslana ~b~%s~w~.",
	a_contract_on_your_head = "~r~Byla na tebe vypsana odmena. Ten, kdo te zabil dostal odmenu.",
	reward_for_contract = "Lovec odmen! Dostal jsi odmenu ~g~$%s~w~ za zabiti ~b~%s~w~.",

	hey_can_help_you = "Cus, jak ti muzu pomoct?",
	i_want_to_buy_items = "Chci si neco koupit",
	i_want_to_sell_items = "Chci neco prodat",

	press_context_or_jump_to_get_up = "Zmackni ~INPUT_CONTEXT~ nebo ~INPUT_JUMP~ pro ~b~zvednuti se~w~.",
	server_restart_warning = "Server se bude za chvili restartovat..",
	auto_restart_in = "Automaticky restart probehne za %s sekund.",

	not_allowed_create_character = "Nemuzes si vytvorit novou postavu.",
	character_not_yours = "Tato postava neni tvoje.",
	character_does_not_exist = "Tato postava jiz neexistuje.",
	loading_character = "Nacitani tvoji postavy",

	playtime_is = "~b~Odehrany cas na Extinction:\n~w~%s",
	dont_spam = "^1Nespamuj!",

	babygod_warning = "~b~Opustil jsi safezonu, chvili budes nesmrtelny.",

	-- LS Custom
	modifications_classiques = "Klasicke modifikace",
	modifications_custom = "Specialni modifikace",
	modifications_benny = "Benny's modifikace",
	paint = "barva",
	custom_your_car = "Vytun svoje auto",
	wheels_modifications = "Kola",
	performances = "Vykon",
	neons = "Neony",
	extra = "Extra",
	klaxon = "Horn",
	teinte_fenetre = "Windows tint",
	phares_xenons = "Xenon headlights",
	modele_plaque = "Plate model",
	livery = "Livery",
	headlight_color = "Headlights color",
	wheel_type = "Wheel type",
	primary_wheel_type = "Primary wheel type",
	back_wheel_type = "Back wheel type",
	wheel_color = "Wheel color",
	tire_smoke = "Tire smoke",
	custom_color = "Custom color",
	custom_wheel = "Custom wheel",
	custom_back_wheel = "Custom back wheel",
	suspension = "Suspension",
	transmission = "Transmission",
	moteur = "Engine",
	frein = "Brake",
	turbo = "Turbo",
	primary_color = "Primary color",
	secondary_color = "Secondary color",
	interior_color = "Interior color",
	dashboard_color = "Dashboard color",
	color_effect = "Color effect",
	left_neon = "Left neon",
	right_neon = "Right neon",
	front_neon = "Front neon",
	back_neon = "Back neon",

	aileron = "Spoiler",
	pc_front = "Front bumper",
	pc_back = "Rear bumper",
	carroserie = "Side skirt",
	exhaust = "Exhaust",
	cadre = "Frame",
	calandre = "Grille",
	capot = "Hood",
	gb_left = "Left fender",
	gb_right = "Right fender",
	roof = "Roof",
	plate_support = "Plate holders",
	front_plate = "Front plate",
	interior_style = "Interior style",
	figurine = "Figurine",
	motif_dashboard = "Dashboard style",
	cadran = "Dial design",
	haut_parleur_portes = "Speaker doors",
	motif_sieges = "Seat style",
	volant = "Steering wheel",
	levier = "Shifter leavers",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Speaker back doors",
	hydrolique = "Hydraulics",
	moteur = "Engine",
	filtres_air = "Air filter",
	entretoises = "Spacers",
	arc_couverture = "Arch",
	antenne = "Antenna",
	motif_exterieur = "Exterior style",
	reservoir = "Tank",
	window = "Window",
	style = "Style",
	default = "Default",
	type = "Type",
	normal = "Normal",
	black = "Black",
	black_smoke = "Black smoke",
	simple_smoke = "Simple smoke",
	stock = "Stock",
	limo = "Limousine",
	sa_black = "San Andreas black",
	sa_blue = "San Andreas blue",
	sa_white = "San Andreas white",
	simple_white = "Simple white",
	ny_white = "North Yankton white",
	race = "Race",
	sport = "Sport",
	stock = "Stock",
	street = "Street",
	discount = "Sleva",
	select_your_car = "Vyber svoje auto",
	select_car_custom = "Vyber vozidlo, ktere chces vytunit. Cislo mezi sipkama je cislo vozidla, pokud jich mas v inventari vice.",
	loading_vehicle = "Spawnovani vozidla",
	invalid_vehicle = "~r~Nespravne vozidlo.",
	invalid_vehicle_please_spawn = "~r~Nespravne vozidlo. Prosim spawni svoje auto alespon jednou predtim, nez ho budes modifikovat.",
	free_take_and_validate = "Vsechno je zdarma. Vyber si co chces a potvrd svuj vyber!",
	car_custom_saved = "~g~Modifikace tveho vozidla byly ulozeny.",

	-- Character creation
	character_creation = "Vytvoreni postavy",
	confirm = "",
	start_playing = "Hrat",
	appearance = "vzhled",
	character_list = "seznam postav",
	face_features = "rysy obliceje",
	parents = "rodice",
	parent = "rodic",
	mix = "mix",
	skin = "kuze",
	desc_mix = "Vyber jestli je tvuj oblicej vice podobny na otce/matku.",
	desc_skin = "Vyber jestli je barva kuze vice ovlivnena otcem/matkou.",
	identity = "identita",
	player_name = "jmeno hrace",
	new_character = "nova postava",
	warning_headblend = "~r~Nevybral sis rodice tve postavy.",
	warning_overlays = "~r~Nevybral sis vlasy, oboci nebo vousy.",
	warning_identity = "~r~Varovani.~n~~w~Zapomnel jsi vyplnit tabulku o identite.",

	-- kits
	kit_does_not_exist = "~r~Tento kit neexistuje.",
	kit_needs_rank = "Nemas ~r~%s~w~ roli.",
	wait_before_using_kit = "Prosim pockej ~r~%s~w~ pred obdrzenim tohoto kitu.",
	received_kit = "Obdrzel jsi kit ~b~%s~w~.",
	no_kit = "Nemas zadny kit.",

	unable_to_find_booster = "Nebylo mozne najit zadny booster s timto ID.",
	wait_already_player_boost = "Prosim pockej chvili nez pouzijes tento booster. Tento booster je jiz aktivni.",
	wait_already_crew_boost = "Prosim pockej chvili nez pouzijes tento booster. Crew booster je jiz aktivni.",
	wait_already_server_boost = "Prosim pockej chvili nez pouzijes tento booster. Server booster je jiz aktivni.",
	booster_activated = "Booster aktivovan na ~g~%s minut~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ aktivoval server booster na ~g~%s minut~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ aktivoval crew booster na ~g~%s minut~z~! ~b~XP +%s%%",
	no_booster = "Nemas zadny booster.",

	rank_expired = "~r~Tvoje role vyprsela.",
	supporter_role = "~g~Role:~w~ <C>%s</C>",
	no_rank_warning = "Nemas zadnou roli.\n~r~Pokud sis neco zakoupil, musis si linknout svuj FiveM ucet.",
	no_fivem_id = "Nemas linknuty FiveM ucet.\n~r~Zkontroluj, ze mas FiveM ucet linknuty s hrou.",
	no_queue_warning = "Nemas zadny balicek v rade.\n~r~Zkus chvili pockat nebo napsat /getRank pokud jsi nedostal svou roli.",
	package_sync_success = "~g~Tvuj nakup byl synchronizovany, uzivej!\n~w~Uzitecne prikazy: /getRank, /booster",

	level_required = "Musis byt level %s.",
	rank_required = "Musis mit alespon hodnost %s.",
	level_required_2 = "~r~Musis byt level %s.",

	updated_deathmessage = "~g~Aktualizoval jsi svou zpravu po smrti.",
	updated_deatheffect = "~g~Aktualizoval jsi svuj efekt pri zabiti.",
	use = "Pouzit",
	test = "Test",

	-- zombie
	you_bitten = "~r~Byl jsi nakazen.",
	infection_rate = "Mira infekce: ~r~%s%%",

	-- ranks
	thug = "Thug",
	hustler = "Hustler",
	soldier = "Soldier",
	trigger = "Trigger",
	enforcer = "Enforcer",
	facilitator = "Facilitator",
	public_enemy = "Public Enemy",
	shot_caller = "Shot Caller",
	street_boss = "Street Boss",
	kingpin = "Kingpin",
	-- Tattoo
	tattoo = "tetovani",
	tattoos = "tetovani",
	torso = "trup",
	head = "hlava",
	left_arm = "leva ruka",
	right_arm = "prava ruka",
	left_leg = "leva noha",
	right_leg = "prava noha",
	unknown = "nezname",
	other = "ostatni",
	remove_tattoo = "Odstranit vsechna tetovani",
	-- Hairdress
	haircuts = "Ucesy",
	makeup = "Makeup",
	face = "Oblicej",
	eyebrows = "Oboci",
	facial_hair = "Vousy",
	body_hair = "Chlupy na tele",
	barber_shop = "Holicstvi",
	face_makeup = "Makeup",
	lipstick = "Rtenka",
	face_foundation = "Oblicejovy zaklad",
	skin_blemishes = "Kozni vady",
	skin_ageing = "Stari",
	moles_freckles = "Pihy",
	sun_damage = "Poskozeni kuze",
	skin_complexion = "Pokozka",
	body_blemishes = "Telesne vady",
	body_blemishes_2 = "Telesne vady 2",
	opacity = "Alpha",
	variations = "Variace",
	filter = "Filtr",
	eyes_color = "Barva oci",
	-- Mask
	masks = "Masky",
	-- Items
	money = "Penize",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	rocket = "Rocket",
	flare = "Flare",
	grenade = "Grenade Ammo",
	-- Food
	["fish_1"] = "Largemouth Bass",
	["fish_2"] = "Rainbow Trout",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Arctic Grayling",
	["fish_5"] = "Rock Bass",
	["fish_6"] = "Smallmouth Bass",
	["fish_7"] = "Paddlefish",
	["fish_8"] = "Bull Trout",
	["fish_9"] = "Lake Trout",
	["fish_10"] = "Chinook",
	["fish_11"] = "Pallid Sturgeon",
	["fish_12"] = "Salmon",

	misc_meat = "Raw meat",
	rabbit_meat = "Raw rabbit",
	lion_meat = "Raw lion",
	rare_plume = "Rare feather",
	dog_meat = "Raw dog",
	cat_meat = "Raw cat",
	rare_fish = "Rare fish",

	mask = "Mask",
	malette = "Suitcase",
	malette_metal = "Metal suitcase",
	ciseaux = "Scissors",
	clean_kit = "Clean kit",
	fishing_rod = "Fishing rod",
	meuble = "Furniture",
	tissu = "Cloth",
	accessory = "Accessory",
	radio = "Radio",
	recyclor = "Recycler",
	medkit = "Medkit",
	kevlar = "Kevlar",
	gps = "GPS",
	repair_tool = "Repair kit",
	jvn = "JVN",
	engine_veh = "Engine",
	bag = "Sac",
	wheel_veh = "Wheel",
	vetement = "Top",
	bloc_note = "Notepad",
	paint_spray = "Paint spray",
	spike = "Spike strip",
	paracetamol = "Paracetamol",
	bandage = "Bandage",
	gaz_mask = "Gaz mask",
	filter = "Filtr",
	tattoo_tool = "Tattoo tool",
	drug_med = "Drug",
	drug_antizin = "Antizin shot",
	drug_stamina = "Stamina shot",
	drug_berserker = "Health shot",

	pickup_spikestrip = "sebrani zastavovaciho pasu",
	you_dropped_spikestrip = "Polozil jsi ~g~zastavovaci pas~w~.",
	you_pickup_spikestrip = "Sebral jsi ~g~zastavovaci pas~w~.",

	you_have_been_killed_by = "Zabil te ~r~%s",
	kill_notif = "~m~Zabit",
	you_killed = "Zabil jsi ~r~%s~w~",
	already_used_reset_only = "~r~Uz sis resetoval svou postavu.\n~w~Pouze %s~w~ clenove mohou resetovat svou postavu vicekrat nez jednou.",
	already_used_reset_only2 = "~r~Tohle jsi uz udelal.\n~w~Pouze %s~w~ clenove to mohou pouzit vicekrat.",

	hud_options = "Nastaveni HUD",
	advanced_hud = "Zobrazit pokrocily HUD",
	players = "Hraci",
	health = "Zdravi",
	player_menu = "Menu hrace",

	you_are_now_zombie = "~r~Nyni jsi zombik.",

	my_weapons = "moje zbrane",
	customize_weapons = "modifikace zbrane",
	weapon_skin = "Odstin",

	-- camo
	skin_classic = "Defaultni",
	skin_green = "Zelena",
	skin_yellow = "Zluta",
	skin_pink = "Ruzova",
	skin_gold = "Zlata",
	skin_blue = "Modra",
	skin_orange = "Oranzova",

	weapon_katana = "Katana",
	weapon_sledgehammer = "Sledge Hammer",

	-- new
	airdrop_coming = "~r~Blizi se airdrop, podivej se na mapu.",
	killed_by_cheater = "~r~Byl jsi zabit cheaterem.\n~w~Zabanovali jsme ho a tvoje smrt byla vyresetovana.",

	corrupted_vehicle = "~r~Toto vozidlo je poskozene a v minulosti bylo duplikovane, proto bylo odstraneno z inventare. Omlouvame se, pokud te nekdo okradl.",

	-- Discord
	join_discord_for_kit = "Pripoj se na nas Discord pro ziskani kitu!\n~g~discord.gg/gtalife",
	discord_account_not_linked = "~r~Musis si linknout svuj Discord ucet s FiveM.",
	discord_account_not_guild = "~r~Nejsi na nasem Discord serveru.\n~w~Pripoj se discord.gg/gtalife",

	already_done_recently = "~r~Zkus to znovu pozdeji, v posledni dobe jsi to jiz provedl.",
	update_country = "Zmenit zemi",

	prestige_info = "~b~Dosahl jsi maximalniho levelu.\n~w~Napis /prestige pro ziskani informaci o systemu prestizi.",
	prestige_not_max_level = "~r~Nedosahl jsi nejvyssiho mozneho levelu.",
	max_prestige_reached = "~r~Dosahl jsi posledni prestize.",
	prestige_info_cmd = [[^3System prestizi^7
Prave mas prestiz ^4%s^7 a level ^5%s^7.

Pokud dosahnes maximalniho levelu (%s) muzes si zvolit prestiz a restartovat svuj level na level 0.
Ziskanim nove prestize dostanes specialni odznak a body, kterymi si muzes napriklad zvetsit velikost inventare.
^2Pokud si chces dat prestiz a VRATIT se na level 0, napis ^1/setprestige^2
]],
	new_prestige = "Odemkl jsi novou prestiz!\n~g~Nyni mas %s prestizi",
	cant_store_event_veh = "~r~Nemuzes uschovat legendarni vozidla.",

	you_are_no_longer_in_combat = " ~b~Uz nejsi v combatu.",
	you_are_in_combat_mode = " ~b~Jsi v combatu.\nPokud se odpojis, zemres.",
	you_disconnected_in_combat = " Odpojil ses v combatu, zemrel jsi.",

	not_enough_prestige_points = "~r~Nemas dostatek bodu na prestiz.",
	you_reached_max_prestige_stats_rank = "~r~Ziskal jsi nejvyssi moznou uroven pro tuto prestiz.",
	new_prestige_stats_upgrade = "Vylepsil jsi svuj ~b~%s~w~\n~g~%s/%s",

	legendary_vehicle_pop = "~r~Legendarni vozidlo se objevilo nekde na mape.",

	-- poll one
	poll1_q1 = "Jaky server bys rad videl?",

	poll1_q1_a1 = "Battle Royale",
	poll1_q1_a2 = "Private missions solo nebo s 1-4 kamarady (neco jako Payday/heisty/Hitman)",
	poll1_q1_a3 = "Race / Freeroam",
	poll1_q1_a4 = "Murder / Horror game",

	-- poll two
	poll2_q1 = "Mluvis anglicky a mel bys zajem o RP server?",

	poll2_q1_a1 = "Ne",
	poll2_q1_a2 = "Ano",

	combat_mode_container_disabled = "~r~Jsi v combatu.\n~w~Nemuzes uschovavat veci.",
	gcoins_wallet_updated = "~g~Tvoje penezenka s GCoiny se aktualizovala.\n~w~+%s GCoinu",
	not_enough_gcoins = "~r~Nemas dostatek GCoinu.",
	gcoins_something_went_wrong = "~r~Neco se nepovedlo.",
	you_bought_with_gcoins = "Koupil sis ~g~%s~w~ za ~b~%s GCoinu~w~.",

	equiping_armor = "Nasazovani armoru",

	toggle_mute_player = "Mutnout hrace",
	you_muted_this_player = "~b~Mutnul sis tohoto hrace.",
	you_unmuted_this_player = "~b~Odmutnul sis tohoto hrace.",

	already_purchased = "~r~Tento predmet uz jsi koupil.",
	weapon_camo_preview = "Prave se divas na nahled modelu, nektere komponenty chybi.\n~INPUT_CELLPHONE_CANCEL~ pro opusteni nahledu.",

	already_using_a_seringue_booster = "~r~Tohle sis uz pichnul.",
	seringue_effect_done = "~b~Efekt antizin shotu skoncil.",
	you_injected_a_seringue_boost = "Pichnul sis ~b~antizin shot~w~ do krve.",

	put_item_permission = "Vlozit veci",
	take_item_permission = "Vzit veci",
	put_money_permission = "Vlozit penize",
	take_money_permission = "Vzit penize",

	preferred_badge_set = "Nastavil jsi svuj ~g~preferovany odznak~w~.",
	preferred_badge_not_set = "~r~Nemuzes si nastavit svuj preferovany odznak.",

	marketplace_received_money_sales = "Ziskal jsi ~g~$%s~w~ z ~b~%s~w~ nabidek.",
	marketplace_no_sales = "~r~Nic jsi neprodal.",
	marketplace_you_paid_for = "Zaplatil jsi ~g~$%s~w~ za ~b~%s~w~.",

	deleted_sell_offer = "~b~Smazal jsi svou nabidku.",
	deleted_buy_offer = "~b~Smazal jsi svou nabidku.",
	deleted_sell_offers = "~b~Smazal jsi svoje nabidky.",
	deleted_buy_offers = "~b~Smazal jsi svoje nabidky.",

	marketplace_offer_does_not_exist = "~r~Tato nabidka neexistuje.",

	marketplace_create_sell_offer = "Vytvoril jsi nabikdu ~b~%sx %s ~w~za ~g~$%s~w~ za jeden predmet.",
	marketplace_create_buy_offer = "Vytvoril jsi nabidku ~b~%sx %s ~w~za ~g~$%s~w~ za jeden predmet.",

	i_want_to_enter_in_my_property = "Chci do bunkru.",
	i_want_to_exit_private_world = "Chci do verejneho sveta.",
	public_world = "Verejny svet",
	private_world = "Vlastni svet",

	dailymission_playerkill = "Zabito hracu",
	dailymission_zombiekill = "Zabito zombiku",
	dailymission_playerheadshotkill = "Zabito hracu headshotem",
	dailymission_zombieheadshotkill = "Zabito zombiku headshotem",
	dailymission_zombiesurvivorkill = "Zabito survivor zombiku",
	dailymission_zombiearmoredkill = "Zabito armored zombiku",
	dailymission_zombiehazmatkill = "Zabito hazmat zombiku",
	dailymission_zoombieboomerkill = "Zabito boomer zombiku",
	dailymission_sellitems = "Prodanych veci",
	dailymission_buyitems = "Koupenych veci",
	dailymission_lootitems = "Nalootenych veci",
	dailymission_createselloffer = "Vytvoreno nabidek",
	dailymission_killtopkillcrew = "Zabito hracu z crew",
	dailymission_killtopkillplayers = "Zabito hracu",
	dailymission_getintolegendaryvehicle = "Vozidel",
	dailymission_killzombiewithweapon = "Zabito zombiku se zbrani",
	dailymission_killplayerwithweapon = "Zabito hracu se zbrani",
	dailymission_darkzonesurvivingtime = "Prezito v darkzone",
	dailymission_redzoneplayerkill = "Killu hracu v redzone",
	dailymission_redzonezombiekill = "Killu zombiku v redzone",
	dailymission_darkzoneplayerkill = "Killu hracu v darkzone",
	dailymission_darkzonezombiekill = "Killu zombiku v darkzone",
	dailymission_useitem = "Pouzito veci",
	dailymission_playtime = "Odehrany cas",
	dailymission_xpharvest = "Ziskano XP",
	dailymission_sellofferpurchased = "Nabidek prodano",
	dailymission_sellofferpurchasedbyme = "Nabidek nakoupeno",
	dailymission_tradeitems = "Predmetu vytradovano",
	dailymission_createbuyoffer = "Nabidek vytvoreno",

	dailymission_completed = "~g~Splnil jsi denni ukol!\n~b~+%s XP\n~y~+1 Dungeon klic",

	character_creation_mix_desc = "Vyber jestli je tvuj oblicej vice podobny na otce/matku.",
	character_creation_skin_desc = "Vyber jestli je barva kuze vice ovlivnena otcem/matkou.",

	ff_1 = "Sirka nosu",
	ff_2 = "Vyska nosu",
	ff_3 = "Delka nosu",
	ff_4 = "Pokles nosu",
	ff_5 = "Pokles spicky nosu",
	ff_6 = "Zakrouceni nosu",
	ff_7 = "Vyska oboci",
	ff_8 = "Hloubka oboci",
	ff_9 = "Vyska licnich kosti",
	ff_10 = "Sirka licni kosti",
	ff_11 = "Sirka lic",
	ff_12 = "Otevreni oci",
	ff_13 = "Tloustka rtu",
	ff_14 = "Sirka celisti",
	ff_15 = "Delka zadni celisti",
	ff_16 = "Snizeni brady",
	ff_17 = "Delka brady",
	ff_18 = "Sirka brady",
	ff_19 = "Rozstep brady",
	ff_20 = "Tloustka krku",

	airdrop_taken_by = "^1%s vzal %s z airdropu.",

	available_death_effects = "Dostupne efekty pri zabiti",
	available_modes = "Dostupne mody",

	you_changed_your_ped_model = "~g~Uspesne jsi zmenil svuj ped.",
	i_want_to_change_my_ped = "Chci si zmenit peda",

	poll4_q1 = "Co ocekavas od dalsi sezony?",
	poll4_q1_a4 = "Nove eventy jako airdropy, zabirani zon atd.",
	poll4_q1_a1 = "Vice PvE moznosti jako napriklad dungeony",
	poll4_q1_a2 = "Vice her jako napriklad kasino/zavody",
	poll4_q1_a3 = "Vice PvP moznosti",

	poll4_q2 = "Chtel bys mit vice turnaju/ranked zapasu?",
	poll4_q2_a1 = "Ano",
	poll4_q2_a2 = "Ne",

	poll4_q3 = "Chtel bys sniperky v obchode?",
	poll4_q3_a1 = "Ano",
	poll4_q3_a2 = "Ne",

	poll4_q4 = "Co si nejvic uzivas na Extinction?",
	poll4_q4_a1 = "PvP",
	poll4_q4_a2 = "PvE",
	poll4_q4_a3 = "Obchodovani",

	dungeon_no_more_time = "~r~Byl jsi prilis pomaly. Dungeon se uzavrel.",
	dungeon_participant_left = "~r~%s opustil dungeon.",
	started_dungeon_party = "~b~Vytvoril jsi dungeon.",
	dungeon_party_no_longer_exists = "~r~Tato dungeon parta jiz neexistuje.",
	dungeon_invitation_expired = "~r~Tato pozvanka vyprsela.",
	dungeon_join_party = "~g~Pripojil ses do dungeon party.",
	dungeon_too_late_for_invitation = "~r~Prijal jsi pozvanku prilis pozde. Nemuzes se pripojit do probihajiciho dungeonu.",
	dungeon_already_invited_this_player = "~r~Tohoto hrace uz jsi pozval.",
	dungeon_invitation_received = "Ziskal jsi pozvanku od ~b~%s~w~ do jeho dungeon party.\nNapis ~g~/dungeon join %s~w~ pro pripojeni se.",
	dungeon_invitation_sent = "Pozval jsi ~g~%s~w~ do tvoji dungeon party.",

	i_want_to_enter_a_dungeon = "Chci navstivit dungeon",
	dungeon_list = "Seznam dungeonu",
	dungeon = "Dungeon",
	dungeons = "Dungeony",
	you_need_x_keys = "Potrebujes ~y~%s dungeon klicu~w~ pro vstup do dungeonu.",
	time_remaining = "Zbyvajici cas",
	you_killed_the_dungeon_boss = "~r~Zabil jsi dungeon bosse.",
	dungeon_kill_final_boss = "Jsi v posledni mistnosti. Zabij bosse, abys ziskal jeho poklad.",

	dungeon_died_remaining = "Umrel jsi, mas ~r~%s~w~ zbyvajicich zivotu.",
	dungeon_died = "~r~Uz nemas zadne zbyvajici zivoty. Zemrel jsi.",
	dungeon_already_in_party = "~r~Uz jsi v dungeon party.\n~w~Napis /dungeon quit pro opusteni.",
	dungeon_does_not_exist = "~r~Tento dungeon neexistuje.",
	dungeon_ready = "~g~%s~w~ je pripraven.",
	dungeon_not_ready = "~r~%s~w~ neni pripraven.",

	not_released_yet = "Toto jeste neni vydano.",
	feature_only_supporters = "~b~Tato funkce je teprve v bete a pouze hraci s ranky Gold/Diamond ji mohou pouzivat.",
	feature_not_enabled = "~b~Tato funkce neni jeste zapnuta na tomto serveru.",
	dungeon_charid_required = "~r~Prosim zadej character ID tveho kamarada (nachazi se na obrazovce vpravo nahore).\nPriklad: /dungeon invite 1234",

	poll5_q1 = "Mel bys problem pokud by nas anticheat vyscreenoval obrazovku cheatera, pokud by byl podezrely, ze pouziva wallhack/aimbot? (je mozne, ze to ukaze cast plochy, pokud mas hru v okne, ale tyto screeny nejsou ulozeny a jsou pristupne pouze pro moderatory)",
	poll5_q1_a1 = "preskocit - ignorovat",
	poll5_q1_a2 = "Ano, souhlasim s touto novou metodou",
	poll5_q1_a3 = "Ne, nesouhlasim",
	
	-- S4
	redzone_kill_leader_killed = "~r~Kill leader v redzone~w~ byl zabit.",
	redzone_kill_leader_fled = "~r~Kill leader v redzone~w~ utekl.",
	redzone_get_back_kill_leader_before_x = "Jsi ~r~mimo redzonu~w~ vrat se zpatky nebo ztratis status kill leadera za ~r~%s sekund~w~.",
	redzone_kill_leader_new_xp_step = "~r~Nasobitel XP v redzone\n~b~+%s%~w~ bonus",
	remaining_lives = "Zbyvajici zivoty",

	name_tag = "Crew tag",
	redzone_changed = "~r~Redzony se premistily na nove lokace.",

	-- Squad
	squad_not_leader = "~r~Nejsi leader tvoji squady.",
	squad_kicked_by_x = "Byl jsi ~r~vyhozen~w~ z tvoji squady hracem ~r~%s~w~.",
	squad_you_kicked_x = "Vyhodil jsi ~r~%s~w~ z tvoji squady.",
	squad_invited_x = "Pozval jsi ~r~%s~w~ do tvoji squady.",
	squad_invited_you_x = "~r~%s~w~ te pozval do jeho squady.\nNapis ~r~/squad join %s~w~ pro prijmuti pozvanky.",
	squad_you_set_new_leader = "Urcil jsi ~r~%s~w~ jako noveho ~r~leadera~w~ squady.",
	squad_you_are_new_leader = "~g~Nyni jsi novy leader squady.",
	squad_not_invited = "~r~Nebyl jsi pozvan do zadne squady.",
	squad_joined_squad = "~g~Pripojil ses do squadu.",
	squad_left = "~r~Opustil jsi squad.",
	squad_already_in = "~r~Uz jsi v nejake squade.",
	squad_created_x = "Vytvoril jsi novy squad. ~b~(%s)",
	squad_x_joined = "~b~%s~w~ se pripojil do squadu.",
	squad_leader_deleted = "~r~Leader smazal tento squad.",
	write_yes_to_confirm = "Napis yes pro potvrzeni",
	invite_a_player_write_char_id = "Pozvi hrace. Napis jeho character ID",

	-- Help stuff
	press_enter_beginner_guide = "Zmackni ~INPUT_ENTER~ pro zapnuti navodu pro novacky.",
	welcome_glife = "Vitej na ~g~GLife~w~!",
	you_are_playing_server_x_with_x = "Hrajes na serveru ~b~#%s~w~ s ~b~%s hraci~w~.",
	start_beginner_guide = "Zacit navod pro novacky",
	play_now = "~g~Hraj nyni!",
	interact_npc_fast_travel = "Promluv si s teleporterem",

	-- Tutorial
	tutorial_beginner_end_msg = "~r~Diky za tvuj cas!\n~w~Uzivej Extinction, pokud mas nejake otazky zeptej se v chatu nebo navstiv nas Discord.",
	tutorial_beginner_start_msg = "~r~Vitej na serveru GLife Extinction!\n~w~Timto kratkym navodem zjistis jak zde zacit.",
	tutorial_beginner_camera_01 = "~r~~BLIP_557~ ~r~Hlavni safezona\n~w~V teto zone muzes nakupovat a uschovavat svoje veci, ale take si zde muzes modifikovat svoji vybavu a obchodovat s ostatnimi hraci.",
	tutorial_beginner_camera_02 = "~BLIP_568~ ~r~Sklad\n~w~Tady muzes navstivit svuj sklad a uschovat si zde tvoje cenne veci.",
	tutorial_beginner_camera_03 = "~BLIP_567~~BLIP_556~~BLIP_658~ ~r~NPC obchodnici\n~w~Muzes nakupovat a prodavat svoje veci u obchodniku se zbranemi, autami nebo u obchodnika s ostatni vybavou.",
	tutorial_beginner_camera_04 = "~BLIP_84~ ~r~Verejne odmeny\n~w~Pokud se ti podari najit a zabit ciloveho hrace, dostanes urcitou odmenu.",
	tutorial_beginner_camera_05 = "~BLIP_176~ ~r~Nepratelsky svet\n~w~Potkas zombiky a ostatni hrace. Vsichni te budou chtit zabit, ale na druhou stranu jsou nejlepsim zpusobem, jak ziskat XP a loot.",
	tutorial_beginner_camera_06 = "~BLIP_303~ ~r~Redzony\n~w~Tady muzes mit lepsi loot a budes ziskavat vice zkusenosti za killy.",
	tutorial_beginner_camera_07 = "~BLIP_648~ ~r~Darkzona\n~w~Zde nemuzes uschovavat veci nebo utect tak jednoduse, ale je to nejlepsi misto, kde najit nejlepsi loot jako jsou MK2 zbrane nebo sniperky.",
	tutorial_beginner_camera_08 = "~BLIP_575~ ~r~Ostatni prilezitosti\n~w~Muzes bojovat o airdrop ale take muzes prozkoumat dungeon a na konci zabit bosse.",
	tutorial_beginner_training_01 = "~g~Pripojil ses do treninkove mistnosti.\n~w~Skoc pomoci ~INPUT_JUMP~ az budes pripraven.",
	tutorial_beginner_training_02 = "~g~Pouzij inventar.\n~w~Zmackni ~%s~ pro otevreni inventare.",
	tutorial_beginner_training_03 = "~g~Vem si zbran.\n~w~Otevri inventar a presun zbran do listy dole.\nZmackni urcitou klavesu ~b~1/2/3/4/5/6/7~w~.\n~r~Pokud nemas zadnou zbran, pouzij ~b~/kit newbie.",
	tutorial_beginner_training_04 = "~g~Nabij svoji zbran.\n~w~Vem si zbran a vloz naboje do listy dole, pak zmackni urcitou klavesu.",
	tutorial_beginner_training_05 = "~g~Konecne vozidla.\n~w~Ted muzes spawnovat auta stejne jako pouzivas naboje nebo zbrane. Jakmile spawnes auto, muzes ho schovat ~%s~ zatimco stojis na miste. Zmackni klavesu pro potvrzeni.",
	tutorial_beginner_training_success_01 = "~g~Dobra prace, nyni muzeme zacit!",
	tutorial_beginner_training_success_02 = "~g~Dobre, zvladl jsi to.\n~w~Proces je stejny pro vsechny predmety.",
	tutorial_beginner_training_success_03 = "~g~Dobre, zvladl jsi to.\n~w~Proces je stejny pro vsechny predmety.",
	tutorial_beginner_training_success_04 = "~g~Dobre, zvladl jsi to.\n~w~Nyni jsme hotovi.",

	-- Darkzone stuff
	contaminated = "kontaminovano",
	darkzone_boat_leaving_in = "Lode zmizi za",
	darkzone_exit = "Misto pro opusteni",
	purificator = "Purifikator",
	you_entered_the_darkzone = "~r~Vstoupil jsi do darkzony.\n~w~Momentalne je uvnitr ~b~%s hracu~w~.",
	you_left_the_darkzone = "~r~Opustil jsi darkzonu.",
	cannot_enter_darkzone_time = "~r~Darkzona jeste neni otevrena, cekej.",
	darkzone_is_full = "~r~Darkzona je plna, prosim cekej.",
	darkzone_exit_allowed = "~r~Lode jsou zde pro opusteni darkzony, utikej pokud chces opustit darkzonu.",
	darkzone_close_time = "Zavira se za",
	darkzone_surviving_since = "Prezivas",
	darkzone_points = "Bodu",
	darkzone_points_x = "~r~Darkzone bodu: ~w~+%s",
	darkzone_landing_in_x = "Darkzona se otevre za ~b~%s minut~w~.\nPokud bude dostatek hracu.",
	darkzone_open_press_context = "Zmackni ~INPUT_CONTEXT~ pro vstoupeni ~m~do darkzony~w~.",
	darkzone_outside_warning = "~r~Jsi mimo darkzonu, vrat se nebo umres.",
	darkzone_close_warning = "~r~Darkzona se brzy uzavre~w~.\nNemel bys zde zustavat prilis dlouho.",
	darkzone_close_damage = "Darkzona se uzavrela, cela oblast je nyni kontaminovana.",
	darkzone_not_enough_points_to_exit = "Potrebujes ~r~%sx bodu~w~ pro opusteni darkzony.",
	press_e_to_exit_the_darkzone = "Zmackni ~INPUT_CONTEXT~ pro opusteni darkzony.\n~r~Potrebujes x%s darkzone bodu.",
	use_purificator = "pouziti purifikatoru",
	darkzone_not_enough_points_to_start_purificator = "Potrebujes ~r~%sx bodu~w~ pro zapnuti purifikatoru.",
	darkzone_not_enough_points_to_refill_purificator = "Potrebujes ~r~%sx bodu~w~ pro doplneni purifikatoru.",
	darkzone_too_far_from_purificator = "~r~Jsi prilis daleko od purifikatoru.",
	darkzone_cant_remove_while_running_purificator = "~r~Nemuzes vybirat veci pokud je purifikator zapnuty.",
	darkzone_purificator_running = "~r~Nemuzes vkladat veci dovnitr pokud je purifikator zapnuty.",
	darkzone_purificator_running_refill = "~r~Nemuzes doplnit purifikator pokud je prave zapnuty.",
	darkzone_put_x_in_purificator = "Vlozil jsi ~r~%s~w~ do purifikatoru.",
	darkzone_you_took_x_from_purificator = "Vzal jsi ~r~%s~w~ z purifikatoru.",
	darkzone_purificator_does_not_need_refill = "Nepotrebujes ~r~doplnovat tento purifikator~w~.",
	darkzone_refilled_purificator_x = "Pouzil jsi ~r~x%s bodu~w~ pro doplneni purifikatoru.",
	darkzone_open = "Darkzona se otevrela.\n~r~Najdi transporter v jakekoliv safezone.",
	darkzone_item_clean = "Tato polozka uz je predelana.\n~r~Muzes vkladat pouze kontaminovane veci.",
	
	dungeon_cooldown_between = "Prosim pockej ~r~%s minut~w~ pred startem dalsiho dungeonu.",
	set_as_default = "Nastavit jako defaultni modifikaci pro tento model vozidla",
	car_custom_presets_saved = "Preset modifikaci pro ~g~%s~w~ byl ulozen.",
	marketplace_you_received_x_x = "Obdrzel jsi ~b~%sx ~g~%s~w~.",

	above_level_x_no_longer_possible_loot_safe = "Hraci nad level %s nemuzou lootovat zombiky v safezonach.",
	preferred_component_desc = "Tento set bude defaultni set pro vsechny %s zbrane, ktere budes drzet.",
	set_as_preferred_component_class = "Nastavit jako preferovany set komponentu",
	weapon_presets_updated = "Nastavil sis defaultni preset komponentu pro ~g~%s~w~.",

	-- New survey
	poll6_q1 = "Chtel bys snizit limit clenu v crew na 25? (vice konkurence, mensi skupinky)",
	poll6_q2 = "Mas v pohode ping na tvem main serveru? (je tvuj prumerny ping v pohode?)",
	poll6_q3 = "Hrajes v private worldu?",
	poll6_q4 = "Mel by byt zaply headshot damage pro sezonu 4?",
	
	casino_dungeon_desc = "[?] ~r~Budes potrebovat baterku na zbran, abys tam dobre videl.",
	dungeon_destroy_wall_obj = "Znic zed, ktera ti blokuje cestu.",
	dungeon_use_key_obj = "Pouzij klic k otevreni dveri.",
	dungeon_kill_zombies_obj = "Zabij vsechny zombiky.",
	dungeon_kill_zombies_obj_x = "~b~Zabij vsechny zombiky.~w~\n%s/%s hracu zabilo vsechny zombiky.",
	dungeon_use_key_to_open_door = "Pouzij klic pro otevreni dveri.",
	dungeon_find_key_obj = "Najdi klic, kterym otevres dvere.",
	take_key = "ziskani klice",
	open_the_door = "otevreni dveri",
	dungeon_quit_notif = "Napis ~g~/dungeon quit~w~ pro opusteni dungeonu.",
	dungeon_generator_obj = "Najdi generator a obnov elektrinu.",
	dungeon_press_generator = "Zmackni ~INPUT_CONTEXT~ pro zapnuti generatoru.",
	power_generator = "Generator elektricke energie",
	dungeon_find_c4_obj = "Nekde tu je schovana C4, najdi ji.",
	dungeon_use_c4_obj = "Pouzij C4 k odpaleni trezoru.",
	dungeon_party_help = "Napis ~b~\"/dungeon\"~w~ pro spravu tohoto dungeonu.",
	press_x_to = "Zmackni %s pro %s",

	quest_clean_zone = "Zabij zombiky v zone: %s",
	quest_clean_zone_desc = "Prijed do zony %s a zabijej zde zombiky.",

	loot_crate_light = "Light Loot Crate",
	loot_crate_medium = "Medium Loot Crate",
	loot_crate_high = "High Loot Crate",
	
	dailymission_killzombieinzoneid = "Zombiku zabito v zone",
	dailymission_dungeonbosskilled = "Dungeon boss zabit",

	quest_too_far_npc = "~r~Jsi prilis daleko od NPC s ukoly.",
	quest_already_started_quest = "~r~Tento ukol uz plnis.",
	quest_redo_in_x = "~r~Tento ukol uz jsi splnil.\n~w~Budes se moct pokusit ho splnit znovu po uplynuti ~b~%s",
	quest_max_quests_reached = "~r~Muzes prijmout pouze %s ukoly.",
	quest_new_accepted = "~g~Prijmul jsi novy ukol.",
	quest_gave_up = "~r~Vzdal ses tohoto ukolu.",
	quest_not_completed = "~r~Musis splnit vsechny casti tohoto ukolu.",
	quest_already_completed = "~r~Tento ukol uz jsi splnil.",
	quest_all_completed = "~g~Uspesne jsi splnil vsechny casti.",
	dungeon_key = "Dungeon klic",
	darkzone_cannot_enter_min_levels = "Musis byt level ~b~%s~w~ abys mohl vstoupit do darkzony.",
	darkzone_you_survived_x = "Prezil jsi ~r~%s minut~w~ v darkzone.",
	questmenu_command = "Otevrit menu s ukoly",
	squadmenu_command = "Otevrit squad menu",
	airdrop_coming_darkzone = "~r~V darkzone budou airdropy, podivej se na mapu.",
	darkzone_full_crew = "V darkzone je ~r~%s members~w~ z tvoji crew, pockej az nekdo opusti darkzonu.",

	crew_join_cooldown_x = "Musis pockat ~r~%s~w~ nez se budes moct pripojit do teto crew.",
	darkzone_not_enough_players_darkzone = "Darkzona se neotevre.\n~r~Neni dostatek hracu.",

	dungeon_loot_boss_box = "~g~Bedna se objevila uprostred mistnosti.",
	drug_antizin_bar = "Efekt Antizin shotu",
	drug_stamina_bar = "Efekt Stamina shotu",
	drug_berserker_bar = "Efekt Health shotu",

	squad_members_limit = "~r~Tvoje squad prekrocila limit clenu.",
	darkzone_only = "~r~Musis byt v darkzone.",
	darkzone_no_cars = "~r~V darkzone muzes pouzivat pouze motorky, lode a ostatni vozidla, ktere mohou letat.",

	poll7_q1 = "Mel bys zajem o evropsky server pouze pro hrani solo?",
	poll7_q2 = "Chtel bys opet dropovat AWP MK2/Marksman Rifle MK2 i z dropu?",

	you_have_been_muted = "~r~Byl jsi umlcen.~w~\nVyprseni: ~b~%s~w~\nDuvod: ~b~%s",
	you_have_been_unmuted = "~g~Byl jsi odmlcen.",
	muted_x = "Umlcel jsi ~g~%s~w~.~w~\nVyprseni: ~b~%s~w~\nDuvod: ~b~%s",
	unmuted_x = "Odmlcel jsi ~g~%s~w~.",
	invalid_duration = "~r~Nespravna delka, prosim zadej spravny cas.",
	player_already_muted = "~r~Tento hrac uz je umlceny.",
	player_not_muted = "~r~Tento hrac neni umlceny.",
	you_are_muted = "~r~Jsi umlceny.",

	open_mailbox = "otevreni schranky",
	you_entered_crew_pro = "~g~Vstoupil jsi do crew bunkru.",

	you_player_not_enough_gcoin = "~r~Nemas dostatek GCoinu.",
	other_player_not_enough_gcoin = "~r~Hrac se kterym obchodujes nema dostatek GCoinu.",
	a_player_no_fivem_account_linked = "~r~Hrac se kterym obchodujes nema linknuty svuj FiveM ucet.",
	you_no_fivem_account_linked = "~r~Abys mohl tradovat GCoiny, musis linknout svuj FiveM ucet.",
	trade_gcoin_for_gcoin_not_allowed = "~r~Nemuzes tradovat GCoiny za GCoiny.",
	cannot_delete_this_item = "~r~Nemuzes vymazat tuto polozku.",
	impossible_on_solo_server = "~r~Tohle nemuzes delat na solo serveru.",

	warning_message = "Hrajes na SOLO serveru Extinction. Neni zde povoleno teamovat s ostatnimi hraci, vytvaret squady/spojenectvi. Pokud budes prichycen pri teamovani, budes zabanovan z tohoto serveru a docasne i z celeho GLifu. Prosim respektuj pravidla a hraj solo.",
	bank_no_money = "~r~Nemas zadne penize.",
	bank_deposit_x = "Vlozil jsi ~g~$%s~w~ do banky.",
	cannot_deposit_money_go_bank = "~r~Promin, zde nemuzes vlozit penize do banky.\n~w~Bez za opici u banky.",
	bank_balance_x = "Zustatek v bance: ~g~$%s",
	store_money_bank = "~g~vlozeni penez do banky",
	wait_before_next_action = "Pockej ~r~%sms~w~ nez budes manipulovat s touto polozkou.",
	bank = "Banka",

	poll8_q1 = "Chtel bys nahradit server 2 (solo server) serverem pouze pro dua?",
	poll8_q2 = "Mas rad banan?",

	reset_radar_tips = "Pokud chces resetovat i radar, je pro to jine nastaveni.",
	redzone_shop = "Redzone obchod",
	no_enough_redzone_points = "~r~Nemas dostatek redzone bodu.",
	you_paid_basket_rp = "Zaplatil jsi ~r~%s RP~w~ za tvuj kosik.",

	redzone_points_balance_x = "Redzone body: ~r~%s",
	top_kills = "Nejvice killu",
	top_zombies = "Nejvice zombiku",

	not_allowed_in_this_zone = "~r~Tohle nemuzes delat v teto zone.",
	darkzone_disabled_for_update = "~r~Darkzony jsou momentalne vypnute, budou zpatky s dalsimi updaty.",
	loot_crate_halloween = "Halloween Loot Crate",

	new_weapon = "Nova zbran",
	winner_title = "Vitez",
	left_gungame_party = "~r~Opustil jsi lobby Gun Game.",
	outfit_gta = "GTA Outfity",

	poll10_q1 = "Kde si myslis, ze by mel byt zaply siphon mod?",
	poll_10_q1 = "Pouze v redzone",
	poll_10_q2 = "Vsude",

	open_lobby_menu = "otevrit lobby menu",
	choose_game_lobby = "Vyber lobby",

	joined_lobby_x = "~g~Pripojil ses do lobby %s.~w~\nHerni rezim: ~b~%s",
	gun_game = "Gun Game",
	spawn = "Spawn",
	return_lobby_help = "Pokud se chces vratit do hlavni lobby, napis ~b~/lobby.",
	afk_press_key = "AFK?~r~~n~Zmackni klavesu.",
	sorry_it_is_ok = "~r~Promin!\n~w~Ted je to v pohode.",
	swimming_respawn_help = "~r~Vypada to, ze jsi ve vode.\n~w~Zmackni ~INPUT_CONTEXT~ pro respawn.",

	only_darkzone_item = "~r~Tento predmet muzes pouzit pouze v darkzone.",
	cant_get_darkzone_loadout = "~r~Nemuzes dostat tvoji vybavu do darkzony.\n~w~%s",
	press_e_to_exit_the_darkzone2 = "Zmackni ~INPUT_CONTEXT~ pro opusteni darkzony.",
	not_driving_vehicle = "~r~Neridis vozidlo.",
	not_enough_airdrop_points = "~r~Tvoje crew/squad nema dostatek bodu na to, aby mohla otevrit airdrop.",
	airdrop_points = "Airdrop body",

	warning_message_duo = "Hrajes na DUO serveru Extinction. Neni zde povoleno teamovat s vice jak jednim hracem. Pokud budes prichycen pri teamovani, budes zabanovan z tohoto serveru a docasne i z celeho GLifu. Prosim respektuj pravidla a hraj solo. Pokud budes prichycen pri teamovani s vice jak jednim hracem, budes zabanovan z tohoto serveru a docasne i z celeho GLifu. Prosim respektuj pravidla a hraj solo.",
	combat_mode_cannot_do_that = "~r~Jsi v combatu.\n~w~Tohle nemuzes delat.",
	open_darkzone_shop = "otevreni darkzone obchodu",
	dzone_flare_airdrop = "Svetlice airdropu",
	paid_x_points_for_x = "Zaplatil jsi ~r~%s~w~ bodu za ~r~%s~w~.",
	starter_pack_upgrade_1 = "Upgrade starter packu",
	extraction_package = "Vysadkovy balicek",
	always_spawn_antizin = "Spawn s antizinem",
	cannot_enter_darkzone_inventory = "~r~Nemuzes vstoupit do darkzony pokud mas neco v inventari.",
	you_are_not_in_a_squad = "~r~Nejsi v zadne squade.",
	already_in_a_crew = "Uz jsi v nejake crew.",
	
	poll11_q1 = "Meli bychom opravit rychle prebijeni homingu/rpg (glitch)?",
	poll11_q2 = "Meli bychom banovat/opravit deluxo trick (stani na deluxu a strileni z nej)?",
	loot_crate_christmas = "Christmas Loot Crate",

	christmas_quest_x_completed = "~r~Vanocni ukol za den #%s splnen.",
	open_the_gift_menu = "otevreni menu s darky",
	too_high_level_gift = "~r~Pouze novacci mohou brat darky, tvuj level je prilis vysoky.",
	already_withdraw_gift_recently = "~r~Za poslednich 15 minut uz sis darek vzal.",
	thank_you_for_gifting_x = "Diky za darovani ~g~%sx %s~w~.",
	cannot_donate_junk = "~r~Nemuzes darovat levne/junk veci.",
	item_not_unique = "~r~Nemuzes prodat tuto polozku, jelikoz je duplikovana.",
	marketplace_minimum_price_x_is_x = "Minimalni cena za ~r~1x %s~w~ je ~r~$%s~w~.",

	drop_from_the_plane = "skok z letadla",
	component_suppressor = "Tlumic",
	component_clip_01 = "Maly zasobnik",
	component_clip_02 = "Stredni zasobnik",
	component_clip_03 = "Velky zasobnik",
	component_flashlight = "Baterka",
	component_barrel = "Hlaven",
	component_grip = "Rukojet",
	component_rail = "Lista",
	component_compensator = "Kompenzator",
	component_scope_small = "Maly puskohled",
	component_scope_medium = "Stredni puskohled",
	component_scope_large_fixed_zoom = "Velky puskohled",
	component_scope_thermal = "Puskohled s termovizi",
	component_scope_nv = "Puskohled s nocnim videnim",

	light_kevlar = "Policejni vesta",
	medium_kevlar = "Vojenska vesta",
	heavy_kevlar = "Vesta pro specialni jednotky",
	light_helmet = "Motorkarska helma",
	medium_helmet = "Vojenska helma",
	heavy_helmet = "Helma pro specialni jednotky",
	light_bag = "Maly batoh",
	medium_bag = "Stredni batoh",
	heavy_bag = "Velky batoh",

	armor_plate = "Plat do vesty",
	fixing_armor = "Nasazovani platu",
	bandage_g2 = "Bandaz",
	medkit_g2  ="Medkit",

	game_start = "Hra zacina v",
	waiting_x_players_to_start = "Pro start hry je potreba alespon %s hracu.",
	game_starting_in_x = "Hra zacina za %s sekund",
	game_in_progress = "Hra prave probiha. Preziva %s hracu.",
	zone_closing_in = "Zona se bude uzavirat v",
	zone_closed_in = "Zona bude uzavrena v",
	x_joined_the_lobby = "~b~%s~w~ se pripojil do lobby.",
	choose_a_gamemode = "Vyber si herni mod",

	loading_account = "Nacitani uctu",
	loading_user = "Nacitani uzivatele",
	loading_game_data = "Nacitani hernich dat",
	loading_clothes = "Nacitani obleceni",
	loading_crew = "Nacitani crew",

	["aircraft-carrier"] = "Aircraft carrier",
	["car-dealer"] = "Car dealer",
	["cayo"] = "Cayo Perico",
	["construction-site"] = "Construction site",
	["docks"] = "South docks",
	["docks2"] = "Private docks",
	["el-burro"] = "El burro height",
	["fairground"] = "Fairground",
	["families"] = "Families",
	["golf-field"] = "Golf field",
	["grape-seed"] = "Grape seed",
	["groove-street"] = "Groove Street",
	["hippie-camp"] = "Hippie Camp",
	["hollywood"] = "Hollywood",
	["killhouse"] = "Killhouse",
	["kortz"] = "Kortz",
	["labs"] = "Humane Labs",
	["lost-territory"] = "Lost territory",
	["madrazo"] = "Fuenta Blanca",
	["military-base"] = "Military Base",
	["mining-site"] = "Mining site",
	["mirror-park"] = "Mirror Park",
	["oil-field"] = "Oil field",
	["oil-station"] = "Oil station",
	["oneil-land"] = "Oneil land",
	["paleto-big"] = "Paleto city",
	["paleto-city"] = "Paleto city",
	["planeyard"] = "Plane yard",
	["playboy"] = "Playboy Mansion",
	["police-department"] = "Police department",
	["quarry"] = "Quarry",
	["race-site"] = "Racing site",
	["rockford-mansions"] = "Rockford mansions",
	["sandy-motel"] = "Sandy motel",
	["sandy-shore"] = "Sandy Shore",
	["sawmill"] = "Sawmill",
	["transport-station"] = "Transport station",
	["trash"] = "Junkyard",
	["unicorn"] = "Unicorn",
	["university"] = "University",
	["vagos-playa"] = "Vespucci beach",
	["vagos"] = "Vagos",
	["vespucci-canals"] = "Vespucci canals",

	vote_removed_x = "Hlasovani pro ~r~%s~w~ odstraneno.",
	vote_added_x = "Hlasovani pridano pro ~g~%s~w~.",

	armor_full = "~b~Plny armor.",
	spawning_vehicle = "Spawnovani auta",
	opening_chest = "Otevirani bedny",
	cannot_loot_greenzone_public_world = "~r~Nemuzes lootit zombiky v safe zone.\n~w~Musis jit do vlastniho sveta.",
	leaving_private_world = "Odchazis z vlastniho sveta",

	front_post_ls_3 = "Front post Los Santos 3",
	front_post_bc_3 = "Front post Blaine County 3",
	find_destination_press_x_to_select = "Najdi destinaci a zmackni %s pro vybrani.",
	dungeon_check_secret_files = "Najdi tajne soubory pro zjisteni informaci o puvodu viru.",
	secret_files = "Tajne soubory",
	reading_files = "Cteni souboru",
	dungeon_press_read_files = "Zmackni ~INPUT_CONTEXT~ pro precteni tajnych souboru.",
	dungeon_reach_fib = "Pro zjisteni puvodu viru musis jit do FIB budovy.",
	destination = "Destinace",
	dungeon_find_keycard_obj = "Najdi kartu, ktera slouzi k otevreni dveri v mistnosti.",
	stop_action = "zruseni prave probihajici akce",
	crewperk_screen_bunker = "Obrazovka v bunkru",
	crewperk_crew_chest = "Spolecna crew bedna v bunkru",
	crewperk_lscustom_bunker = "Upravy aut a obchod s auty v bunkru",
	crewperk_clothshop_bunker = "Obchod s oblecenim v bunkru",
	crewperk_weapon_bunker = "Obchod se zbranemi v bunkru",
	crewperk_double_storage = "Zvetsena crew bedna v bunkru",
	crewperk_slots_increase_a = "Zvyseni maximalniho poctu clenu v crew o 2",
	crewperk_default_cloth = "Moznost pro nastaveni vychoziho outfitu pro vsechny cleny",
	crewperk_map_blips = "Moznost videt ostatni cleny na mape",
	crewperk_speed_boost_bunker = "Zrychleni pro vsechny cleny v bunkru",
	crewperk_slots_increase_b = "Zvyseni maximalniho poctu clenu v crew o 3",
	crew_did_not_unlock_perk = "~r~Tvoje crew si nevylepsila tento perk.",
}

AddLanguage("cs", my_language)