local my_language = {
    give_vehicle = "Du tilføjede ~b~%s~w~ til din inventar.",
    store_vehicle_command = "Opbevar dette køretøj, du kører",
    no_entity_vehicle = "~r~Køretøjet findes ikke eller er for langt fra dig.",
    no_entity_vehicle_id = "~r~Køretøjet er ikke bundet til noget ID, du kan derfor ikke opbevare det.",
    store_vehicle = "~b~Du har opbevaret dit køretøj.",
    teleported_former_position = "~g~Du er blevet teleporteret til din sidst gemte placering.",
    not_enough_of = "~r~Du har ikke nok %s.",
    max_storage_chest = "~r~Opbevaringsboksen er fuld.",
    cant_carry_more_items = "~r~Dit inventar kan ikke holde på flere genstande (fuld).",
    put_item = "Du lagde ~g~x%s~w~ %s~w~.",
    take_item = "Du tog ~g~x%s~w~ %s~w~.",
    delete_item = "Du fjernede ~r~x%s~w~ %s~w~.",
    you_equiped_item = "Du har udstyret dig med din ~g~%s~w~.",
    bind_weapon_command = "Genvej til våbenslot %s",
    kevlar_broke = "~r~AHH!~n~~w~Din rustning gik i stykker.",
    inventory_command = "Skift til inventar",
    press_enter_to_join = "Tryk ~g~ENTER~w~ for at begynde spillet.",
    new_character = "Ny karakter",
    survivor = "Overlevende",
    right = "Højre",
    left = "Venstre",
    male = "Mand",
    female = "Kvinde",
    ped = "Ped",
    name = "Navn",
    sex = "Køn",
    title = "Titel",
    select_this_character = "Vælg denne karakter",
    no_entity_zombie = "Zombien eksisterer ikke eller er for langt fra dig.",
    you_found = "Du fandt ~g~%sx %s~w~.",
    you_found_nothing = "Du fandt ~g~ingenting~w~.",
    press_e_to_loot = "Tryk ~b~[E]~w~ for at loote",
    full_for_item = "~r~Der er ikke nok plads for denne genstand There is not enough room for this item.",
    put_item_container = "Du lagde ~g~x%s~w~ %s~w~ i din opbevaring.",
    take_item_container = "Du tog ~g~x%s~w~ %s~w~ fra din opbevaring.",
    not_allowed_here = "~r~Dette er ikke tilladt på denne placering.",
    cant_store_moving_veh = "~r~Du kan ikke opbevare et køretøj i bevægelse.",
    use_repair_tool = "Anvend reparationsværktøjet",
    please_get_closer = "~b~Kom venligst tættere på, ingen enhed er inden for rækkevidde.",
    you_cancel_action = "~r~Du har annulleret din handling.",
    selected_target_message = "Udvalgte mål target:~n~%s~n~~r~Tryk ~b~Y~r~ for at annullere~n~~r~Tryk ~g~X~r~ for at fortsætte.",
    target_you = "~b~Dig",
    target_screen = "~g~Vises",
    take_this_path = "Tag denne vej",

    -- hud
    default_hud = "Default HUD",
    cinema_hud = "Cinema HUD",
    no_hud = "No HUD",

    -- perms
    kick_member = "Kick medlem",
    edit_member = "Redigere medlemmer",
    edit_rank = "Redigere rang",
    create_rank = "Opret rang",
    delete_rank = "Slet rang",
    edit_structure = "Redigere crew info",
    edit_permissions = "Redigere tilladelser",
    permission_level = "Tilladelsesniveauer",
    red_delete = "Slet",
    rank = "Rang",
    red_kick = "Kick",
    crew_name = "Crew navn",
    slogan = "Signatur",
    information = "information",
    boss_rank = "Leder rang navn",
    member_rank = "Medlemmernes rang navn",
    member = "Medlem",

    permissions_manager = "Tilladelsesadministrator",
    members_manager = "Medlems leder",
    ranks_manager = "rang leder",
    ranks_list = "rangs liste",
    members_list = "Medlems list",
    create_a_rank = "Opret en invitation",
    invite_someone = "Inviter person",
    stats = "Stats",
    total_ranks = "Rangsantal",
    total_members = "Memdlemsantal",
    level = "Level",
    actions = "Handlinger",
    crew_manager = "crew leder",
    you_created_a_new_crew = "Du har oprettet et nyt crew: %s",
    you_deleted_your_crew = "Du har slettet dit crew.",
    you_are_not_in_a_crew = "Du er ikke i noget crew",
    you_joined_the_crew = "Du har tilsluttet dig et nyt crew '%s'",
    kick_failed = "Dit kick fejlede, årsag: %s",
    already_in_crew = "Du er allerede i et crew",
    no_invitation = "Du har ikke modtaget noget invitation.",
    left_crew = "Du har forladt dit crew.",
    permission_updated = "Tilladelserne for <C>~g~%s</C>~w~ er opdateret.",
    incorrect_name = "~r~Navneformatet er forkert",
    incorrect_rank_perm = "~r~Fejl\n~w~Rang navnet eller tilladelsesniveauet er ugyldigt.",
    warn_rank_limit = "~r~Du har opnået begrænsningen for rangs.",
    create_rank_success = "~g~Succes\n~w~Du har oprettet et nyt rank <C>~b~%s</C>~w~ med et tilladelsesniveau på <C>~b~%s</C>~w~.",
    crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Du kan ikke interagere med et medlem, der har et tilladelsesniveau over dit.",
    you_sent_an_invitation = "Du har sendt en invitation til <C>~g~%s</C>~w~ til at tilslutte sig dit crew.",
    you_received_an_invitation = "Du har modtaget en invition til at tilslutte et crew.\n~b~/%s to accept.",
    invitation_expired = "Invitationen er udløbet",
    crew_kick_success = "Du har fjernet <C>~b~%s</C>~w~ fra dit crew.",
    first_rank_warning = "Det første rang er et 'standart' rang.",

    you_updated_this = "Du har opdateret %s til ~g~<C>%s</C>~w~.",
    changes_saved_on = "Dine ændringer lavet på <C>~g~%s</C>~w~ er gemt.",
    yes = "Ja",
    no = "Nej",
    none = "Ingen",
    character_id = "Karakter ID",
    server_id = "Server ID",
    report = "Rapporter",
    rename = "Omdøb",
    trade_with = "Byt",

    please_wait_x_before = "~r~Vent venligst %s sekunder før fortager dig det.",

    -- Tøj
    take_outfit = "Køb dette outfit",
    wardrobe_options = "Garderobe muligheder",
    wardrobe = "Garderobe",
    manual_options = "manuelle muligheder",
    manual_mode = "manuel tilstand",
    save_outfit = "Gem dette outfit",
    variation = "variation",
    outfits = "outfits",
    cloth_shop = "Tøjbutik",
    ped_cloth_shop = "Ped tøjbutik",
    manual_props = "manuelle rekvisitter",
    manuel = "manuel",
    new_name = "Nyt navn",
    outfit_name = "Outfit navn",
    variations_saved = "~g~Succes.~n~~w~Dine karaktervariationer er blevet gemt.",
    equipped_new_outfit = "Du har udstyret dig med dit nye outfit: ~b~%s",
    warning_limit_outfits = "Du har opnået begrænsninger for gemte outfits. ~g~(%s)",
    saved_new_outfit = "Du har gemt et nyt outfit: ~b~%s~w~.",
    rename_outfit = "Dit outfit ~b~%s~w~ er blevet omdøbet til ~g~%s~w~.",
    delete_outfit = "Dit outfit: ~b~%s~w~ er blevet slettet.",

    torso = "Torso",
    props = "Rekvisitter",
    top = "Top",
    tops = "Tops",
    badge = "Emblem",
    pants = "Bukser",
    pant = "Pant",
    shoes = "Sko",
    bags = "Tasker",
    undershirt = "undertrøje",
    neck = "nakke",
    bracelets = "armbånd",
    montres = "Urer",
    earrings = "øreringe",
    glasses = "briller",
    hats = "hatter",
    graphiques = "dekoration",

    -- health
    inconscious = "Bevidstløs",
    doing_something = "Gør noget",
    time_before_respawn = "Tid før genoplivning",
    you_died = "~r~Du døde.",
    healing_wounds = "Heler skader",
    already_doing_something = "~r~Du er allerede igang med en handling.",
    you_have_been_healed = "~g~Du er blevet helet.",
    you_respawned = "~g~Du genoplivede.",

    player_too_far_to_interact = "~r~Den spiller, du vil interagere med, er for langt fra dig.",
    send_trade_invitation_to = "Du har sendt en invitation til at bytte med ~b~%s~w~.\n~b~Vent venligst til at den anden spiller accepterer.",
    receive_invitation_from = "Du har modtaget en invitation til at bytte fra ~b~%s~w~.\n~b~Tast ~w~/trade accept %s~b~ for at begynde byttet.",

    invalid_command_args = "Ugyldigt kommando argument: %s",
    start_trade_command_help = "Start en byttehandel med en anden spiller",
    accept_trade_command_help = "Accepter en bytte invitation",
    deny_trade_command_help = "Afvis en bytte invitation",
    invalid_invitation = "Invitationen er ugyldig eller eksisterer ikke længere",
    name_accepted_your_trade_invitation = "~b~%s~w~ har accepteret din bytte invitation",
    you_accepted_trade_invitation_of_name = "Du har accepteret bytte invitationen fra %s",
    name_denied_your_trade_invitation = "~b~%s~w~ har afvist din bytte invitation",
    you_denied_trade_invitation_of_name = "You denied the trade invitation of %s",
    you_already_trading = "Du bytter allerede",
    other_already_trading = "Den anden spiller bytter i forvejen",

    other_player_not_enough_money = "~r~Byttet fejlede. Den anden spiller havde ikke nok penge.",
    you_player_not_enough_money = "~r~Byttet fejlede. Du havde ikke nok penge.",
    other_player_not_enough_item = "~r~Byttet fejlede. Den anden spiller havde ikke nok af en bestemt genstand.",
    you_player_not_enough_item = "~r~Byttet fejlede. Du havde ikke ikke nok af en bestemt genstand.",
    success_trade = "~g~Byttehandlen er bekræftet.",
    fail_trade_other_player = "~r~Byttet fejlede, den anden spiller forlod.",
    trade_other_full_item = "~r~Byttet fejlede, den anden spiller havde ikke nok plads.",
    trade_full_for_item = "~r~Byttet fejlede, du havde ikke nok plads.",

    press_e_to_loot_inv = "Tryk ~INPUT_CONTEXT~ for at loote inventaret.",
    press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Tryk ~INPUT_CONTEXT~ at interagere med ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
    press_e_to = "Tryk ~INPUT_CONTEXT~ for at ~b~%s~w~.",
    press_e_to_open_catalog = "Tryk ~b~E~w~ for at læse ~g~kataloget~w~.",
    this_person = "Denne person",
    the_shop = "Denne butik",
    you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Du har ikke tilladelse til at fortage denne handling.",

    no_weapon = "~r~Du har ikke udstyret dig med noget våben.",
    no_need_ammo = "~r~Du behøver ikke at bruge noget ammunition til dette våben.",
    not_right_ammo = "~r~Du bruger ikke den rigtige form for ammunition, du skal bruge ~b~%s~w~.",
    you_used_ammo = "Du har ladet dit ~b~%s~w~ med ~b~x%s~w~ af ~b~%s~w~.",

    choose_a_destination = "vælg en ~b~destination",
    open_your_chest = "Åben din opbevaring",
    no_enough_money = "~r~Du har ikke råd til dette.",
    you_paid = "Du har betalt ~g~$%s~w~ for ~b~%s~w~.",
    you_paid_basket = "Du har betalt ~g~$%s~w~ for din kurv.",
    you_sell_basket = "Du har modtaget ~g~$%s~w~ for at sælge ~b~x%s~w~ genstand(e).",

    you_repaired_your_vehicle = "~g~Du har repareret dit køretøj.",
    repairing_your_vehicle = "Reparerer dit køretøj",
    wheels_are_fine = "~r~Køretøjets hjul er allerede i en god tilstand.",
    changing_wheel = "Skifter hjulene",
    you_repaired_the_wheels = "~g~Du har repareret køretøjets hjul.",

    front_post_ls = "Front post Los Santos",
    front_post_ls_2 = "Front post Los Santos 2",
    front_post_bc = "Front post Blaine County",
    front_post_bc_2 = "Front post Blaine County 2",
    main_post_ls = "Safe City Los Santos",
    main_post_bc = "Safe City Blaine County",
    random_zone = "Tilfældig zone (lander)",

    this_item_is_equipped = "~r~Denne genstand er i brug, fjern det fra dine genveje.",
    only_in_safezone = "~r~Du kan ikke gøre dette udenfor en safe-zone.",
    -- Commerce
    feature_gold_only = "Denne funktion er kun tilgængelig for ~y~gold members~w~.",
    feature_diamond_only = "Denne funktion er kun tilgængelig for ~b~diamond members~w~.",
    you_turned_into = "Du blev til en ~g~%s~w~.",
    wait_between_transformation = "~r~Vent venligst et øjeblik før du benytter dig af Morph Mode again.",
    wait_between = "~r~Vent venligst før du foretager dig det igen.",
    available_morphs = "Tilgængelige morphs",
    animal_models = "Dyr modeller",
    zombie_models = "Zombie modeller",
    success_update_name = "Du har ændret din karakters navn til ~b~%s~w~.",
    success_reset_stats = "~g~Du har nulstillet dine stats. (Leaderboards will be updated later)",

    -- Dyr
    boar = "Vildsvin",
    cat = "Kat",
    chop = "Rottweiler (Chop)",
    rottweiler = "Rottweiler",
    cow = "Ko",
    coyote = "Prærieulv",
    deer = "Hjort",
    hen = "Høne",
    husky = "Husky",
    mtlion = "Løve",
    pig = "Gris",
    poodle = "Puddel",
    pug = "Mops",
    rabbit = "Kanin",
    rat = "Rotte",
    retriever = "Retriever",
    shepherd = "Fårehyrde",
    westy = "Westy",

    player_id = "Spillerens ID",
    bounty = "Dusør",
    reason = "Årsag",
    id_player_not_found = "~r~Ingen spiller er forbundet med dette id.",

    ammo_dealer = "Ammunitionsforhandler",
    misc_dealer = "Udstyrsbutik",
    veh_dealer = "Bilforhandler",
    custom_dealer = "LS Custom",
    gun_dealer = "Våbenbutik",

    bounty_created = "Du betalte ~g~$%s~w~ for at oprette en dusørkontrakt på ~b~%s~w~.",
    contract_success = "Dusøren du har oprettet på ~r~%s~w~ er blevet sent til ~b~%s~w~.",
    a_contract_on_your_head = "~r~Du havde en dusør over dig. Din drabsmand har modtaget dusøren.",
    reward_for_contract = "Dusør jæger! Du er blevet belønnet med ~g~$%s~w~ for at dræbe ~b~%s~w~.",

    hey_can_help_you = "Hej, hvordan kan jeg hjælpe dig?",
    i_want_to_buy_items = "Jeg ville købe genstande",
    i_want_to_sell_items = "Jeg ville sælge genstande",

    press_context_or_jump_to_get_up = "Tryk ~INPUT_CONTEXT~ eller ~INPUT_JUMP~ for at ~b~rejse dig op~w~.",
    server_restart_warning = "Serveren genstarter..",
    auto_restart_in = "Automatisk genstart om %s sekunder.",

    not_allowed_create_character = "Du har ikke tilladelse til at oprette en ny karakter.",
    character_not_yours = "Denne karakter er ikke din.",
    character_does_not_exist = "Denne karakter eksisterer ikke eller eksisterer ikke længere.",
    loading_character = "Indlæser din karakter...",

    playtime_is = "~b~Din spille tid på Extinction:\n~w~%s",
    dont_spam = "^1Du bedes stopppe med at spamme!",

    babygod_warning = "~b~Du har forladt safe-zone, du er usynlig i en kort tidsperiode.",

    -- LS Custom
    modifications_classiques = "Klassiske modifikationer",
    modifications_custom = "Speciale modifikationer",
    modifications_benny = "Benny's modifikationer",
    paint = "farve",
    custom_your_car = "Tilpas din bil",
    wheels_modifications = "Hjul modifikationer",
    performances = "Performances",
    neons = "Neoner",
    extra = "Ekstra",
    klaxon = "Horn",
    teinte_fenetre = "Vindue tone",
    phares_xenons = "Xenon forlygter",
    modele_plaque = "Nummerplade model",
    livery = "Livery",
    headlight_color = "Forlygter farve",
    wheel_type = "Hjul type",
    primary_wheel_type = "Primær hjultype",
    back_wheel_type = "Baghjulstype",
    wheel_color = "Hjul farve",
    tire_smoke = "Dækrøg",
    custom_color = "Brugerdefineret farve",
    custom_wheel = "Brugerdefineret hjule",
    custom_back_wheel = "Brugerdefineret baghjul",
    suspension = "Affjedring",
    transmission = "Transmission",
    moteur = "Motor",
    frein = "Bremser",
    turbo = "Turbo",
    primary_color = "Primær farve",
    secondary_color = "Sekundær farve",
    interior_color = "Indvendig farve",
    dashboard_color = "Dashboard farve",
    color_effect = "Farveeffekt",
    left_neon = "Venstre neon",
    right_neon = "Højre neon",
    front_neon = "Foreste neon",
    back_neon = "Bagerste neon",

    aileron = "Spoiler",
    pc_front = "Forreste kofanger",
    pc_back = "Rear bumper",
    carroserie = "Sideskørt",
    exhaust = "Udstødning",
    cadre = "Ramme",
    calandre = "Gitter",
    capot = "Kølerhjelm",
    gb_left = "Venstre skærm",
    gb_right = "Højre skærm",
    roof = "Tag",
    plate_support = "Pladeholdere",
    front_plate = "Forplade",
    interior_style = "Indvendig stil",
    figurine = "Figur",
    motif_dashboard = "Dashboard stil",
    cadran = "Skivedesign",
    haut_parleur_portes = "Højttalerdøre",
    motif_sieges = "Sæde stil",
    volant = "Rat",
    levier = "Shifter leavers",
    logo_custom = "Logo",
    ice = "ICE",
    haut_parleur_coffre = "Højttaler bagdøre",
    hydrolique = "Hydraulik",
    moteur = "Motor",
    filtres_air = "Luft filter",
    entretoises = "Afstandsstykker",
    arc_couverture = "Arch",
    antenne = "Antenne",
    motif_exterieur = "Udvendig stil",
    reservoir = "Tank",
    window = "Vindue",
    style = "Stil",
    default = "Standart",
    type = "Type",
    normal = "Normal",
    black = "Sort",
    black_smoke = "Sort røg",
    simple_smoke = "Simpel røg",
    stock = "Stock",
    limo = "Limousine",
    sa_black = "San Andreas sort",
    sa_blue = "San Andreas blå",
    sa_white = "San Andreas hvid",
    simple_white = "Simpel hvid",
    ny_white = "North Yankton hvid",
    race = "Race",
    sport = "Sport",
    stock = "Lager",
    street = "Vej",
    discount = "Rabat",
    select_your_car = "Vælg din bil",
    select_car_custom = "Vælg den bil du gerne ville tilpasse. Tallene imellem pilene er genstandsnøglen.",
    loading_vehicle = "Opret køretøjer",
    invalid_vehicle = "~r~Ugyldig køretøjsenhed.",
    invalid_vehicle_please_spawn = "~r~Ugyldig køretøjs genstand. Venligst spawn dette en gang, før du forsøger at gøre noget.",
    free_take_and_validate = "Alt er gratis. Tag hvad du vil og bekræft!",
    car_custom_saved = "~g~Dine bilændringer er blevet gemt.",

    -- Karakter oprettelse
    character_creation = "Karakter oprettelse",
    confirm = "Bekræft",
    start_playing = "Begynd at spille",
    appearance = "udseende",
    character_list = "karakter liste",
    face_features = "ansigtstræk",
    parents = "forældre",
    parent = "parent",
    mix = "blanding",
    skin = "hud",
    desc_mix = "Vælg om formen på dit ansigt er mere påvirket af din far/mor.",
    desc_skin = "Vælg om din hud er mere påvirket af din far/mor.",
    identity = "identitet",
    player_name = "spiller navne",
    new_character = "ny karakter",
    warning_headblend = "~r~Du har ikke valgt dine karakters forældre.",
    warning_overlays = "~r~Du har ikke valgt hår, øjenbryn eller skæg.",
    warning_identity = "~r~Advarsel.~n~~w~Du glemte at udfylde identitetsfeltet.",

    -- Udstyr
    kit_does_not_exist = "~r~Dette udstyr findes ikke.",
    kit_needs_rank = "Du har ikke ~r~%s~w~ ranget.",
    wait_before_using_kit = "Vent venligst ~r~%s~w~ før du benytter dette udstyr.",
    received_kit = "Du har modtaget dit udsytr ~b~%s~w~.",
    no_kit = "Du har ikke noget udstyr.",

    unable_to_find_booster = "Mislykkeds at finde en sprøjte med dette id.",
    wait_already_player_boost = "Vent venligst et øjeblik, før du bruger denne sprøjte. Der er allerede en spillersprøjte der er aktiv.",
    wait_already_crew_boost = "Vent venligst et øjeblik, før du bruger denne sprøjte. Der er allerede en crew sprøjte der er  aktiv.",
    wait_already_server_boost = "Vent venligst et øjeblik, før du bruger denne sprøjte. Der er allerede en server sprøjte der er aktiv.",
    booster_activated = "Sprøjten er aktiveret for  ~g~%s minutter~w~! ~b~XP +%s%%",
    server_booster_activated = "~b~%s~w~ Aktiveret en server sprøjte for ~g~%s minutter~z~! ~b~XP +%s%%",
    crew_booster_activated = "~b~%s~w~ Aktiveret en crew sprøjte for ~g~%s minutter~z~! ~b~XP +%s%%",
    no_booster = "Du har ikke nogen sprøjte.",

    rank_expired = "~r~Din supporter rolle er udløbet.",
    supporter_role = "~g~Supporter rolle:~w~ %s",
    no_rank_warning = "Du har ingen supporterroller.\n~r~Hvis du har foretaget et køb skal du forbinde din fivem konto.",
    no_fivem_id = "Dit FiveM er ikke forbundet med spillet.\n~r~Bekræft at du har en FiveM konto og, at den er forbundet til spillet.",
    no_queue_warning = "Du har ikke nogen pakke i kø.\n~r~Vent venligst et øjeblik eller prøv /getRank hvis du leder efter dit rang.",
    package_sync_success = "~g~Dine pakker har synkroniseret succesfuldt, god fornøjelse!\n~w~Useful commands: /getRank, /booster",

    level_required = "Du skal være i level %s.",
    rank_required = "Du er nødsaget til at have %s ranget.",
    level_required_2 = "~r~Du skal være i level %s.",

    updated_deathmessage = "~g~Du har opdateret din dræbsmeddelelse.",
    updated_deatheffect = "~g~Du har opdateret dine dræbseffekter.",
    use = "Brug",
    test = "Test",

    -- zombie
    you_bitten = "~r~Du er blevet bidt.",
    infection_rate = "Infektions rate: ~r~%s%%",

    -- ranks
    thug = "bandit",
    hustler = "Hustler",
    soldier = "Soldat",
    trigger = "Trigger",
    enforcer = "Håndhæver",
    facilitator = "Facilitator",
    public_enemy = "Offentlig fjende",
    shot_caller = "Shot Caller",
    street_boss = "Gade Boss",
    kingpin = "Kingpin",
    -- Tattoo
    tattoo = "tattoo",
    tattoos = "tattoos",
    torso = "torso",
    head = "hoved",
    left_arm = "venstre arm",
    right_arm = "højre arm",
    left_leg = "venstre ben",
    right_leg = "højre ben",
    unknown = "ukendt",
    other = "andre",
    remove_tattoo = "Fjern alle tattoos",
    -- Hairdress
    haircuts = "Klipninger",
    makeup = "Make up",
    face = "Ansigt",
    eyebrows = "Øjenbryn",
    facial_hair = "Ansigtshår",
    body_hair = "Kropshår",
    barber_shop = "Frisør",
    face_makeup = "Ansigts make up",
    lipstick = "Læbestift",
    face_foundation = "Ansigts foundation",
    skin_blemishes = "Hud skavanker",
    skin_ageing = "Hudens ældning",
    moles_freckles = "Fregner",
    sun_damage = "Hud skade",
    skin_complexion = "Hudens teint",
    body_blemishes = "Pletter på kroppen",
    body_blemishes_2 = "Pletter på kroppen 2",
    opacity = "Alfa",
    variations = "Variationer",
    filter = "Filters",
    eyes_color = "øjenfarve",
    -- Mask
    masks = "Maske",
    -- Items
    money = "Penge",
    -- Ammo
    ["9mm"] = "9mm",
    ["300_mag"] = ".300 Magnum",
    ["7_62mm"] = "7.62mm",
    ["calibre_12"] = "Calibre 12",
    ["45_acp"] = ".45 ACP",
    ["5_56mm"] = "5.56mm",
    rocket = "Rocket",
    flare = "Flare",
    grenade = "Granat Ammo",
    -- Food
    ["fish_1"] = "Largemouth Bass",
    ["fish_2"] = "Rainbow Trout",
    ["fish_3"] = "Kokanee",
    ["fish_4"] = "Arctic Grayling",
    ["fish_5"] = "Rock Bass",
    ["fish_6"] = "Smallmouth Bass",
    ["fish_7"] = "Paddlefish",
    ["fish_8"] = "Bull Trout",
    ["fish_9"] = "Lake Trout",
    ["fish_10"] = "Chinook",
    ["fish_11"] = "Pallid Sturgeon",
    ["fish_12"] = "Salmon",

    misc_meat = "Rå kød",
    rabbit_meat = "Rå kanin",
    lion_meat = "Rå løve",
    rare_plume = "Rå fjer",
    dog_meat = "Rå hund",
    cat_meat = "Rå kat",
    rare_fish = "Sjælden fisk",

    mask = "Maske",
    malette = "kuffert",
    malette_metal = "Metal kuffert",
    ciseaux = "Saks",
    clean_kit = "Rengøringsudstyr",
    fishing_rod = "Fiskestang",
    meuble = "Møbel",
    tissu = "Tøj",
    accessory = "Tilbehør",
    radio = "Radio",
    recyclor = "Genbruger",
    medkit = "Førstehjælpskasse",
    kevlar = "Skudsikker vest",
    gps = "GPS",
    repair_tool = "Reparationsværktøj",
    jvn = "JVN",
    engine_veh = "Motor",
    bag = "Sæk",
    wheel_veh = "Hjul",
    vetement = "Top",
    bloc_note = "Notesplok",
    paint_spray = "Malingsspray",
    spike = "Spike strip",
    paracetamol = "Paracetamol",
    bandage = "Bandage",
    gaz_mask = "Gas maske",
    filter = "Filter",
    tattoo_tool = "Tattoo middel",
    drug_med = "Drug",
    drug_antizin = "Antizin sprøjte",
    drug_stamina = "Stamina sprøjte",
    drug_berserker = "Helbredssprøjte",

    pickup_spikestrip = "pickup the spike strip",
    you_dropped_spikestrip = "You dropped a ~g~spike strip~w~.",
    you_pickup_spikestrip = "You picked up a ~g~spike strip~w~.",

    you_have_been_killed_by = "Du er blevet dræbt af ~r~%s",
    kill_notif = "~m~Dræbt",
    you_killed = "Du dræbte ~r~%s~w~",
    already_used_reset_only = "~r~Du har allrede nulstillet din karakter.\n~w~Kun %s~w~ medlemmer kan foretage dette mere end en enkelt gang.",
    already_used_reset_only2 = "~r~Du har allerede gjort dette.\n~w~Kun %s~w~ medlemmer kan foretage dette mere end en enkelt gang.",

    hud_options = "HUD muligheder",
    advanced_hud = "Display avanceret HUD",
    players = "Spillere",
    health = "Helbred",
    player_menu = "Spiller menu",

    you_are_now_zombie = "~r~Du er nu en zombie.",

    my_weapons = "mine våben",
    customize_weapons = "Tilpas mit våben",
    weapon_skin = "Tint",

    -- camo
    skin_classic = "Standart",
    skin_green = "Grøn",
    skin_yellow = "Gul",
    skin_pink = "Pink",
    skin_gold = "Guld",
    skin_blue = "Blå",
    skin_orange = "Orange",

    weapon_katana = "Katana",
    weapon_sledgehammer = "Forhammer",

    -- new
    airdrop_coming = "~r~Et airdrop kommer tjek dit map.",
    killed_by_cheater = "~r~Du er blevet dræbt af en der snyder.\n~w~Vi har bannet ham og din død annulleresWe banned him and your death has been canceled.",

    corrupted_vehicle = "~r~Dette køretøj er korrupt og er blevet duplikeret, derfor er det fjernet fra dit inventar. Vi bekalger hvis du er blevet snydt.",

    -- Discord
    join_discord_for_kit = "Tilslut dig vores discord og få dit gratis discord udstyr!\n~g~discord.gg/gtalife",
    discord_account_not_linked = "~r~Du er nødsaget til at tilslutte din discord bruger til FiveM.",
    discord_account_not_guild = "~r~Du er ikke en del af vores discord.\n~w~Tilslut discord.gg/gtalife",

    already_done_recently = "~r~Prøv igen senere, du har lige forsøgt dette..",
    update_country = "Opdater nationalitet",

    prestige_info = "~b~Du har opnået det maksimale level.\n~w~Tast /prestige for at få informatiom om prestige niveauerne og dens systemer.",
    prestige_not_max_level = "~r~Du har ikke opnået det maksimale level.",
    max_prestige_reached = "~r~Du har opnået det sidste prestige.",
    prestige_info_cmd = [[^3Prestige leveling system^7
Du er på nuværende tidspunkt prestige ^4%s^7 og level ^5%s^7.
Hivs du har opnået det maksimale level (%s) kan du vælge imellem prestige og nulstille din XP udvikling og start fra level 0.
At opnå et nyt prestige giver dig specialle emblemer og nye fordele, som bedre loot, nye genstande, flere penge eller mere inventar plads.
^2Hvis du ville prestige og vende tilbage til level 0 tast ^1/setprestige^2
]],
    new_prestige = "Du har åbnet et nyt prestige!\n~g~Du har nu %s prestige(s)",
    cant_store_event_veh = "~r~Du kan ikke opbevare specielle køretøjer.",

    you_are_no_longer_in_combat = "🛡️ ~b~Du er ikke længere i kamptilstand.",
    you_are_in_combat_mode = "🛡️ ~b~Du er i kamptilstand.\nHvis du afbryder forbindelsen ville du dø.",
    you_disconnected_in_combat = "💀 Du forlod i kamptilstand, derfor døde du.",

    not_enough_prestige_points = "~r~Du har ikke nok prestige point.",
    you_reached_max_prestige_stats_rank = "~r~Du har opnået det maksimale rang for denne prestige opgradering.",
    new_prestige_stats_upgrade = "Du har opgraderet din ~b~%s~w~\n~g~%s/%s",

    legendary_vehicle_pop = "~r~Et legendarisk køretøj er kommet til på mappet.",

    -- poll one
    poll1_q1 = "Hvad for en type spil server ønsker du at se?",

    poll1_q1_a1 = "Battle Royale",
    poll1_q1_a2 = "Private missioner solo eller med 1-4 venner (Payday / Heist / Hitman like)",
    poll1_q1_a3 = "Race / Freeroam",
    poll1_q1_a4 = "Murder / Horror game",

    -- poll two
    poll2_q1 = "Are you an English speaker and would you be interested in a GLife RP Server?",

    poll2_q1_a1 = "No",
    poll2_q1_a2 = "Yes",

    combat_mode_container_disabled = "~r~Du er i kamptilstand.\n~w~Du kan ikke opbevare genstande.",
    gcoins_wallet_updated = "~g~Din GCoins pung er blevet opdateret.\n~w~+%s GCoins",
    not_enough_gcoins = "~r~Du har ikke nok GCoins.",
    gcoins_something_went_wrong = "~r~En fejl forekom.",
    you_bought_with_gcoins = "Du købte ~g~%s~w~ for ~b~%s GCoins~w~.",

    equiping_armor = "Benytter skudersikker vest",

    toggle_mute_player = "Toggle stum",
    you_muted_this_player = "~b~Du har gjort denne spiller stum .",
    you_unmuted_this_player = "~b~Du har fjernet stumheden fra denne spiller.",

    already_purchased = "~r~Du har allerede købt denne genstand.",
    weapon_camo_preview = "Du ser en forhåndsvisning af en våbenbasemodel, hvor nogle elementer mangler .\n~INPUT_CELLPHONE_CANCEL~ for at annullere forhåndsvisningen.",

    already_using_a_seringue_booster = "~r~Du har allerede brugt denne sprøjte.",
    seringue_effect_done = "~b~Din sprøjte-effekt er forsvundet.",
    you_injected_a_seringue_boost = "Du har sprøjtet en ~b~sprøjte ~w~ i dit blod.",

    put_item_permission = "Læg genstand",
    take_item_permission = "Tag genstand",
    put_money_permission = "Læg penge",
    take_money_permission = "Tag penge",

    preferred_badge_set = "Du har sat dit ~g~foretrukkende emblem~w~.",
    preferred_badge_not_set = "~r~Mislykkeds at sætte dit foretrukkende emblem.",

    marketplace_received_money_sales = "Du har modtaget ~g~$%s~w~ fra ~b~%s~w~ salg.",
    marketplace_no_sales = "~r~Du har ikke solgt noget.",
    marketplace_you_paid_for = "Du betalte ~g~$%s~w~ for ~b~%s~w~.",

    deleted_sell_offer = "~b~Du har slettet dine markedssalg.",
    deleted_buy_offer = "~b~Du har slettet dine markedssalg.",
    deleted_sell_offers = "~b~Du har slettet dine markedssalg.",
    deleted_buy_offers = "~b~Du har slettet dine markedssalg.",

    marketplace_offer_does_not_exist = "~r~Dette tilbud eksisterer ikke.",

    marketplace_create_sell_offer = "Du har oprettet et salg for ~b~%sx %s ~w~for ~g~$%s~w~ per enhed.",
    marketplace_create_buy_offer = "Du har oprettet et købssalg for ~b~%sx %s ~w~for ~g~$%s~w~ per enhed.",

    i_want_to_enter_in_my_property = "Jeg ville gerne tilgå min ejendom.",
    i_want_to_exit_private_world = "Jeg ville gerne vende tilbage til den offentlige verden.",
    public_world = "Offentlig Verden",
    private_world = "Privat Verden",

    dailymission_playerkill = "Dræbte spillere",
    dailymission_zombiekill = "Dræbte zombier",
    dailymission_playerheadshotkill = "Spiller hovedskud",
    dailymission_zombieheadshotkill = "Zombie hovedskud",
    dailymission_zombiesurvivorkill = "Dræbte overlevende zombier",
    dailymission_zombiearmoredkill = "Dræbte udstyrede zombier",
    dailymission_zombiehazmatkill = "Dræbte hazmat zombies",
    dailymission_zoombieboomerkill = "Dræbte boomer zombies",
    dailymission_sellitems = "Genstande solgt",
    dailymission_buyitems = "Genstande købt",
    dailymission_lootitems = "Genstande lootet",
    dailymission_createselloffer = "Salget er oprettet",
    dailymission_killtopkillcrew = "Dræbte spillere fra crew",
    dailymission_killtopkillplayers = "Dræbte spillere",
    dailymission_getintolegendaryvehicle = "Køretøjer",
    dailymission_killzombiewithweapon = "Zombie dræbt med våben",
    dailymission_killplayerwithweapon = "Spillere dræbt med våben",
    dailymission_darkzonesurvivingtime = "Darkzone overlevelsestid",
    dailymission_redzoneplayerkill = "Dræbte spillere i redzone",
    dailymission_redzonezombiekill = "Zombie drab i redzone",
    dailymission_darkzoneplayerkill = "Spiller drab i darkzone",
    dailymission_darkzonezombiekill = "Zombie drab i darkzone",
    dailymission_useitem = "Brugte genstande",
    dailymission_playtime = "Spilletid",
    dailymission_xpharvest = "Harvested XO",
    dailymission_sellofferpurchased = "Markedssalg opkøbt",
    dailymission_sellofferpurchasedbyme = "Markedssalg opkøbt",
    dailymission_tradeitems = "Genstande byttet",
    dailymission_createbuyoffer = "Markedssalg oprettet",

    dailymission_completed = "~g~Du har fuldført en daglig mission!\n~b~+%s XP\n~y~+1 Dungeon Key",

    character_creation_mix_desc = "Vælg, om formen på dit ansigt er mere påvirket af din fars/mors form.",
    character_creation_skin_desc = "Vælg, om formen omkring din hud er mere påvirket af din fars/mors form.",

    ff_1 = "Næse bredde",
    ff_2 = "Næse højde",
    ff_3 = "Næse længde",
    ff_4 = "Næse hængende",
    ff_5 = "Næsespidsfald",
    ff_6 = "Næse vrid",
    ff_7 = "Øjenbryns højde",
    ff_8 = "Øjenbryns dybde",
    ff_9 = "Kindbenshøjde",
    ff_10 = "Kindbensbredde",
    ff_11 = "Kindbredde",
    ff_12 = "Øjneåbning",
    ff_13 = "Læbe tykkelse",
    ff_14 = "Kæbebredde",
    ff_15 = "Kæbe tilbage længde",
    ff_16 = "Hagesænkning",
    ff_17 = "Hagebenslængde",
    ff_18 = "Hagebredde",
    ff_19 = "Hagehul",
    ff_20 = "Hals tykkelse",

    airdrop_taken_by = "^1%s har taget %s fra airdroppet.",

    available_death_effects = "Tilgængelige dødseffekter",
    available_modes = "Tilgængelig modeller",

    you_changed_your_ped_model = "~g~Du har nu ændret din ped-model.",
    i_want_to_change_my_ped = "Jeg ville gerne ændre min ped",

    poll4_q1 = "Hvad forventer du for næste sæson?",
    poll4_q1_a4 = "Nye begivenheder, som airdrops, zone capture osv.",
    poll4_q1_a1 = "Mere PvE indhold, som dungeons",
    poll4_q1_a2 = "Flere spil, som casion/race",
    poll4_q1_a3 = "PvP indhold",

    poll4_q2 = "Kunne du tænke dig at have flere rangerede/turneringer?",
    poll4_q2_a1 = "Ja",
    poll4_q2_a2 = "Nej",

    poll4_q3 = "Kunne du tænke dig at have flere snipere i butikkerne?",
    poll4_q3_a1 = "Ja",
    poll4_q3_a2 = "Nej",

    poll4_q4 = "What do you enjoy the most on Extinction?",
    poll4_q4_a1 = "PvP",
    poll4_q4_a2 = "PvE",
    poll4_q4_a3 = "Trading",

    dungeon_no_more_time = "~r~Du er for langsom. Dungeonen er lukket.",
    dungeon_participant_left = "~r~%s har forladt dungeonen.",
    started_dungeon_party = "~b~Du har oprettet et dungeon rum.",
    dungeon_party_no_longer_exists = "~r~Denne dungeon eksisterer ikke længere.",
    dungeon_invitation_expired = "~r~Dungeon invitationen er udløbet.",
    dungeon_join_party = "~g~Du har tilsluttet dig dungeonen.",
    dungeon_too_late_for_invitation = "~r~Du var for langsom. Du kan ikke tilslutte dungeonen på nuværende tidspunkt.",
    dungeon_already_invited_this_player = "~r~Du har allerede inviteret denne spiller.",
    dungeon_invitation_received = "Du har modtaget en invitation fra ~b~%s~w~ for at tilslutte dig spillerens dungeon.\nType ~g~/dungeon join %s~w~ for at tilslutte dig.",
    dungeon_invitation_sent = "DU har inviteret ~g~%s~w~ til din dungeon.",

    i_want_to_enter_a_dungeon = "Jeg ville gerne tilgå dungeonen",
    dungeon_list = "Dungeon liste",
    dungeon = "Dungeon",
    dungeons = "Dungeons",
    you_need_x_keys = "Du skal bruge ~y~%s dungeon nøgler~w~ for at tilgå dungeonen.",
    time_remaining = "Tid tilbage",
    you_killed_the_dungeon_boss = "~r~Du har dræbt dungeon bossen.",
    dungeon_kill_final_boss = "Du er i det sidste rum. Dræb bossen for, at opnå dine frynsegoder.",

    dungeon_died_remaining = "Du døde, du har ~r~%s~w~ liv tilbage.",
    dungeon_died = "~r~Du har ikke flere liv tilbage. Du døde.",
    dungeon_already_in_party = "~r~Du er allerede i en dungeon.\n~w~Tast /dungeon quit for at forlade.",
    dungeon_does_not_exist = "~r~This dungeon does not exist.",
    dungeon_ready = "~g~%s~w~ er klar.",
    dungeon_not_ready = "~r~%s~w~ er ikke klar.",

    not_released_yet = "Dette er ikke udgivet.",
    feature_only_supporters = "~b~Denne funktion er i beta-test og kun Diamond/gold supporter kan benytte det for nu.",
    feature_not_enabled = "~b~Denne funktion er ikke mulig lige nu.\n~w~Vent venligst for dette senere i dag.",
    dungeon_charid_required = "~r~Venligst inkluder din vens karater id (øverst højre på skærmen) efter kommandoen.\nEksempel: /dungeon invite 1234",

    poll5_q1 = "Would you accept that our anticheat captures cheaters's entire screen if they're suspected of wallhack or aimbots? (It may shows a part of your desktop if the game is in windowed mode but these captures will not be saved and only used by reliable moderators)",
    poll5_q1_a1 = "skip - ignore",
    poll5_q1_a2 = "Yes, I agree to this new method",
    poll5_q1_a3 = "No, I disagree",

    -- S4
    redzone_kill_leader_killed = "~r~redzone kill leader~w~ er blevet dræbt.",
    redzone_kill_leader_fled = "~r~redzone kill leader~w~ flygtede.",
    redzone_get_back_kill_leader_before_x = "Du er  ~r~uden for redzone~w~ vend tilbage eller mist din titel om ~r~%s sekunder~w~.",
    redzone_kill_leader_new_xp_step = "~r~Redzone XP Multiplier\n~b~+%s%~w~ bonus",
    remaining_lives = "Resterende liv",

    name_tag = "Crew tag",
    redzone_changed = "~r~Red zones har fået nye placeringer.",

    -- Squad
    squad_not_leader = "~r~Du er ikke leder af dit squad.",
    squad_kicked_by_x = "Du er blevet ~r~kicked~w~ fra dit squad af ~r~%s~w~.",
    squad_you_kicked_x = "Du har fjernet ~r~%s~w~ fra dit squad.",
    squad_invited_x = "Du inviterede ~r~%s~w~ til dit squad.",
    squad_invited_you_x = "~r~%s~w~ inviterede dig til deres squad.\nTast ~r~/squad join %s~w~ for at tilslutte dig holdet.",
    squad_you_set_new_leader = "Du har sat ~r~%s~w~ som ny ~r~leader~w~ af dit squad.",
    squad_you_are_new_leader = "~g~Du er ny leder af dit squad.",
    squad_not_invited = "~r~Du er ikke blevet inviteret til noget squad.",
    squad_joined_squad = "~g~Du har tilsluttet dig et squad.",
    squad_left = "~r~Du har forladt dit squad.",
    squad_already_in = "~r~Du er allerede i et squad.",
    squad_created_x = "Du har oprettet et nyt squad. ~b~(%s)",
    squad_x_joined = "~b~%s~w~ tilsluttede sig dit squad.",
    squad_leader_deleted = "~r~Lederen har slettet sit squad.",
    write_yes_to_confirm = "Tast yes for at bekræfte",
    invite_a_player_write_char_id = "Inviter en spiller. Tast spillerens karakter id",

    -- Help stuff
    press_enter_beginner_guide = "Tast ~INPUT_ENTER~ for at start begynder guiden.",
    welcome_glife = "Velkommen til ~r~GLife Extinction~w~!",
    you_are_playing_server_x_with_x = "Du spiller på server ~b~#%s~w~ med ~b~%s spillere~w~.",
    start_beginner_guide = "Start begynder guiden",
    play_now = "~g~Spil nu!",
    interact_npc_fast_travel = "Interager med den hurtig rejsende NPC",

    -- Tutorial
    tutorial_beginner_end_msg = "~r~Tak for din tid!\n~w~God fornøjelse med at spille Extinction, hvis du har nogen spørgsmål kan du bruge chatten eller finde os på discord.",
    tutorial_beginner_start_msg = "~r~Velkommen til GLife Extinction!\n~w~Dette er en kort guide, som forklarer begyndelsen på dette spil.",
    tutorial_beginner_camera_01 = "~r~~BLIP_557~ ~r~Standart safezone\n~w~Dette er et sikkert område, hvor du kan shoppe og opbevare varer, men også personliggøre dit udstyr og handle med andre spillere.",
    tutorial_beginner_camera_02 = "~BLIP_568~ ~r~Opbevaringskiste\n~w~Here you can access your private storage and store your precious items.",
    tutorial_beginner_camera_03 = "~BLIP_567~~BLIP_556~~BLIP_658~ ~r~NPC Shops\n~w~Du kan købe og sælge dine genstande i mange butikker som f.eks. våben-, køretøjs- eller genstandsforhandleren.",
    tutorial_beginner_camera_04 = "~BLIP_84~ ~r~Offentlige dusører\n~w~Hvis det lykkes dig at finde og dræbe målet, får du den tilhørende belønning.",
    tutorial_beginner_camera_05 = "~BLIP_176~ ~r~Fjendtlig verden\n~w~Du vil møde zombier og fjendtlige spillere. De vil alle ønske at få dig dræbt, men de er den bedste måde at få XP og loot på.",
    tutorial_beginner_camera_06 = "~BLIP_303~ ~r~Verdens redzones\n~w~Der kan du finde bedre loot og tjene flere oplevelser fra dine drab.",
    tutorial_beginner_camera_07 = "~BLIP_648~ ~r~Darkzone øen\n~w~Her kan du ikke gemme genstande eller flygte let, men det er det bedste sted at finde tyvegods som MK2-våben eller snigskytter..",
    tutorial_beginner_camera_08 = "~BLIP_575~ ~r~Loot og udforskningsmuligheder\n~w~Du kan kæmpe om airdrop-kasser, men også udforske og slå dungeon bossen.",
    tutorial_beginner_training_01 = "~g~Du kom med i træningslokalet.\n~w~Hop med ~INPUT_JUMP~ når du er klar.",
    tutorial_beginner_training_02 = "~g~Lad os bruge inventaret.\n~w~Tryk ~%s~ for at åbne dit inventar.",
    tutorial_beginner_training_03 = "~g~Udstyr et våben.\n~w~Åbn inventaret og træk et våben i genvejslinjen.\nTryk på den tilsvarende tast ~b~1/2/3/4/5/6/7~w~.\n~r~Hvis du ikke har nogen våbenbrug ~b~/kit newbie.",
    tutorial_beginner_training_04 = "~g~Fyld ammunition op.\n~w~Udstyr en pistol, og sæt en æske med ammunition i din genvejsbar. Tryk derefter på genvejstasten.",
    tutorial_beginner_training_05 = "~g~Endelig til køretøjer.\n~w~Du kan spawne køretøjer, ligesom du udstyrer et våben. Når den er spawnet, kan du gemme den med ~%s~ imens du kører den. Tast på knappen for at bekræfte.",
    tutorial_beginner_training_success_01 = "~g~Godt arbejde, vi kan begynde nu!",
    tutorial_beginner_training_success_02 = "~g~Dejligt, du forstår det.\n~w~Det er den samme prcoes for at bruge alle genstande.",
    tutorial_beginner_training_success_03 = "~g~Dejligt, du forstår det.\n~w~Det er den samme prcoes for at bruge alle genstande.",
    tutorial_beginner_training_success_04 = "~g~ Dejligt, du forstår det.\n~w~Vi er færdige nu.",

    -- Darkzone stuff
    contaminated = "contaminated",
    darkzone_boat_leaving_in = "Bådene forlader om",
    darkzone_exit = "Exit spot",
    purificator = "Renser",
    you_entered_the_darkzone = "~r~Du har tilgået darkzone.\n~w~På nuværende tidspunkt er der ~b~%s spillere~w~ inde.",
    you_left_the_darkzone = "~r~Du har forladt darkzone.",
    cannot_enter_darkzone_time = "~r~Darkzone er ikke åben endnu, vent.",
    darkzone_is_full = "~r~Darkzone er fuld, Vent venligst.",
    darkzone_exit_allowed = "~r~Bådene er ankommet til udgangen af darkzone, løb hvis du ville flygte.",
    darkzone_close_time = "Lukker om",
    darkzone_surviving_since = "Overlevet siden",
    darkzone_points = "Points",
    darkzone_points_x = "~r~Darkzone points: ~w~+%s",
    darkzone_landing_in_x = "Landing tilgængelig om ~b~%s minutter~w~.\nHvis nok spillere .",
    darkzone_open_press_context = "Tryk ~INPUT_CONTEXT~ for at lande ~m~Inde i darkzone~w~.",
    darkzone_outside_warning = "~r~Du er udenfor darkzone, kom tilbage eller dø.",
    darkzone_close_warning = "~r~Darkzonen lukker snart~w~.\nDu skal ikke forblive her for længe.",
    darkzone_close_damage = "Darkzonen er lukket. Hele området er nu fourenet.",
    darkzone_not_enough_points_to_exit = "Du skal bruge ~r~%sx points~w~ For at forlade darkzonen.",
    press_e_to_exit_the_darkzone = "Tast ~INPUT_CONTEXT~ for at forlade darkzonen.\n~r~Du skal bruge x%s darkzone points.",
    use_purificator = "Brug renseren",
    darkzone_not_enough_points_to_start_purificator = "Du skal bruge ~r~%sx points~w~ for at start renseren.",
    darkzone_not_enough_points_to_refill_purificator = "Du skal bruge ~r~%sx points~w~ for at genfylde renser.",
    darkzone_too_far_from_purificator = "~r~Du er for langt fra renseren.",
    darkzone_cant_remove_while_running_purificator = "~r~Du kan ikke fjerne genstrande imens renseren er igang.",
    darkzone_purificator_running = "~r~Du kan ikke benytte genstande imens renseren er igang.",
    darkzone_purificator_running_refill = "~r~Du kan ikke fylde maskinen imens renseren er igang.",
    darkzone_put_x_in_purificator = "Du har lagt ~r~%s~w~ i renseren.",
    darkzone_you_took_x_from_purificator = "Du har taget ~r~%s~w~ fra renseren.",
    darkzone_purificator_does_not_need_refill = "Du behøver ikke at ~r~fylde denne renserr~w~.",
    darkzone_refilled_purificator_x = "Du har brugt ~r~x%s points~w~ for at fylde renseren.",
    darkzone_open = "Darkzone landinger er tilgængelige.\n~r~Find en transporter i en safezone.",
    darkzone_item_clean = "Denne genstand er allerede ren.\n~r~Du kan kun putte fourende genstande i.",

    dungeon_cooldown_between = "Vent venligst ~r~%s minutter~w~ før du starter en dungeon igen.",
    set_as_default = "Set as default custom for vehicle model",
    car_custom_presets_saved = "Your customization presets for ~g~%s~w~ have been saved.",
    marketplace_you_received_x_x = "You received ~b~%sx ~g~%s~w~.",

    above_level_x_no_longer_possible_loot_safe = "Player above rank %s cannot loot zombies in safezones.",
    preferred_component_desc = "This set will be the default set of all %s weapon you hold.",
    set_as_preferred_component_class = "Set as preferred component set",
    weapon_presets_updated = "You have set the default component presets for your ~g~%s~w~.",

    -- New survey
    poll6_q1 = "Would you like the crew member limit to be set to 25 members? (more competition, smaller groups)",
    poll6_q2 = "Is your main server fine for your ping? (Is your average ping ok?)",
    poll6_q3 = "Are you playing in private worlds?",
    poll6_q4 = "Should headshots be enabled for season 4?",

    casino_dungeon_desc = "⚠️ ~r~You may need flashlight on your weapon to see well here.",
    dungeon_destroy_wall_obj = "Destroy the wall blocking your path.",
    dungeon_use_key_obj = "Use the key to open the door.",
    dungeon_kill_zombies_obj = "Kill all zombies.",
    dungeon_kill_zombies_obj_x = "~b~Kill all zombies.~w~\n%s/%s of players have killed their zombies.",
    dungeon_use_key_to_open_door = "Use the key to open the door.",
    dungeon_find_key_obj = "Find a key to open the door in the room.",
    take_key = "take the key",
    open_the_door = "open the door",
    dungeon_quit_notif = "Type ~g~/dungeon quit~w~ to leave the dungeon.",
    dungeon_generator_obj = "Find the generator and get the power back.",
    dungeon_press_generator = "Press ~INPUT_CONTEXT~ to toggle the generator.",
    power_generator = "Power generator",
    dungeon_find_c4_obj = "There are blocks of C4 hidden somewhere, find them.",
    dungeon_use_c4_obj = "Use your C4 to blow up the vault door.",
    dungeon_party_help = "Type ~b~\"/dungeon\"~w~ to manage the dungeon party.",
    press_x_to = "Press %s to %s",

    quest_clean_zone = "Clean the zone: %s",
    quest_clean_zone_desc = "Reach %s and clean the area of zombies.",

    loot_crate_light = "Light Loot kasse",
    loot_crate_medium = "Medium Loot kasse",
    loot_crate_high = "High Loot kasse",

    dailymission_killzombieinzoneid = "Zombies killed in the zone",
    dailymission_dungeonbosskilled = "Dungeon boss killed",

    quest_too_far_npc = "~r~You are too far from the quest NPC.",
    quest_already_started_quest = "~r~You have already started this quest.",
    quest_redo_in_x = "~r~You have already done this quest.\n~w~You will be able to redo this quest in ~b~%s",
    quest_max_quests_reached = "~r~You can only accept %s quests.",
    quest_new_accepted = "~g~You accepted a new quest.",
    quest_gave_up = "~r~You gave up this quest.",
    quest_not_completed = "~r~You need to complete all objectives of the quest.",
    quest_already_completed = "~r~You already have completed this quest.",
    quest_all_completed = "~g~You successfully completed all objectives.",
    dungeon_key = "Dungeon key",
    darkzone_cannot_enter_min_levels = "You must be level ~b~%s~w~ to enter the darkzone.",
    darkzone_you_survived_x = "You survived ~r~%s minute(s)~w~ in the darkzone.",
    questmenu_command = "Open the quest menu",
    squadmenu_command = "Open the squad menu",
    airdrop_coming_darkzone = "~r~An airdrop is coming in the darkzone check your map.",
    darkzone_full_crew = "There is already ~r~%s members~w~ of your crew in the darkzone, wait for someone to leave.",

    crew_join_cooldown_x = "You need to wait ~r~%s~w~ before joining this crew.",
    darkzone_not_enough_players_darkzone = "The darkzone will not open.\n~r~Not enough players.",

    dungeon_loot_boss_box = "~g~A chest appeared in the center of the room.",
    drug_antizin_bar = "Antizin effect",
    drug_stamina_bar = "Stamina effect",
    drug_berserker_bar = "Health effect",

    squad_members_limit = "~r~You squad reached the members limit.",
    darkzone_only = "~r~You must be in the darkzone.",
    darkzone_no_cars = "~r~You can only use bikes, boats and other flying vehicles in the darkzone.",

    poll7_q1 = "Would you be interested by a EU server SOLO ONLY?",
    poll7_q2 = "Would you like to see AWP MK2/Marksman rifle MK2 back in the loot/airdrops?",

    you_have_been_muted = "~r~You have been muted.~w~\nExpiration: ~b~%s~w~\nReason: ~b~%s",
    you_have_been_unmuted = "~g~You have been unmuted.",
    muted_x = "You muted ~g~%s~w~.~w~\nExpiration: ~b~%s~w~\nReason: ~b~%s",
    unmuted_x = "You unmuted ~g~%s~w~.",
    invalid_duration = "~r~Incorrect duration, please enter a correct time.",
    player_already_muted = "~r~This player is already muted.",
    player_not_muted = "~r~This player is not muted.",
    you_are_muted = "~r~You are muted.",

    open_mailbox = "open the mailbox",
    you_entered_crew_pro = "~g~You entered your crew bunker.",

    you_player_not_enough_gcoin = "~r~You do not have enough gcoins.",
    other_player_not_enough_gcoin = "~r~The other player does not have enough gcoins.",
    a_player_no_fivem_account_linked = "~r~The other player does not have a fivem account linked.",
    you_no_fivem_account_linked = "~r~To trade gcoins you need to link a FiveM account.",
    trade_gcoin_for_gcoin_not_allowed = "~r~You cannot trade gcoins between players, only from one side.",
    cannot_delete_this_item = "~r~You cannot delete this item.",
    impossible_on_solo_server = "~r~You cannot do that on the solo server.",

    warning_message = "Du spiller på Extinction SOLO-serveren. Du må ikke slå dig sammen med andre spillere, oprette hold eller indgå alliancer. Hvis du bliver fanget i teaming, vil du blive udelukket fra at spille på denne server og også midlertidigt udelukket globalt. Respekter venligst reglerne og spil solo.",
    bank_no_money = "~r~Du har ikke noget penge.",
    bank_deposit_x = "Du indsatted ~g~$%s~w~ i banken.",
    cannot_deposit_money_go_bank = "~r~Bekalger, du kan ikke hæve nogen penge her.\n~w~Besøg aben hos banken.",
    bank_balance_x = "Bank balance: ~g~$%s",
    store_money_bank = "~g~store your money in the bank",
    wait_before_next_action = "Wait ~r~%sms~w~ before moving this item again.",
    bank = "Bank",

    poll8_q1 = "Would you like server 2 (solo server) to be replaced by a duo-only server?",
    poll8_q2 = "Do you like banana?",

    reset_radar_tips = "If you want to reset the radar too, there is another setting for that.",
    redzone_shop = "Redzone shop",
    no_enough_redzone_points = "~r~You do not have enough redzone points.",
    you_paid_basket_rp = "You paid ~r~%s RP~w~ for your basket.",

    redzone_points_balance_x = "Redzone points: ~r~%s",
    top_kills = "Top kills",
    top_zombies = "Top zombies",

    not_allowed_in_this_zone = "~r~You cannot do that in that zone.",
    darkzone_disabled_for_update = "~r~The darkzone is disabled and will be back with updates and improvements.",
    loot_crate_halloween = "Halloween Loot Crate",

    new_weapon = "New weapon",
    winner_title = "Winner",
    left_gungame_party = "~r~You left the gun-game lobby.",
    outfit_gta = "GTA Oufits",

    poll10_q1 = "Where do you believe siphon mode should be enabled?",
    poll_10_q1 = "In redzone only",
    poll_10_q2 = "Everywhere",

    open_lobby_menu = "open the lobby menu",
    choose_game_lobby = "Choose a lobby",

    joined_lobby_x = "~g~You joined the lobby %s.~w~\nGamemode: ~b~%s",
    gun_game = "Gun game",
    spawn = "Spawn",
    return_lobby_help = "If you want to return to the main lobby, type ~b~/lobby.",
    afk_press_key = "AFK?~r~~n~Press the key.",
    sorry_it_is_ok = "~r~Sorry!\n~w~It is ok now.",
    swimming_respawn_help = "~r~You seem to be stuck in water.\n~w~Press ~INPUT_CONTEXT~ to respawn.",
}

AddLanguage("da", my_language)
